// Shared prompt constants for character avatar generation.
//
// Ported from `tools/seed/character_meta.json` so that avatars created via the
// web proposal flow look indistinguishable from those pre-generated by
// `tools/images/generate_avatars_vertex.py` for the main cast. When the Python
// script's prompt tuning changes, update these two strings accordingly.

export const CHARACTER_COMMON_STYLE =
  "stylized geometric biblical character illustration, " +
  "blocky low-poly faceted planes, angular polygon face and hair, " +
  "flat matte vector shading with subtle cut-paper facets, " +
  "strict canonical body proportions, head:torso:legs = 1:1:1 exactly, " +
  "head section one-third of total height, torso section one-third, " +
  "legs section one-third, same body ratio template across all human " +
  "characters, compact adult proportions, not chibi, simple small eyes " +
  "and nose, mature friendly expression, minimal clean outline, " +
  "exactly one character only, solo single subject, full body visible " +
  "from head to toe, both feet visible, whole figure fits inside frame, " +
  "centered, plain white background, high resolution, consistent design " +
  "system across the full cast, distinct silhouette and face geometry " +
  "for each character, distinct hairstyle and story-inspired accessory " +
  "for each character, no text, no watermark";

export const CHARACTER_NEGATIVE_PROMPT =
  "realistic, photoreal, anime, manga, glossy 3D render, clay, pixel art, " +
  "chibi, super-deformed, giant head, baby proportions, oversized eyes, " +
  "long legs, short legs, tiny torso, oversized torso, tiny body, " +
  "stretched body, uneven body ratio, inconsistent body proportions, " +
  "head larger than torso, legs longer than torso, same-face clones, " +
  "duplicate person, multiple people, crowd, group shot, companions, " +
  "side characters, extra faces, extra bodies, twin, mirrored figure, " +
  "close-up, portrait crop, bust shot, half body, cropped head, " +
  "cropped feet, marshmallow body, gritty, dark, horror, complex " +
  "background, text, logo, watermark";

/// Imagen model candidates (tried in order until one succeeds).
///
/// Imagen 4.0 (preview) 는 계정에 따라 allowlist 필요 — 403 이 뜨면
/// 자동으로 3.0 으로 fallback. 명시적으로 고정하고 싶으면 Supabase
/// secret `VERTEX_IMAGEN_MODEL` 에 단일 모델 id 지정.
export const IMAGEN_MODEL_CANDIDATES: string[] = (() => {
  const override = (
    // Deno is available in the Edge Function runtime; guard for type safety
    // in case this file is ever re-used from a Node context.
    (typeof Deno !== "undefined" ? Deno.env.get("VERTEX_IMAGEN_MODEL") : null) ??
    ""
  ).trim();
  if (override) return [override];
  return [
    "imagen-4.0-generate-001",
    "imagen-3.0-generate-002",
    "imagen-3.0-generate-001",
  ];
})();

/// 과거 호환 alias (generate-proposal-character/index.ts 가 초기 import).
export const IMAGEN_MODEL = IMAGEN_MODEL_CANDIDATES[0];

/// Compose the final prompt from user-provided description using the same
/// convention as Python's `resolve_prompt`: if the text contains the literal
/// token "COMMON_STYLE", substitute; otherwise prepend.
export function composeCharacterPrompt(userPrompt: string): string {
  const description = (userPrompt ?? "").trim();
  if (description.length === 0) {
    return CHARACTER_COMMON_STYLE;
  }
  if (description.includes("COMMON_STYLE")) {
    return description.replace("COMMON_STYLE", CHARACTER_COMMON_STYLE).trim();
  }
  return `${CHARACTER_COMMON_STYLE}, ${description}`;
}
