// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7pyz5ZQ7GUnXQFezMUs_CZevYbYb7I0I',
    appId: '1:196457947669:web:a12ecb5408f22cc46f641c',
    messagingSenderId: '196457947669',
    projectId: 'story-bible-491907',
    authDomain: 'story-bible-491907.firebaseapp.com',
    storageBucket: 'story-bible-491907.firebasestorage.app',
    measurementId: 'G-JHLTRK7N32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsREqovA3QFeFRCrWR3Z_kT6fIWlidqpA',
    appId: '1:196457947669:android:458dd6388c71d4eb6f641c',
    messagingSenderId: '196457947669',
    projectId: 'story-bible-491907',
    storageBucket: 'story-bible-491907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpuJHVGQ9SHBPJ_Y050QGcMBDdfFS6v-0',
    appId: '1:196457947669:ios:d79e3acc88e573e86f641c',
    messagingSenderId: '196457947669',
    projectId: 'story-bible-491907',
    storageBucket: 'story-bible-491907.firebasestorage.app',
    iosBundleId: 'com.storybible.app',
  );
}
