-- Generated by tools/seed/build_200_stories_seed_sql.py
-- Generated at UTC: 2026-04-21T13:34:32.658544+00:00
-- Target table: events
-- (character_codes / bible_refs / story_scenes / scene_characters live
--  on the events row itself; character_eras and events_ordered are views.)
begin;

-- Upsert events from 200 stories
with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_primeval', '001 창조: 7일과 안식', '하나님이 말씀으로 세상을 창조하시고 안식으로 완성하신다.', '["완전한 어둠과 혼돈이 가득한 태초의 세계", "하나님의 빛이 임하며 어둠이 갈라지고 질서가 생겨난다", "하늘과 바다와 땅, 식물과 별과 동물이 차례로 채워지고 사람은 전혀 보이지 않는다", "넓은 세상이 고요한 안식에 잠기고 사람은 전혀 보이지 않는다"]'::jsonb, '[[], ["god"], [], []]'::jsonb, ARRAY['god']::text[], '[{"book": "창", "from": "1:1", "to": "2:3"}]'::jsonb, -4000, -4000, 'approx', 1, '메소포타미아(추정)', 31.018, 47.423, 'published'),
    ('era_primeval', '002 에덴: 사람의 창조와 사명', '사람은 에덴에서 돌보고 지키는 사명을 받는다.', '["옷을 입지 않은 아담이 큰 잎과 풀숲에 몸을 가린 채 흙에서 일어나 숨을 들이마시며 눈을 뜬다, 얼굴과 어깨 위주만 보인다", "옷을 입지 않은 아담이 에덴의 큰 잎과 풀숲에 몸을 가린 채 서 있고 하나님의 빛이 가까이 임한다, 얼굴과 상반신 위주만 보인다", "옷을 입지 않은 아담이 큰 잎과 풀숲에 몸을 가린 채 동물들을 바라보며 이름을 붙인다, 얼굴과 상반신 위주만 보인다", "옷을 입지 않은 아담과 하와가 큰 잎과 풀숲 뒤에 몸을 가린 채 서로를 바라본다, 얼굴과 어깨 위주만 보인다"]'::jsonb, '[["adam"], ["god", "adam"], ["adam"], ["adam", "eve"]]'::jsonb, ARRAY['god', 'adam', 'eve']::text[], '[{"book": "창", "from": "2:4", "to": "2:25"}]'::jsonb, -4000, -4000, 'approx', 2, '에덴 지역(추정)', 31.018, 47.423, 'published'),
    ('era_primeval', '003 타락: 뱀의 유혹과 선택', '유혹은 의심을 만들고, 선택은 관계의 균열로 이어진다.', '["옷을 입지 않은 하와가 큰 나무 곁에서 뱀의 유혹을 듣는다, 몸은 잎과 가지에 가려지고 얼굴과 어깨 위주만 보인다", "옷을 입지 않은 하와가 열매를 바라보며 망설이다 손을 뻗는다, 몸은 큰 잎과 풀숲에 가려지고 얼굴과 상반신 위주만 보인다", "옷을 입지 않은 하와가 아담에게 열매를 건네고 아담이 받는다, 두 사람의 몸은 잎과 풀에 가려지고 얼굴과 어깨 위주만 보인다", "아담과 하와가 잎으로 몸을 가린 채 나무 사이에 숨는다, 부끄러움이 덮친다"]'::jsonb, '[["eve"], ["eve"], ["eve", "adam"], ["adam", "eve"]]'::jsonb, ARRAY['eve', 'adam']::text[], '[{"book": "창", "from": "3:1", "to": "3:13"}]'::jsonb, -3995, -3995, 'approx', 3, '에덴 지역(추정)', 31.018, 47.423, 'published'),
    ('era_primeval', '004 추방: 동산 밖으로', '죄의 결과로 사람은 에덴을 떠나고, 길은 막힌다.', '["하나님의 빛 앞에서 아담과 하와가 거친 가죽옷을 입은 채 고개를 숙이고 결과를 듣는다", "하나님이 아담과 하와에게 거친 가죽옷을 입혀 준다", "아담과 하와가 거친 가죽옷을 입은 채 동산 문을 나선다, 침묵의 발걸음", "생명나무로 가는 길이 막히고 불칼이 번쩍인다"]'::jsonb, '[["god", "adam", "eve"], ["god", "adam", "eve"], ["adam", "eve"], []]'::jsonb, ARRAY['god', 'adam', 'eve']::text[], '[{"book": "창", "from": "3:14", "to": "3:24"}]'::jsonb, -3995, -3995, 'approx', 4, '에덴 동쪽(추정)', 31.09, 47.52, 'published'),
    ('era_primeval', '005 가인과 아벨: 들판의 비극', '분노가 다스려지지 않자 형제가 형제를 해친다.', '["두 형제가 제사를 드린다, 표정 대비", "하나님의 빛이 임하고, 가인이 이를 악문다", "들판에서 가인이 아벨을 덮친다, 직접 묘사 없이 충격", "하나님의 빛이 임하고, 가인은 책임을 피한다"]'::jsonb, '[["cain", "abel"], ["god", "cain", "abel"], ["cain", "abel"], ["god", "cain"]]'::jsonb, ARRAY['cain', 'abel', 'god']::text[], '[{"book": "창", "from": "4:1", "to": "4:16"}]'::jsonb, -3950, -3950, 'approx', 5, '에덴 밖 들판(추정)', 31.16, 47.61, 'published'),
    ('era_primeval', '006 셋의 계보: 다시 부르다', '끊긴 듯한 역사 속에서도 하나님을 찾는 흐름이 이어진다.', '["seth가 seth가 seth가 seth가 결연한 표정으로 선다", "세대가 지나가며 이름들이 이어진다, 계보", "seth가 seth가 사람들이 여호와의 이름을 부르기 시작한다, 예배 앞쪽에 서 있다", "에녹이 하나님과 동행하는 모습으로 마무리된다"]'::jsonb, '[["seth"], [], ["seth"], []]'::jsonb, ARRAY['seth']::text[], '[{"book": "창", "from": "4:25", "to": "5:24"}]'::jsonb, -3900, -3100, 'approx', 6, '근동(상징)', 33, 44, 'published'),
    ('era_primeval', '007 홍수 전의 타락: 노아를 주목하다', '폭력으로 가득 찬 세상 속에서 하나님은 노아에게 길을 여신다.', '["혼란과 폭력이 번지는 앞쪽에 서 있고, 거리의 소란", "하나님의 빛이 임한다", "노아가 조용히 방주 설계 도면을 펼친다", "노아가 첫 나무를 자르며 준비를 시작한다"]'::jsonb, '[[], ["god"], ["noah"], ["noah"]]'::jsonb, ARRAY['god', 'noah']::text[], '[{"book": "창", "from": "6:1", "to": "6:22"}]'::jsonb, -2500, -2500, 'approx', 7, '근동', 33, 44, 'published'),
    ('era_primeval', '008 방주와 홍수: 문이 닫히다', '구원의 문이 닫히고 물이 땅을 덮는다.', '["노아 가족이 방주로 들어가고 짐승들이 따라 들어온다", "문이 닫히는 둔탁한 소리, 바깥 소리가 끊긴다", "폭우와 물기둥, 방주가 크게 흔들리며 떠오른다", "물이 잦아들고 방주 문이 열리며 새 땅이 보인다"]'::jsonb, '[["noah"], [], [], []]'::jsonb, ARRAY['noah']::text[], '[{"book": "창", "from": "7:1", "to": "8:19"}]'::jsonb, -2500, -2499, 'approx', 8, '방주(근동)', 33, 44, 'published'),
    ('era_primeval', '009 무지개 언약: 다시는', '하나님은 무지개로 언약을 표징하시며 새 출발을 약속하신다.', '["노아가 제단을 쌓고 고개 숙인다, 연기가 위로 오른다", "하나님의 빛이 임한다", "비구름이 걷히고 햇빛만 비치며 사람은 보이지 않는다", "무지개가 선명하게 걸리고 노아가 올려다본다"]'::jsonb, '[["noah"], ["god"], [], ["noah"]]'::jsonb, ARRAY['god', 'noah']::text[], '[{"book": "창", "from": "8:20", "to": "9:17"}]'::jsonb, -2499, -2499, 'approx', 9, '아라랏 산지(전승)', 39.7, 44.3, 'published'),
    ('era_primeval', '010 바벨탑: 언어가 갈라지다', '자기 이름을 세우려던 계획은 언어의 혼잡으로 멈춘다.', '["배경과 분위기만 보이는", "탑이 올라가며 사람들의 얼굴이 도취된다", "갑자기 말이 안 통한다, 손짓만 커지고 싸움이 난다", "공사가 멈추고 사람들이 각기 다른 방향으로 흩어진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['god']::text[], '[{"book": "창", "from": "11:1", "to": "11:9"}]'::jsonb, -2200, -2200, 'approx', 10, '시날 평지(바벨론, 전승)', 32.54, 44.42, 'published'),
    ('era_patriarch', '011 아브라함의 부르심: 떠나라', '하나님이 아브라함을 부르시고 약속의 길을 여신다.', '["하란의 일상 속에서 아브라함이 멈춰 서서 먼 곳을 바라본다", "하나님의 빛이 임하고 아브라함이 숨을 고른다", "아브라함이 장막을 접고 가족이 짐을 낙타에 싣는다", "가나안으로 향하는 길 위에서 아브라함이 제단을 세운다"]'::jsonb, '[["abraham"], ["abraham", "god"], ["abraham"], ["abraham"]]'::jsonb, ARRAY['abraham', 'god']::text[], '[{"book": "창", "from": "12:1", "to": "12:9"}]'::jsonb, -2100, -2100, 'approx', 1, '하란', 36.87, 39.03, 'published'),
    ('era_patriarch', '012 애굽 우회: 두려움의 선택', '기근과 두려움 속에서 아브라함은 위험한 거짓말을 선택한다.', '["메마른 땅, 기근 속 행렬이 애굽으로 향한다", "아브라함이 사라에게 속삭인다", "궁정 쪽으로 끌려가는 사라, 긴장, 아브라함은 굳은 얼굴", "재앙 후 사라가 돌아오고, 아브라함은 급히 떠난다"]'::jsonb, '[[], ["abraham", "sarah"], ["abraham", "sarah"], ["abraham", "sarah"]]'::jsonb, ARRAY['abraham', 'sarah']::text[], '[{"book": "창", "from": "12:10", "to": "12:20"}]'::jsonb, -2099, -2099, 'approx', 2, '애굽(멤피스 일대, 전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '013 롯과 분리: 시선의 선택', '갈등을 피하려 한 분리가 훗날의 방향을 가른다.', '["목자들이 다투고, 아브라함이 손을 들어 멈추게 한다", "아브라함이 앞쪽에 서 있고, 양보를 제안한다", "롯이 푸른 요단 들을 가리키며 선택한다", "아브라함이 남은 땅에 서서 제단을 세운다"]'::jsonb, '[["abraham"], ["abraham"], ["lot"], ["abraham"]]'::jsonb, ARRAY['abraham', 'lot']::text[], '[{"book": "창", "from": "13:1", "to": "13:18"}]'::jsonb, -2098, -2098, 'approx', 3, '요단 들(전승)', 31.8, 35.6, 'published'),
    ('era_patriarch', '014 전쟁과 멜기세덱: 축복의 만남', '아브라함은 롯을 구출하고, 멜기세덱에게 축복을 받는다.', '["전령이 사로잡힘 소식을 전하자 아브라함이 굳은 얼굴로 멈춰 선다", "아브라함이 사람들을 이끌고 야간 추격을 준비한다", "전투 후 롯을 되찾고 돌아오는 아브라함의 행렬", "멜기세덱이 떡과 포도주를 내며 아브라함을 축복한다"]'::jsonb, '[["abraham"], ["abraham"], ["abraham", "lot"], ["abraham", "melchizedek"]]'::jsonb, ARRAY['abraham', 'lot', 'melchizedek']::text[], '[{"book": "창", "from": "14:1", "to": "14:24"}]'::jsonb, -2097, -2097, 'approx', 4, '살렘(예루살렘, 전승)', 31.78, 35.22, 'published'),
    ('era_patriarch', '015 별 언약: 믿음이 의로', '하나님은 별처럼 많은 자손을 약속하시고 언약을 확증하신다.', '["밤하늘 아래 하나님의 빛이 임한다", "아브라함이 셀 수 없는 별을 바라보다가 조용히 고개를 끄덕인다", "아브라함이 암소와 암염소와 숫양의 고기를 쪼개어 언약 의식을 준비한다", "어두운 밤, 아브라함이 지켜보는 가운데 하나님의 횃불 같은 빛이 쪼갠 고기 사이를 지나간다"]'::jsonb, '[["god"], ["abraham"], ["abraham"], ["abraham", "god"]]'::jsonb, ARRAY['abraham', 'god']::text[], '[{"book": "창", "from": "15:1", "to": "15:21"}]'::jsonb, -2096, -2096, 'approx', 5, '가나안(전승)', 31.5, 35, 'published'),
    ('era_patriarch', '016 하갈과 이스마엘: 사람의 방법', '기다림이 길어지자 가정에 갈등이 들어오고 하갈은 광야로 나간다.', '["사라가 결연한 표정으로 선다", "하갈의 시선이 바뀌고, 사라와 갈등이 폭발한다", "광야 길, 하갈이 눈물로 주저앉는다", "하나님의 위로, 하갈이 다시 일어나 길을 따른다"]'::jsonb, '[["sarah"], ["sarah", "hagar"], ["hagar"], ["hagar"]]'::jsonb, ARRAY['abraham', 'sarah', 'hagar', 'ishmael']::text[], '[{"book": "창", "from": "16:1", "to": "16:16"}]'::jsonb, -2090, -2090, 'approx', 6, '가나안(전승)', 31.5, 35, 'published'),
    ('era_patriarch', '017 할례 언약: 이름이 바뀌다', '언약의 표가 주어지고 아브라함과 사라의 이름이 바뀐다.', '["하나님의 빛이 임한다", "아브람이 엎드리고, 아브라함으로 불린다", "사래가 사라로 불리며 약속이 구체화된다", "언약의 표가 선포되고 아브라함이 결단한다"]'::jsonb, '[["god"], ["abraham"], ["sarah"], ["abraham"]]'::jsonb, ARRAY['abraham', 'sarah', 'god']::text[], '[{"book": "창", "from": "17:1", "to": "17:27"}]'::jsonb, -2088, -2088, 'approx', 7, '가나안(전승)', 31.5, 35, 'published'),
    ('era_patriarch', '018 세 손님: 웃음과 약속', '손님을 맞이한 아브라함의 집에 불가능해 보이던 약속이 다시 선포된다.', '["더운 낮, 아브라함이 세 손님을 보고 장막 밖으로 뛰어나가 맞이한다", "사라가 장막 안에서 급히 음식을 준비하며 긴장한 표정을 짓는다", "사라가 장막 뒤에서 숨은 채 웃음을 참지 못한다", "하나님의 빛이 아브라함 앞에서 머물고, 장막 뒤에서 그 말을 듣던 사라의 얼굴이 굳는다"]'::jsonb, '[["abraham"], ["sarah"], ["sarah"], ["abraham", "god", "sarah"]]'::jsonb, ARRAY['abraham', 'sarah', 'god']::text[], '[{"book": "창", "from": "18:1", "to": "18:15"}]'::jsonb, -2087, -2087, 'approx', 8, '마므레(헤브론, 전승)', 31.53, 35.1, 'published'),
    ('era_patriarch', '019 소돔을 위한 중보: 숫자가 줄어들다', '아브라함은 의인을 위해 담대하게 간구하며 하나님의 공의를 붙든다.', '["멀리 소돔 방향을 바라보는 아브라함의 실루엣", "아브라함이 하나님의 빛 앞에서 간절히 중보를 시작한다", "아브라함이 땅에 엎드려 하나님께 간절히 기도한다", "기도를 마친 아브라함이 무거운 발걸음으로 자기 장막 쪽으로 돌아간다"]'::jsonb, '[["abraham"], ["abraham", "god"], ["abraham", "god"], ["abraham"]]'::jsonb, ARRAY['abraham', 'god']::text[], '[{"book": "창", "from": "18:16", "to": "18:33"}]'::jsonb, -2087, -2087, 'approx', 9, '마므레(전승)', 31.53, 35.1, 'published'),
    ('era_patriarch', '020 소돔 멸망과 롯 구출', '도시는 심판을 받고 롯의 가족은 급히 나오지만 뒤돌아봄이 비극을 만든다.', '["밤의 소돔에서 롯이 두 천사를 자기 집 안으로 급히 들여 숨겨 준다", "아직 불타지 않은 도시를 뒤로 두고 롯이 아내와 두 딸을 재촉하며 허둥지둥 달린다", "롯과 아내와 두 딸이 도망가고 뒤편 도시에는 불길과 연기가 치솟기 시작한다", "롯의 아내는 소금기둥이 되고, 롯과 두 딸은 불타는 성을 뒤로한 채 달아난다"]'::jsonb, '[["lot"], ["lot"], ["lot"], ["lot"]]'::jsonb, ARRAY['lot']::text[], '[{"book": "창", "from": "19:1", "to": "19:29"}]'::jsonb, -2086, -2086, 'approx', 10, '소돔 일대(사해 남부, 전승)', 31.2, 35.5, 'published'),
    ('era_patriarch', '021 아브라함과 아비멜렉: 오해와 보호', '아브라함의 두려움이 다시 거짓을 낳지만 하나님이 사라를 지키신다.', '["그랄 입성, 아브라함과 사라가 결연한 표정으로 선다", "아비멜렉의 궁정, 사라가 끌려가는 긴장", "밤의 꿈, 경고를 받은 아비멜렉이 놀라 깬다", "사라가 돌아오고, 아브라함은 변명 대신 침묵한다"]'::jsonb, '[["abraham", "sarah"], ["sarah", "abimelech"], ["abimelech"], ["abraham", "sarah"]]'::jsonb, ARRAY['abraham', 'sarah', 'abimelech']::text[], '[{"book": "창", "from": "20:1", "to": "20:18"}]'::jsonb, -2085, -2085, 'approx', 11, '그랄(전승)', 31.37, 34.45, 'published'),
    ('era_patriarch', '022 이삭 탄생과 하갈 추방', '약속의 아들이 태어나지만 가정의 갈등은 하갈을 광야로 내몬다.', '["사라가 아기 이삭을 안고 환하게 웃는다", "사라의 차가운 눈빛이 앞쪽에 크게 보이고, 뒤편에서는 열 살쯤 된 이스마엘이 어린 이삭을 놀린다", "하갈이 물가죽을 들고 열 살쯤 된 이스마엘과 함께 집을 떠난다", "하갈이 우물 앞에서 열 살쯤 된 이스마엘을 안아 일으켜 세운다"]'::jsonb, '[["sarah", "isaac"], ["sarah", "isaac", "ishmael"], ["hagar", "ishmael"], ["hagar", "ishmael"]]'::jsonb, ARRAY['abraham', 'sarah', 'isaac', 'hagar', 'ishmael']::text[], '[{"book": "창", "from": "21:1", "to": "21:21"}]'::jsonb, -2066, -2066, 'approx', 12, '브엘세바 주변(전승)', 31.25, 34.8, 'published'),
    ('era_patriarch', '023 이삭 번제: 멈추게 하시는 하나님', '극한의 시험 속에서 하나님은 아브라함을 멈추게 하시고 대안을 준비하신다.', '["새벽, 아브라함이 나무를 챙기고 서른 살 남짓한 젊은 이삭이 곁에서 함께 길을 나선다", "아브라함과 서른 살 남짓한 젊은 이삭이 산 위에 서 있고 하나님의 빛이 임한다", "제단 위에 누운 서른 살 남짓한 젊은 이삭 곁에서 아브라함의 손이 떨린다", "아브라함이 풀숲 뒤의 숫양을 보고 서른 살 남짓한 젊은 이삭을 풀어준다"]'::jsonb, '[["abraham", "isaac"], ["abraham", "isaac", "god"], ["abraham", "isaac"], ["abraham", "isaac"]]'::jsonb, ARRAY['abraham', 'isaac', 'god']::text[], '[{"book": "창", "from": "22:1", "to": "22:14"}]'::jsonb, -2055, -2055, 'approx', 13, '모리아(예루살렘, 전승)', 31.78, 35.22, 'published'),
    ('era_patriarch', '024 사라의 죽음과 막벨라 굴', '아브라함은 약속의 땅에서 첫 소유지로 묘지를 산다.', '["사라의 죽음 앞에서 아브라함이 조용히 울며 고개를 숙인다", "성문 앞에서 아브라함이 예의를 지키며 매장지를 요청한다", "아브라함이 은을 세어 땅값을 직접 지불한다", "막벨라 굴에 장사한 뒤 아브라함이 오래 서 있다"]'::jsonb, '[["abraham", "sarah"], ["abraham"], ["abraham"], ["abraham"]]'::jsonb, ARRAY['abraham', 'sarah']::text[], '[{"book": "창", "from": "23:1", "to": "23:20"}]'::jsonb, -2030, -2030, 'approx', 14, '헤브론(막벨라, 전승)', 31.53, 35.1, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_patriarch', '025 리브가: 이삭의 결혼', '기도와 만남을 통해 리브가가 이삭의 아내로 선택된다.', '["늙은 종이 여러 낙타를 끌고 우물 곁으로 천천히 다가간다", "우물가에서 리브가가 물을 길어 낙타들에게까지 먹인다", "늙은 종과 낙타들, 리브가가 함께 리브가의 집으로 들어간다", "사십 대쯤의 젊은 이삭이 들판에서 리브가를 처음 맞이한다"]'::jsonb, '[[], ["rebekah"], ["rebekah"], ["isaac", "rebekah"]]'::jsonb, ARRAY['isaac', 'rebekah']::text[], '[{"book": "창", "from": "24:1", "to": "24:67"}]'::jsonb, -2026, -2026, 'approx', 15, '하란 주변(전승)', 36.87, 39.03, 'published'),
    ('era_patriarch', '026 장자권: 한 그릇의 거래', '에서는 배고픔에 장자의 권리를 가볍게 팔고 야곱은 그것을 붙잡는다.', '["사냥에서 돌아온 에서가 지친 몸으로 장막으로 들어온다", "붉은 죽 냄새 앞에서 에서가 허기를 참지 못하고 야곱을 바라본다", "야곱이 장자권을 요구하고 에서가 망설인다", "에서가 허겁지겁 먹고, 뒤편에서는 야곱이 그 모습을 지켜본다"]'::jsonb, '[["esau"], ["esau", "jacob"], ["esau", "jacob"], ["esau", "jacob"]]'::jsonb, ARRAY['esau', 'jacob']::text[], '[{"book": "창", "from": "25:19", "to": "25:34"}]'::jsonb, -2006, -2006, 'approx', 16, '브엘세바 일대(전승)', 31.25, 34.8, 'published'),
    ('era_patriarch', '027 축복 가로채기: 속임수의 밤', '야곱은 속임수로 이삭의 축복을 받고 도망길에 오른다.', '["늙은 리브가가 급히 계획을 말하고 야곱이 망설인다", "야곱이 염소 가죽을 두르고 늙은 이삭 앞에 선다, 숨죽인 긴장", "에서가 이삭 앞에서 기도해 달라고 간청하지만, 이삭은 더 줄 축복이 없다는 듯 고개를 떨군다", "에서가 돌아와 울부짖고, 야곱은 짐을 챙겨 도망친다"]'::jsonb, '[["jacob", "rebekah"], ["jacob", "isaac"], ["esau", "isaac"], ["jacob", "esau"]]'::jsonb, ARRAY['jacob', 'esau', 'isaac', 'rebekah']::text[], '[{"book": "창", "from": "27:1", "to": "27:45"}]'::jsonb, -1985, -1985, 'approx', 17, '브엘세바 일대(전승)', 31.25, 34.8, 'published'),
    ('era_patriarch', '028 벧엘의 꿈: 사다리와 약속', '도망자 야곱은 길 위에서 ‘함께하심’의 약속을 받는다.', '["야곱이 돌을 베고 누운다, 밤바람 소리만 들린다", "배경과 분위기만 보이는", "하나님의 빛이 임한다", "야곱이 돌기둥을 세우고 기름을 붓는다, 여기가 하나님의 집이다"]'::jsonb, '[["jacob"], [], ["god"], ["jacob", "god"]]'::jsonb, ARRAY['jacob', 'god']::text[], '[{"book": "창", "from": "28:10", "to": "28:22"}]'::jsonb, -1985, -1985, 'approx', 18, '벧엘(전승)', 31.93, 35.22, 'published'),
    ('era_patriarch', '029 라반의 집: 레아와 라헬', '야곱은 라헬을 사랑하지만 속임수로 레아와도 결혼하게 된다.', '["우물가에서 라헬을 처음 본 야곱이 큰 돌을 옮긴다", "라반이 야곱과 계약을 맺고, 라반은 야곱보다 훨씬 늙어 보인다", "혼인 밤, 얼굴을 가린 신부를 두고 아침에 레아임을 알아차린 야곱이 충격을 받는다", "야곱이 다시 7년을 약속하고 라헬을 맞는다"]'::jsonb, '[["jacob", "rachel"], ["laban", "jacob"], ["jacob", "leah"], ["jacob", "rachel"]]'::jsonb, ARRAY['jacob', 'laban', 'leah', 'rachel']::text[], '[{"book": "창", "from": "29:1", "to": "29:30"}]'::jsonb, -1984, -1977, 'approx', 19, '하란(전승)', 36.87, 39.03, 'published'),
    ('era_patriarch', '030 열두 아들의 시작: 이름에 담긴 마음', '경쟁과 상처 속에서도 열두 지파의 뿌리가 형성된다.', '["레아가 결연한 표정으로 선다", "라헬이 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "아이들이 늘어나고 장막 사이 경쟁이 깊어진다", "마지막에 라헬이 요셉을 낳고 안도의 숨을 쉰다"]'::jsonb, '[["leah"], ["rachel"], [], ["rachel"]]'::jsonb, ARRAY['jacob', 'leah', 'rachel']::text[], '[{"book": "창", "from": "29:31", "to": "30:24"}]'::jsonb, -1977, -1965, 'approx', 20, '하란(전승)', 36.87, 39.03, 'published'),
    ('era_patriarch', '031 야곱의 번성: 양떼의 기묘한 계약', '야곱은 라반의 집에서 번성하고 라반과 갈등이 깊어진다.', '["야곱이 떠나겠다고 말하자 라반이 붙잡는다", "양떼 계약이 정해지고, 야곱이 표식을 구분한다", "야곱의 떼가 늘어나며 라반의 얼굴이 굳는다", "야곱이 가족에게 속삭인다, 이제 떠나야 한다"]'::jsonb, '[["jacob", "laban"], ["jacob"], ["jacob", "laban"], ["jacob"]]'::jsonb, ARRAY['jacob', 'laban']::text[], '[{"book": "창", "from": "30:25", "to": "31:16"}]'::jsonb, -1965, -1961, 'approx', 21, '하란(전승)', 36.87, 39.03, 'published'),
    ('era_patriarch', '032 도피와 언약: 라반과의 마지막', '야곱은 라반을 떠나고, 추격 끝에 언약으로 갈등을 마무리한다.', '["야곱이 밤에 장막을 접고 몰래 길을 나선다", "라반이 분노한 얼굴로 추격해 따라잡는다", "야곱과 라반이 격한 말다툼 끝에 돌무더기를 쌓아 경계 표를 만든다", "야곱과 라반이 서로 맹세하고 각자의 길로 갈라진다"]'::jsonb, '[["jacob"], ["laban"], ["jacob", "laban"], ["jacob", "laban"]]'::jsonb, ARRAY['jacob', 'laban']::text[], '[{"book": "창", "from": "31:17", "to": "31:55"}]'::jsonb, -1961, -1961, 'approx', 22, '길르앗(전승)', 32, 35.7, 'published'),
    ('era_patriarch', '033 얍복강 씨름: 이스라엘', '야곱은 밤새 씨름하며 새 이름 ‘이스라엘’을 받는다.', '["강가의 어둠 속에서 야곱이 혼자 숨을 고른다", "천사 같은 신비한 존재가 야곱을 붙잡고 서로 씨름을 시작한다", "신비한 존재가 야곱을 쓰러뜨리며 야곱이 땅에 넘어간다", "이스라엘이라는 새 이름을 받은 야곱이 절뚝이며 동틀 무렵 선다"]'::jsonb, '[["jacob"], ["jacob"], ["jacob"], ["jacob"]]'::jsonb, ARRAY['jacob']::text[], '[{"book": "창", "from": "32:24", "to": "32:32"}]'::jsonb, -1960, -1960, 'approx', 23, '얍복 강가(전승)', 32.06, 35.74, 'published'),
    ('era_patriarch', '034 에서와 화해: 달려오는 형', '두려움으로 맞이한 재회는 포옹과 눈물로 풀린다.', '["야곱이 가족을 줄 세우고 멀리 에서를 보며 긴장한다", "에서가 달려오고 야곱이 땅에 엎드린다", "에서가 야곱을 껴안고 울고 야곱도 울음을 삼킨다", "야곱이 준비한 선물을 에서에게 직접 건네며 화해를 확인한다"]'::jsonb, '[["jacob", "esau"], ["jacob", "esau"], ["jacob", "esau"], ["jacob", "esau"]]'::jsonb, ARRAY['jacob', 'esau']::text[], '[{"book": "창", "from": "33:1", "to": "33:11"}]'::jsonb, -1960, -1960, 'approx', 24, '야복/에돔 경계(전승)', 32.1, 35.6, 'published'),
    ('era_patriarch', '035 디나 사건: 복수의 폭발', '상처는 복수로 번지고 야곱의 가족은 더 큰 위험에 놓인다.', '["디나 사건 이후 장막 안의 공기가 얼어붙고 모두가 충격에 잠긴다", "협상 테이블에서 시므온과 레위는 싸늘한 눈빛으로 앉아 있고 다른 남자들은 옅은 미소를 지으며 말을 건넨다", "시므온과 레위가 칼을 들고 급히 달아나고 뒤편에는 어떤 남자가 침대에 누워 있는 실루엣이 보인다", "야곱이 절망한 얼굴로 고개를 감싸 쥔다"]'::jsonb, '[[], ["simeon", "levi"], ["simeon", "levi"], ["jacob"]]'::jsonb, ARRAY['dinah', 'simeon', 'levi', 'jacob']::text[], '[{"book": "창", "from": "34:1", "to": "34:31"}]'::jsonb, -1958, -1958, 'approx', 25, '세겜(전승)', 32.22, 35.28, 'published'),
    ('era_patriarch', '036 벧엘 귀환: 라헬의 죽음', '야곱의 가정은 이동 중 큰 상실을 겪고도 약속의 길을 이어간다.', '["야곱이 결연한 표정으로 귀환 길을 재촉한다", "길 위에서 라헬이 진통하고 그 곁에 선 야곱이 초조하게 지켜본다", "라헬의 숨이 가늘어지고 갓난 베냐민 옆에서 야곱이 비통한 얼굴로 서 있다", "야곱이 무덤 기둥을 세우고 오래 서 있다"]'::jsonb, '[["jacob"], ["rachel", "jacob"], ["rachel", "benjamin", "jacob"], ["jacob"]]'::jsonb, ARRAY['jacob', 'rachel', 'benjamin']::text[], '[{"book": "창", "from": "35:1", "to": "35:20"}]'::jsonb, -1955, -1955, 'approx', 26, '베들레헴 길(전승)', 31.7, 35.2, 'published'),
    ('era_patriarch', '037 요셉의 꿈: 형제들의 시기', '요셉의 꿈과 편애가 형제들의 마음을 뒤틀리게 한다.', '["17세 안팎의 어린 요셉이 채색옷을 입고 형들 사이를 지나가자 미묘한 거리감이 흐른다", "17세 안팎의 어린 요셉이 꿈을 이야기하자 형들의 표정이 굳는다", "야곱이 17세 안팎의 어린 요셉을 꾸짖지만 마음속에는 그 말을 담아둔다", "형제들의 시기와 긴장이 장막 사이에 짙게 깔린다"]'::jsonb, '[["joseph"], ["joseph"], ["jacob", "joseph"], []]'::jsonb, ARRAY['joseph', 'jacob', 'reuben', 'simeon', 'levi', 'judah', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun', 'benjamin']::text[], '[{"book": "창", "from": "37:1", "to": "37:11"}]'::jsonb, -1915, -1915, 'approx', 27, '헤브론 주변(전승)', 31.53, 35.1, 'published'),
    ('era_patriarch', '038 요셉이 팔리다: 구덩이와 은', '시기는 요셉을 구덩이에 던지고 끝내 종으로 팔아넘긴다.', '["17세 안팎의 어린 요셉이 멀리서 오자 형들이 모여 속삭인다", "17세 안팎의 어린 요셉의 옷을 빼앗고 구덩이에 던지자 절규가 메아리친다", "유다가 다른 형들을 말리며 손을 뻗어 제지한다", "형들의 손에 은이 쥐어지고 멀리서는 17세 안팎의 어린 요셉이 상인들에게 끌려가듯 팔려간다"]'::jsonb, '[["joseph"], ["joseph"], ["judah", "reuben", "simeon", "levi", "naphtali", "gad", "asher", "issachar", "zebulun"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"]]'::jsonb, ARRAY['joseph', 'judah', 'reuben', 'simeon', 'levi', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun']::text[], '[{"book": "창", "from": "37:12", "to": "37:36"}]'::jsonb, -1915, -1915, 'approx', 28, '도단(전승)', 32.42, 35.18, 'published'),
    ('era_patriarch', '040 보디발의 집: 성실과 누명', '요셉은 유혹을 거절하지만 누명을 쓰고 감옥으로 내려간다.', '["요셉이 보디발의 집 살림을 정리하며 신뢰를 얻고 열쇠를 넘겨받는다", "한 여자가 침대에 앉아 다리를 꼰 채 요셉에게 말을 걸고, 요셉은 앞쪽에 서서 굳은 표정으로 대답한다", "옷을 남기고 달아나는 요셉 뒤로 여자의 고함이 터진다", "감옥에 갇힌 요셉이 죄수들의 일을 맡아 분주히 정리한다"]'::jsonb, '[["joseph"], ["joseph"], ["joseph"], ["joseph"]]'::jsonb, ARRAY['joseph', 'potiphar']::text[], '[{"book": "창", "from": "39:1", "to": "39:23"}]'::jsonb, -1910, -1909, 'approx', 29, '애굽(전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '041 감옥의 꿈: 술 맡은 관원장', '요셉은 감옥에서 두 관원의 꿈을 해석하고도 잊혀진다.', '["감옥의 아침에 두 관원의 얼굴이 어둡게 가라앉아 있다", "요셉이 두 관원의 꿈 이야기를 차분히 듣는다", "꿈 해석이 맞아 술 맡은 관원장이 바로에게 잔을 바친다", "술 맡은 자는 복귀하지만 요셉은 감옥 창살 곁에 홀로 남는다"]'::jsonb, '[[], ["joseph"], [], ["joseph"]]'::jsonb, ARRAY['joseph']::text[], '[{"book": "창", "from": "40:1", "to": "40:23"}]'::jsonb, -1909, -1909, 'approx', 30, '애굽 감옥(전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '042 바로의 꿈: 총리 요셉', '바로의 꿈을 해석한 요셉은 애굽의 총리로 세워진다.', '["바로가 꿈에서 깨어 불안해하고 신하들이 술렁인다", "요셉이 궁전으로 들어가는 긴 복도를 빠르게 걸어간다", "요셉이 일곱 해 풍년과 일곱 해 흉년을 설명하며 계획을 제시한다", "바로가 옆에서 지켜보는 가운데, 요셉은 파라오가 아닌 애굽의 총리로서 절제된 흰 관복과 금청 장식, 얇은 머리띠를 하고 사람들 앞에 선다"]'::jsonb, '[["pharaoh"], ["joseph"], ["joseph"], ["pharaoh", "joseph"]]'::jsonb, ARRAY['joseph', 'pharaoh']::text[], '[{"book": "창", "from": "41:1", "to": "41:57"}]'::jsonb, -1900, -1900, 'approx', 31, '애굽(전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '043 기근: 형제들의 1차 방문', '기근 속에 형제들은 애굽으로 오고, 요셉은 그들을 시험하기 시작한다.', '["애굽 성문으로 들어오는 형제들을, 파라오처럼 보이지 않는 애굽 총리 요셉이 절제된 관복 차림으로 지켜본다", "파라오처럼 보이지 않는 애굽 총리 요셉 앞에 형제들이 무릎 꿇는다", "파라오처럼 보이지 않는 애굽 총리 요셉이 형제들에게 화를 내며 날카롭게 몰아붙인다", "시므온이 묶이고, 형제들은 두려움 속에 애굽을 떠나 가나안으로 돌아간다"]'::jsonb, '[["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"], ["reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"]]'::jsonb, ARRAY['joseph', 'reuben', 'simeon', 'levi', 'judah', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun']::text[], '[{"book": "창", "from": "42:1", "to": "42:38"}]'::jsonb, -1885, -1885, 'approx', 32, '애굽(곡물 창고, 전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '044 2차 방문: 잔치와 긴장', '베냐민과 함께 돌아온 형제들에게 요셉은 예상 밖의 잔치를 베푼다.', '["베냐민이 결연한 표정으로 선다", "파라오처럼 보이지 않는 애굽 총리 요셉이 베냐민을 보자 눈빛이 흔들리고 자리를 피한다", "파라오처럼 보이지 않는 애굽 총리 요셉이 주재하는 잔치에서 형제들이 불안해하며 앉는다", "베냐민에게 유독 많은 몫이 주어지고, 형제들이 서로 눈치를 본다"]'::jsonb, '[["benjamin"], ["joseph", "benjamin"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"], ["reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun", "benjamin"]]'::jsonb, ARRAY['joseph', 'reuben', 'simeon', 'levi', 'judah', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun', 'benjamin']::text[], '[{"book": "창", "from": "43:1", "to": "43:34"}]'::jsonb, -1885, -1885, 'approx', 33, '애굽(요셉의 집, 전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '045 은잔 사건: 유다의 탄원', '은잔이 베냐민 자루에서 발견되고 유다는 자신을 대신 내놓는다.', '["형제들이 떠나자마자 추격자가 따라붙는다", "자루를 뒤지다 베냐민 자루에서 잔이 나온다, 얼굴이 하얘진다", "파라오처럼 보이지 않는 애굽 총리 요셉 앞에 유다가 앞으로 나온다", "유다가 앞쪽에 서 있고, 형제들의 눈에 눈물이 맺힌다"]'::jsonb, '[["reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"], ["benjamin"], ["joseph", "judah"], ["judah", "reuben", "simeon", "levi", "naphtali", "gad", "asher", "issachar", "zebulun"]]'::jsonb, ARRAY['joseph', 'judah', 'reuben', 'simeon', 'levi', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun', 'benjamin']::text[], '[{"book": "창", "from": "44:1", "to": "44:34"}]'::jsonb, -1885, -1885, 'approx', 34, '애굽-가나안 길(전승)', 30.3, 32, 'published'),
    ('era_patriarch', '046 요셉의 정체 공개: 울음의 방', '요셉은 더 이상 참지 못하고 형제들에게 자신을 드러낸다.', '["파라오처럼 보이지 않는 애굽 총리 요셉이 종들에게 모두 물러가라고 손짓한다", "파라오처럼 보이지 않는 애굽 총리 요셉이 형들 앞에서 울음을 터뜨리자 형들은 당황해 얼어붙는다", "요셉이 총리의 겉모습 일부를 내려놓고 자신이 요셉임을 밝히자 형들이 크게 놀란다", "파라오처럼 보이지 않는 총리 차림의 요셉이 베냐민을 끌어안고, 형들은 뒤에서 놀란 얼굴로 그 모습을 바라본다"]'::jsonb, '[["joseph"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun", "benjamin"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun", "benjamin"], ["joseph", "benjamin", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun"]]'::jsonb, ARRAY['joseph', 'reuben', 'simeon', 'levi', 'judah', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun', 'benjamin']::text[], '[{"book": "창", "from": "45:1", "to": "45:15"}]'::jsonb, -1885, -1885, 'approx', 35, '애굽(요셉의 집, 전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '048 고센 정착: 만남과 눈물', '요셉은 야곱을 맞이하고, 이스라엘은 고센에 자리 잡는다.', '["애굽 총리의 옷을 입은 요셉이 전차를 타고 고센으로 급히 달려간다", "애굽 총리의 옷을 입은 요셉과 야곱이 마주 보고 끌어안는다", "애굽 총리의 옷을 입은 요셉이 가족을 바로 앞에 세우며 예의를 지킨다", "바로와 야곱이 서로 이야기하고 그 사이에 애굽 총리의 옷을 입은 요셉이 서 있다"]'::jsonb, '[["joseph"], ["jacob", "joseph"], ["joseph", "pharaoh"], ["pharaoh", "jacob", "joseph"]]'::jsonb, ARRAY['jacob', 'joseph', 'pharaoh']::text[], '[{"book": "창", "from": "46:28", "to": "47:12"}]'::jsonb, -1880, -1879, 'approx', 36, '고센 땅(나일 델타, 전승)', 30.8, 31.85, 'published'),
    ('era_patriarch', '049 야곱의 축복: 열두 아들', '야곱은 마지막 순간 아들들을 불러 각 지파의 길을 예언적으로 선언한다.', '["늙은 야곱이 침상에서 상체를 일으킨다", "애굽 총리의 옷을 입은 요셉이 두 아들을 데려오고 야곱의 손이 교차한다", "늙은 야곱이 아들들을 바라보며 무거운 축복의 말을 남긴다", "턱수염과 머리가 하얗게 센 늙은 야곱이 마지막 숨을 고르며 눈을 감는다"]'::jsonb, '[["jacob"], ["jacob", "joseph"], ["jacob"], ["jacob"]]'::jsonb, ARRAY['jacob', 'joseph', 'reuben', 'judah', 'benjamin']::text[], '[{"book": "창", "from": "48:1", "to": "48:22"}, {"book": "창", "from": "49:1", "to": "49:28"}]'::jsonb, -1860, -1860, 'approx', 37, '애굽(전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '050 요셉의 마지막: 뼈를 기억하라', '요셉은 용서를 확증하고, 언젠가 돌아갈 땅을 바라보며 마지막을 남긴다.', '["애굽 총리의 옷을 입은 요셉이 형들과 함께 아버지를 장사하는 행렬 속에 서 있다", "애굽 총리의 옷을 입은 요셉이 두려워하는 형들을 향해 손을 저으며 위로한다", "늙은 요셉이 애굽의 도시를 바라보며 먼 미래를 생각한다", "요셉이 관 속에 평안히 누워 있다"]'::jsonb, '[["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun", "benjamin"], ["joseph", "reuben", "simeon", "levi", "judah", "naphtali", "gad", "asher", "issachar", "zebulun", "benjamin"], ["joseph"], ["joseph"]]'::jsonb, ARRAY['joseph', 'reuben', 'simeon', 'levi', 'judah', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun', 'benjamin']::text[], '[{"book": "창", "from": "50:1", "to": "50:26"}]'::jsonb, -1805, -1805, 'approx', 38, '애굽(전승)', 29.85, 31.25, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_exodus', '051 이스라엘의 압제와 산파들', '바로는 이스라엘을 두려워해 학대하고, 산파들은 하나님을 두려워해 생명을 지킨다.', '["벽돌 굽는 현장, 감독의 고함과 지친 얼굴들", "바로의 명령이 내려온다, 남자 아기는 죽여라", "산파들이 서로를 바라본다, 떨리지만 고개를 끄덕인다", "아기가 숨 쉬는 소리, 산파들이 조용히 아이를 품고 숨긴다"]'::jsonb, '[[], ["pharaoh"], [], []]'::jsonb, ARRAY['pharaoh']::text[], '[{"book": "출", "from": "1:1", "to": "1:22"}]'::jsonb, -1446, -1446, 'approx', 1, '애굽(고센 일대, 전승)', 30.8, 31.85, 'published'),
    ('era_exodus', '052 모세의 탄생과 갈대상자', '죽음의 명령 속에서 한 아기가 갈대상자에 실려 기적처럼 보호받는다.', '["어머니가 아기를 꼭 안고 숨죽인다, 밖에서 발소리가 지나간다", "갈대상자에 역청을 바르고 조심히 물가에 띄운다", "아기의 누이가 멀리서 상자가 어떻게 되는지 지켜본다", "바로의 딸이 상자를 열고 아기를 안는다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['moses', 'miriam']::text[], '[{"book": "출", "from": "2:1", "to": "2:10"}]'::jsonb, -1446, -1446, 'approx', 2, '나일강(전승)', 29.9, 31.25, 'published'),
    ('era_exodus', '053 모세의 분노와 미디안 도피', '모세는 억압을 보고 분노하지만, 결국 광야로 도망쳐 새 삶을 시작한다.', '["모세가 노역 현장을 바라보다 주먹을 꽉 쥔다", "폭력이 터지고, 모세가 숨 가쁘게 멈춰 선다, 후회", "소문이 퍼지고 바로의 분노가 번진다, 모세가 급히 떠난다", "미디안 우물가, 모세가 낯선 사람들을 돕고 물을 길어준다"]'::jsonb, '[["moses"], ["moses"], ["moses"], ["moses"]]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "2:11", "to": "2:25"}]'::jsonb, -1406, -1406, 'approx', 3, '애굽 → 미디안(전승)', 29.9, 31.25, 'published'),
    ('era_exodus', '054 불타는 떨기나무: 모세의 소명', '광야에서 하나님은 모세를 부르시고 ‘내가 너와 함께’라는 약속을 주신다.', '["모세가 양을 몰다 불타는 떨기나무를 발견하고 멈춘다", "모세가 신을 벗고 떨며 선다", "하나님의 빛이 임한다", "모세가 망설이자 내가 너와 함께하리라가 울린다"]'::jsonb, '[["moses"], ["moses"], ["god"], ["moses"]]'::jsonb, ARRAY['moses', 'god']::text[], '[{"book": "출", "from": "3:1", "to": "3:22"}, {"book": "출", "from": "4:1", "to": "4:17"}]'::jsonb, -1446, -1446, 'approx', 4, '호렙 산(전승)', 28.54, 33.98, 'published'),
    ('era_exodus', '055 바로 앞 첫 대면: 짐이 더 무거워지다', '해방 요구와 표징 앞에서도 바로는 마음을 굳게 하고 노역을 더 무겁게 만든다.', '["모세와 아론이 바로 앞에 선다", "바로가 모세와 아론을 비웃는다", "벽돌 공장, 짚이 끊기고 사람들이 절망한다", "모세가 바로 앞에 지팡이를 던지자 뱀이 되고 궁정이 술렁인다"]'::jsonb, '[["moses", "aaron", "pharaoh"], ["moses", "aaron", "pharaoh"], [], ["moses", "aaron", "pharaoh"]]'::jsonb, ARRAY['moses', 'aaron', 'pharaoh']::text[], '[{"book": "출", "from": "5:1", "to": "7:13"}]'::jsonb, -1446, -1446, 'approx', 5, '애굽 궁정(전승)', 29.9, 31.25, 'published'),
    ('era_exodus', '056 재앙의 시작: 물이 변하다', '하나님은 열 가지 재앙으로 바로의 완강함을 흔드시지만, 바로는 끝까지 마음을 굳힌다.', '["세로 3등분 구도: 위에는 나일강 물이 피로 변해 사람들이 충격에 빠진 모습, 가운데에는 개구리가 집과 궁으로 몰려 올라오는 모습, 아래에는 이가 사람과 가축의 몸에 달라붙어 모두가 괴로워하는 모습", "세로 3등분 구도: 위에는 파리가 바로의 궁을 가득 메운 모습, 가운데에는 애굽의 가축들이 들판에서 떼죽음을 당해 사람들이 망연한 모습, 아래에는 악성 종기로 고통스러워하는 사람들이 몸을 움츠린 모습", "세로 3등분 구도: 위에는 우박이 애굽 전역에 쏟아지는 모습, 가운데에는 메뚜기가 땅을 뒤덮는 모습, 아래에는 흑암이 온 땅을 덮어 사람들이 더듬으며 서 있는 모습", "모세가 바로 앞에서 애굽의 초태생이 모두 죽게 될 것이라고 엄중히 경고한다, 궁정의 공기가 얼어붙는다"]'::jsonb, '[[], [], [], ["moses", "pharaoh"]]'::jsonb, ARRAY['moses', 'aaron', 'pharaoh']::text[], '[{"book": "출", "from": "7:14", "to": "11:10"}]'::jsonb, -1446, -1446, 'approx', 6, '나일강(전승)', 29.9, 31.25, 'published'),
    ('era_exodus', '057 유월절: 피로 표시된 문', '이스라엘은 유월절을 준비하며 ‘보호의 표’를 문에 남긴다.', '["가족들이 급히 무교병을 준비한다, 집 안은 숨죽인 긴장", "모세의 지시가 전달된다, 이 밤은 여호와의 유월절이라", "문설주에 표식을 남긴다, 손의 떨림과 결심", "밤, 바깥의 공포와 안의 침묵이 대비된다"]'::jsonb, '[[], ["moses"], [], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "12:1", "to": "12:14"}]'::jsonb, -1446, -1446, 'approx', 7, '고센(전승)', 30.8, 31.85, 'published'),
    ('era_exodus', '058 출애굽의 밤: 떠나라는 명령', '마침내 바로가 떠나라 말하고, 이스라엘은 급히 길을 나선다.', '["밤의 애굽, 집집마다 초태생의 죽음으로 사람들이 침상 곁에서 오열한다, 시신은 직접적으로 보이지 않고 슬픔과 충격만 절제되게 표현", "밤에 바로가 모세에게 당장 나가라고 말한다, 궁정은 무겁고 다급하다", "모세와 백성들이 반죽과 짐을 들고 애굽을 떠나 광야로 나아간다", "불기둥/구름기둥, 이스라엘이 전진한다"]'::jsonb, '[[], ["moses", "pharaoh"], ["moses"], []]'::jsonb, ARRAY['moses', 'pharaoh']::text[], '[{"book": "출", "from": "12:29", "to": "13:22"}]'::jsonb, -1446, -1446, 'approx', 8, '애굽 → 광야(전승)', 30.8, 31.85, 'published'),
    ('era_exodus', '059 홍해: 길이 열리다', '막다른 길에서 하나님이 길을 여시고 백성은 두려움에서 믿음으로 옮겨간다.', '["뒤엔 군대, 앞엔 바다, 백성이 원망하며 멈춰 선다", "모세가 두 손을 들어 다급하게 몸짓한다", "갈라진 물 벽 사이로 모세가 앞서고 백성들이 아이들과 짐을 이끌며 건너간다", "모두가 건넌 뒤, 물이 합쳐지고 백성은 숨을 몰아쉬며 찬양한다"]'::jsonb, '[[], ["moses"], ["moses"], []]'::jsonb, ARRAY['moses', 'pharaoh']::text[], '[{"book": "출", "from": "14:10", "to": "14:31"}]'::jsonb, -1446, -1446, 'approx', 9, '홍해/갈대바다(전승)', 29.5, 34.9, 'published'),
    ('era_exodus', '060 마라: 쓴 물이 달아지다', '광야의 첫 위기에서 하나님은 쓴 물을 바꾸며 백성을 가르치신다.', '["사람들이 물을 마시고 뱉는다, 써서 못 마신다!", "원망이 커지고 모세가 한쪽으로 물러나 기도한다", "모세가 지시받은 나무를 물에 던진다", "사람들이 다시 물을 마신다, 표정이 풀리며 행렬이 움직인다"]'::jsonb, '[[], ["moses"], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "15:22", "to": "15:27"}]'::jsonb, -1446, -1446, 'approx', 10, '마라(전승)', 28.7, 33.4, 'published'),
    ('era_exodus', '061 만나와 메추라기: 하늘의 양식', '먹을 것이 없던 광야에서 하나님은 매일의 양식을 주시며 ‘신뢰’를 훈련하신다.', '["백성이 불평한다, 애굽의 냄비가 그립다", "아침, 땅 위에 하얀 것들이 덮인다, 이것이 무엇이냐?", "모세가 결연한 표정으로 선다", "집 안에 쌓아 둔 만나가 벌레가 생기고 냄새가 나며 썩어 간다, 사람들이 놀라 뒤로 물러선다"]'::jsonb, '[[], [], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "16:1", "to": "16:36"}]'::jsonb, -1446, -1446, 'approx', 11, '신 광야(전승)', 28.9, 33.3, 'published'),
    ('era_exodus', '062 아말렉 전투: 팔이 내려갈 때', '전투의 승패는 숫자가 아니라 ‘붙드는 손’에서 드러난다.', '["여호수아가 병력을 정리하고 달려나간다", "언덕 위 모세가 손을 들자 이스라엘이 밀어붙인다", "아론과 훌이 양쪽에서 받친다", "해 질 무렵 승리, 모세가 결연한 표정으로 선다"]'::jsonb, '[["joshua"], ["moses"], ["moses", "aaron"], ["moses"]]'::jsonb, ARRAY['moses', 'joshua', 'aaron']::text[], '[{"book": "출", "from": "17:8", "to": "17:16"}]'::jsonb, -1446, -1446, 'approx', 12, '르비딤(전승)', 28.75, 33.35, 'published'),
    ('era_exodus', '063 시내산 도착: 산이 떨리다', '이스라엘은 시내산에서 언약 백성으로 부름받을 준비를 한다.', '["광야 끝, 산이 보이고 백성이 진을 친다", "모세가 산을 오르며 뒤돌아본다, 사람들은 숨죽인다", "천둥과 연기, 백성이 울타리 밖에서 떤다", "모세가 결연한 표정으로 선다"]'::jsonb, '[[], ["moses"], [], ["moses"]]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "19:1", "to": "19:25"}]'::jsonb, -1446, -1446, 'approx', 13, '시내산(전승)', 28.54, 33.98, 'published'),
    ('era_exodus', '064 시내산 도착: 십계명과 하나님 기준', '하나님은 구원받은 백성에게 살아갈 길을 선포하신다.', '["하나님의 빛이 산 위에서 음성이 울린다", "계명이 차례로 선포되고 백성은 떨며 뒤로 물러선다", "모세가 고개를 끄덕인다", "모세가 어두운 구름 속으로 들어간다, 결단의 뒷모습"]'::jsonb, '[["god"], [], ["moses"], ["moses"]]'::jsonb, ARRAY['moses', 'god']::text[], '[{"book": "출", "from": "20:1", "to": "24:18"}]'::jsonb, -1446, -1446, 'approx', 14, '시내산(전승)', 28.54, 33.98, 'published'),
    ('era_exodus', '066 금송아지: 아래에서 벌어진 일', '기다림을 견디지 못한 백성은 우상을 만들고 언약을 깨뜨린다.', '["백성이 아론을 둘러싼다", "금이 모이고 송아지 형상이 세워진다, 환호가 터진다", "산에서 내려오는 모세, 소리를 듣고 표정이 굳는다", "모세가 돌판을 던져 깨뜨린다, 진영이 얼어붙는다"]'::jsonb, '[["aaron"], [], ["moses"], ["moses"]]'::jsonb, ARRAY['moses', 'aaron']::text[], '[{"book": "출", "from": "32:1", "to": "32:35"}]'::jsonb, -1446, -1446, 'approx', 15, '시내산 진(전승)', 28.54, 33.98, 'published'),
    ('era_exodus', '067 모세의 중보: 다시 시작', '모세는 백성을 위해 중보하고 하나님은 관계 회복의 길을 여신다.', '["모세가 장막 밖에서 기도한다, 얼굴에 간절함", "모세가 앞쪽에 서 있다", "하나님의 빛이 임한다", "새 돌판을 들고 내려오는 모세, 관계의 재출발"]'::jsonb, '[["moses"], ["moses"], ["god"], ["moses"]]'::jsonb, ARRAY['moses', 'god']::text[], '[{"book": "출", "from": "33:7", "to": "33:23"}, {"book": "출", "from": "34:1", "to": "34:10"}]'::jsonb, -1446, -1446, 'approx', 16, '시내산(전승)', 28.54, 33.98, 'published'),
    ('era_exodus', '068 성막: 영광이 임하다', '성막이 세워지고 하나님의 임재가 진 가운데 머문다.', '["사람들이 예물을 가져온다, 손마다 재료가 들려 있다", "장인들이 천과 기구를 만들고 기둥을 세운다, 빠른", "모세가 성막을 세우고 마지막 천을 당긴다", "구름이 덮이고 영광이 임한다, 사람들은 말없이 바라본다"]'::jsonb, '[[], [], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "35:1", "to": "40:38"}]'::jsonb, -1445, -1445, 'approx', 17, '광야 진(전승)', 29, 34, 'published'),
    ('era_exodus', '069 나답·아비후: 가까이함의 무게', '거룩을 가볍게 여기자 충격적 사건이 발생하고 공동체는 떨며 배운다.', '["제사장들이 분주히 움직인다, 분위기가 들떠 있다", "분향단 앞에 두 사람이 쓰러져 움직이지 않고, 그 위로 여호와의 불이 크게 타오르며 주변 사람들이 놀라 뒤로 물러난다, 피는 보이지 않음", "모세가 결연한 표정으로 선다", "공동체가 침묵 속에 정돈된다, 거룩의 무게가 남는다"]'::jsonb, '[["nadab", "abihu"], [], ["aaron", "moses"], []]'::jsonb, ARRAY['aaron', 'nadab', 'abihu', 'moses']::text[], '[{"book": "레", "from": "10:1", "to": "10:11"}]'::jsonb, -1445, -1445, 'approx', 18, '성막(광야)', 29, 34, 'published'),
    ('era_exodus', '070 가데스 정탐: 불신의 보고', '정탐 보고는 두려움을 키우고, 불신은 광야 방황로 이어진다.', '["정탐꾼들이 큰 포도송이를 들고 돌아온다, 기대가 오른다", "거인은 크다는 말이 퍼지며 군중의 얼굴이 창백해진다", "여호수아가 두 손을 들어 다급하게 몸짓한다", "원망이 폭발하고, 모세가 얼굴을 땅에 대며 중보한다"]'::jsonb, '[[], [], ["joshua"], ["moses"]]'::jsonb, ARRAY['moses', 'joshua', 'caleb']::text[], '[{"book": "민", "from": "13:1", "to": "13:33"}, {"book": "민", "from": "14:1", "to": "14:35"}]'::jsonb, -1445, -1445, 'approx', 19, '가데스바네아(전승)', 30.63, 34.8, 'published'),
    ('era_exodus', '071 고라의 반역: 땅이 갈라지다', '권위를 뒤흔든 반역은 공동체를 갈라놓고, 심판은 두려운 경고가 된다.', '["세 명의 남자가 한편이 되어 모세 앞에서 거칠게 반항하고 주변 무리가 숨죽여 지켜본다", "모세가 그들을 향해 분노와 슬픔이 섞인 얼굴로 강하게 말한다", "갈라진 땅과 지진의 긴장 옆에서 모세가 결연하게 서 있다", "군중이 뒤로 물러난다, 두려움이 진을 덮는다"]'::jsonb, '[["korah"], ["moses", "korah"], ["moses"], []]'::jsonb, ARRAY['moses', 'korah', 'aaron']::text[], '[{"book": "민", "from": "16:1", "to": "16:35"}]'::jsonb, -1444, -1444, 'approx', 20, '광야 진(전승)', 30, 34, 'published'),
    ('era_exodus', '072 놋뱀: 바라보라', '원망 속에서 고통이 번지지만, 하나님은 ‘바라봄’으로 살 길을 주신다.', '["백성이 모세를 둘러싸고 원망을 쏟아낸다, 왜 우리를 이 광야로 데려왔느냐", "불뱀들이 진영에 나타나 백성을 물어 사람들이 공포에 빠진다, 피나 상처는 직접 보이지 않음", "모세가 장대를 세우고 표징을 올린다", "사람들이 고개를 들어 바라본다, 얼굴이 서서히 안정된다"]'::jsonb, '[[], [], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "민", "from": "21:4", "to": "21:9"}]'::jsonb, -1408, -1408, 'approx', 21, '광야(에돔 길, 전승)', 30, 35.5, 'published'),
    ('era_exodus', '074 모압의 유혹과 비느하스', '유혹이 공동체를 무너뜨리려 할 때, 비느하스의 결단이 위기를 멈춘다.', '["배경과 분위기만 보이는", "진영에 긴장과 슬픔이 번진다, 모세가 고개를 숙인다", "비느하스가 앞으로 나와 결단한다, 빠른 움직임", "혼란이 멈추고, 진영에 다시 질서가 돌아온다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['phinehas']::text[], '[{"book": "민", "from": "25:1", "to": "25:13"}]'::jsonb, -1407, -1407, 'approx', 22, '싯딤(전승)', 31.85, 35.55, 'published'),
    ('era_exodus', '075 모세의 마지막: 느보 산', '모세는 약속의 땅을 바라보고, 다음 세대에 길을 맡긴다.', '["모세가 산길을 오르며 숨을 고른다", "정상에서 멀리 땅을 바라본다, 눈빛이 오래 머문다", "모세가 조용히 고개를 숙인다, 말 없는 작별", "여호수아가 백성 앞에 서서 말하고, 백성들이 그의 말을 경청하며 따를 준비를 한다"]'::jsonb, '[["moses"], [], ["moses"], ["joshua"]]'::jsonb, ARRAY['moses', 'joshua']::text[], '[{"book": "신", "from": "34:1", "to": "34:12"}]'::jsonb, -1406, -1406, 'approx', 23, '느보 산(전승)', 31.77, 35.73, 'published'),
    ('era_judges', '076 요단강 도하: 물이 멈추다', '이스라엘은 요단강을 건너며 약속의 땅에 들어선다.', '["여호수아가 시켜 제사장들이 언약궤를 메고 요단강 앞에 선다", "제사장들의 발이 물을 밟자 요단강 물이 갈라진다", "이스라엘 백성이 마른 땅으로 요단강을 건너간다", "여호수아가 시켜 열두 사람이 제사장들의 발이 섰던 곳에 돌을 세운다"]'::jsonb, '[["joshua"], [], [], ["joshua"]]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "3:1", "to": "4:24"}]'::jsonb, -1406, -1406, 'approx', 1, '요단강(여리고 맞은편, 전승)', 31.85, 35.55, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_judges', '077 여리고: 침묵의 행진', '상식을 깨는 순종의 행진 끝에 성벽이 무너진다.', '["여리고 성벽 아래, 침묵 속 행렬이 한 바퀴 돈다", "나팔 소리만 울리고 사람들은 말이 없다", "일곱째 날, 일곱 바퀴, 긴장감이 최고조가 된다", "외쳐라!, 함성과 함께 성벽이 흔들리며 무너진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "6:1", "to": "6:20"}]'::jsonb, -1406, -1406, 'approx', 2, '여리고', 31.87, 35.44, 'published'),
    ('era_judges', '078 아간: 감춘 것이 드러나다', '숨긴 탐욕이 공동체의 패배로 드러나고, 정리가 시작된다.', '["아이 성 공격이 실패하고 군이 흩어진다, 여호수아가 찢어진 옷으로 엎드린다", "이스라엘 중에 범죄함이 있다는 선언, 진영이 술렁인다", "제비가 좁혀지며 아간이 떨며 선다", "여호수아가 뒤에 서 있고, 사람들이 아간에게 돌을 던지며 심판한다, 직접 묘사는 절제한다"]'::jsonb, '[["joshua"], [], ["achan"], ["joshua", "achan"]]'::jsonb, ARRAY['joshua', 'achan']::text[], '[{"book": "수", "from": "7:1", "to": "7:26"}]'::jsonb, -1406, -1406, 'approx', 3, '아이 성 근처(전승)', 31.93, 35.25, 'published'),
    ('era_judges', '079 기브온 조약: 속임수의 동맹', '기브온은 속임수로 조약을 맺고, 이스라엘은 그 약속을 지킨다.', '["해진 옷과 마른 떡을 든 기브온 사절단이 여호수아를 찾아온다", "여호수아가 그들의 말을 믿고 조약을 맺는다, 긴장감이 흐른다", "정체가 드러나자 진영이 분노한다", "여호수아가 그들에게 나무 패는 자와 물 긷는 자가 되라고 명령한다"]'::jsonb, '[["joshua"], ["joshua"], [], ["joshua"]]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "9:3", "to": "9:27"}]'::jsonb, -1405, -1405, 'approx', 4, '기브온(전승)', 31.85, 35.18, 'published'),
    ('era_judges', '080 세겜 언약 갱신: 선택하라', '여호수아는 백성에게 ‘오늘 누구를 섬길지’ 선택을 요구한다.', '["세겜에 모인 백성, 여호수아가 지팡이를 짚고 선다", "여호수아가 앞쪽에 서 있다", "백성들이 여호수아에게 고개 숙여 인사하며 우리도 하나님을 따르겠다고 말한다", "여호수아가 상수리나무 아래 큰 돌을 세우고, 백성들이 지켜본다"]'::jsonb, '[["joshua"], ["joshua"], ["joshua"], ["joshua"]]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "24:1", "to": "24:28"}]'::jsonb, -1380, -1380, 'approx', 5, '세겜', 32.22, 35.28, 'published'),
    ('era_judges', '081 사사 시대의 반복: 잊고, 부르짖고, 구원받고', '이스라엘은 반복되는 타락과 회복의 사이클 속에 살아간다.', '["시간이 흐르고 세대가 바뀌며 기억이 희미해진다", "우상이 들어오고 억압이 시작된다, 어두운 톤", "배경과 분위기만 보이는", "사사가 일어나고 평안이 오지만, 다시 반복될 기미가 보인다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "삿", "from": "2:10", "to": "2:19"}]'::jsonb, -1375, -1375, 'approx', 6, '가나안(전승)', 31.8, 35.1, 'published'),
    ('era_judges', '082 에훗: 왼손의 반전', '에훗은 예상 밖의 방식으로 억압을 끊고 탈출한다.', '["이스라엘 백성이 여호와 앞에서 악을 행하며 우상을 숭배한다", "이스라엘 백성이 모압 왕 에글론을 섬기며 무거운 조공을 바친다", "에훗이 조공을 들고 모압 왕 에글론에게 들어간다", "왕은 왕좌 앞 바닥에 움직이지 않게 누워 있고, 에훗은 재빨리 도망간다"]'::jsonb, '[[], ["eglon"], ["ehud", "eglon"], ["ehud", "eglon"]]'::jsonb, ARRAY['ehud', 'eglon']::text[], '[{"book": "삿", "from": "3:12", "to": "3:30"}]'::jsonb, -1320, -1320, 'approx', 7, '여리고/모압 경계(전승)', 31.85, 35.5, 'published'),
    ('era_judges', '084 기드온의 소명: 두려움 속의 표징', '기드온은 두려움 속에서 부르심을 받고, 표징으로 확신을 얻는다.', '["기드온이 포도주 틀에서 몰래 타작한다, 눈치 보는 표정", "큰 용사여라는 부름에 기드온이 어이없어한다", "기드온이 제물을 놓고 기다린다, 순간 불빛이 일어난다", "기드온이 숨을 몰아쉬며 무릎 꿇는다"]'::jsonb, '[["gideon"], ["gideon"], ["gideon"], ["gideon"]]'::jsonb, ARRAY['gideon']::text[], '[{"book": "삿", "from": "6:11", "to": "6:24"}]'::jsonb, -1160, -1160, 'approx', 8, '오브라(전승)', 32.5, 35.3, 'published'),
    ('era_judges', '085 기드온 300: 횃불과 나팔', '적은 수의 300명이 공포를 뒤집는 소리로 승리를 만든다.', '["병력이 줄어드는 앞쪽에 서 있고, 기드온이 놀라지만 고개를 끄덕인다", "밤, 300명이 항아리·횃불·나팔을 든다", "여호와와 기드온의 칼!, 항아리를 깨뜨리고 빛이 터진다", "이스라엘이 추격한다"]'::jsonb, '[["gideon"], [], ["gideon"], []]'::jsonb, ARRAY['gideon']::text[], '[{"book": "삿", "from": "7:1", "to": "7:22"}]'::jsonb, -1160, -1160, 'approx', 9, '미디안 진(전승)', 32.35, 35.55, 'published'),
    ('era_judges', '086 아비멜렉: 왕 노릇의 비극', '권력을 움켜쥔 아비멜렉의 길은 폭력과 파멸로 끝난다.', '["욕심 가득한 얼굴의 아비멜렉이 형제들을 죽인 뒤 차갑게 서 있고, 뒤에는 형제들이 쓰러져 있다", "한 아이가 사람들에게 나무들이 서로 대화하는 비유를 들려준다", "욕심 가득한 아비멜렉이 여러 전쟁을 일으켜 많은 사람이 쓰러지고 성읍이 불타는 모습", "한 여인이 성 위에서 맷돌을 떨어뜨리고, 아래의 아비멜렉은 치명상을 입고 무너진다"]'::jsonb, '[["abimelech"], [], ["abimelech"], ["abimelech"]]'::jsonb, ARRAY['abimelech']::text[], '[{"book": "삿", "from": "9:1", "to": "9:57"}]'::jsonb, -1135, -1135, 'approx', 10, '세겜(전승)', 32.22, 35.28, 'published'),
    ('era_judges', '087 입다: 서원과 상처', '입다는 승리를 원하며 서원을 하지만, 그 말은 깊은 상처를 남긴다.', '["전쟁 전, 입다가 혼자 서원하며 중얼거린다", "전투의 승전 소식, 사람들이 환호한다", "집 문이 열리고 가장 먼저 달려나온 딸을 보고 입다의 얼굴이 굳는다", "입다와 딸이 침묵 속에 마주 서 있고, 서원의 무게가 장면을 누른다"]'::jsonb, '[["jephthah"], [], ["jephthah"], ["jephthah"]]'::jsonb, ARRAY['jephthah']::text[], '[{"book": "삿", "from": "11:29", "to": "11:40"}]'::jsonb, -1100, -1100, 'approx', 11, '길르앗(전승)', 32, 35.7, 'published'),
    ('era_judges', '088 삼손: 힘의 비밀과 마지막 기도', '삼손은 은사를 남용하다 무너지고, 마지막에 하나님께 부르짖는다.', '["배경과 분위기만 보이는 앞쪽에 서 있고, 삼손은 웃으며 넘기다 점점 지친다", "비밀을 말하는 순간, 공기가 싸늘해진다, 삼손의 눈빛이 흔들린다", "붙잡힌 삼손이 어둠 속에서 고개를 숙인다, 침묵", "삼손이 마지막으로 기도한다, 나를 기억하소서"]'::jsonb, '[["samson", "delilah"], ["samson", "delilah"], ["samson"], ["samson"]]'::jsonb, ARRAY['samson', 'delilah']::text[], '[{"book": "삿", "from": "16:4", "to": "16:31"}]'::jsonb, -1080, -1080, 'approx', 12, '블레셋 지역(가사/소렉, 전승)', 31.5, 34.45, 'published'),
    ('era_judges', '089 미가의 우상: 마음대로의 신앙', '미가는 우상을 만들어 숭배했고, 단 지파는 이 우상과 레위 제사장을 강탈하여 평화로운 라이스 사람들을 공격, 영토를 빼앗고 우상 숭배를 확산시켰습니다.', '["미가가 어머니의 저주를 듣고 훔친 돈을 고백한 뒤, 은신상을 만들고 집안에 신당을 차려 우상 숭배를 시작한다", "미가가 레위인 요나단을 개인 제사장으로 세우고 집 신당 앞에 세운다", "단 지파 사람들이 미가의 집에서 은신상과 에봇과 드라빔과 제사장을 빼앗아 간다", "단 지파가 평화롭게 살던 라이스 사람들을 멸하고 그 땅을 차지한 뒤, 강탈한 우상을 세워 숭배한다"]'::jsonb, '[["micah"], ["micah", "jonathan"], ["micah", "jonathan"], []]'::jsonb, ARRAY['micah', 'jonathan']::text[], '[{"book": "삿", "from": "17:1", "to": "18:31"}]'::jsonb, -1070, -1070, 'approx', 13, '에브라임 산지(전승)', 32.1, 35.2, 'published'),
    ('era_judges', '090 베냐민 전쟁: 공동체의 붕괴', '한 사건이 연쇄 폭력으로 번지며 이스라엘 내부 전쟁으로 이어진다.', '["충격적 소식이 지파들에 퍼지고 분노가 폭발한다", "지파들이 모여 결의를 다진다, 분위기가 살벌해진다", "israelites가 israelites가 israelites가 israelites가 israelites가 israelites가 전투가 반복되고, 승리에도 얼굴에는 슬픔이 남는다", "마지막에 왕이 없으므로 각기 소견대로라는 공허가 남는다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "삿", "from": "19:1", "to": "21:25"}]'::jsonb, -1060, -1060, 'approx', 14, '기브아(전승)', 31.85, 35.25, 'published'),
    ('era_judges', '091 룻의 귀향: 따라가겠습니다', '룻은 모든 것을 내려놓고 나오미를 따라 약속의 땅으로 돌아온다.', '["나오미가 결연한 표정으로 선다, 룻이 고개를 젓는다", "룻이 결연한 표정으로 선다", "두 사람이 길을 걸어 베들레헴에 도착한다", "마을 사람들이 웅성거린다, 나오미는 씁쓸히 웃는다"]'::jsonb, '[["ruth", "naomi"], ["ruth"], ["ruth", "naomi"], ["naomi"]]'::jsonb, ARRAY['ruth', 'naomi']::text[], '[{"book": "룻", "from": "1:6", "to": "1:18"}]'::jsonb, -1100, -1100, 'approx', 15, '모압 → 베들레헴', 31.7, 35.2, 'published'),
    ('era_judges', '092 보아스의 은혜: 이삭 줍는 자리', '룻은 이삭을 줍다 보아스를 만나고, 보호와 은혜를 경험한다.', '["룻이 베들레헴 들판에서 고개 숙여 이삭을 줍는다", "보아스가 들판에서 룻을 바라보는 장면", "밤에 룻이 보아스의 잠자리 발치에 조용히 누워 있다", "룻이 곡식단을 들고 나오미에게 돌아간다"]'::jsonb, '[["ruth"], ["ruth", "boaz"], ["ruth", "boaz"], ["ruth", "naomi"]]'::jsonb, ARRAY['ruth', 'boaz']::text[], '[{"book": "룻", "from": "2:1", "to": "3:18"}]'::jsonb, -1100, -1100, 'approx', 16, '베들레헴 들판', 31.7, 35.2, 'published'),
    ('era_judges', '093 기업 무를 자: 문 앞의 결정', '보아스는 공적인 자리에서 룻을 맞아들이며 가문을 세운다.', '["성문에 장로들이 모인다, 보아스가 결연한 표정으로 선다", "보아스가 엘리멜렉의 소유지를 사는 장면", "보아스와 룻이 결혼하는 장면", "룻이 아이를 낳고, 나오미가 웃으며 아기를 품에 안고 있다"]'::jsonb, '[["boaz"], ["boaz"], ["boaz", "ruth"], ["ruth", "naomi"]]'::jsonb, ARRAY['boaz', 'ruth', 'naomi']::text[], '[{"book": "룻", "from": "4:1", "to": "4:17"}]'::jsonb, -1100, -1100, 'approx', 17, '베들레헴 성문', 31.7, 35.2, 'published'),
    ('era_judges', '094 사무엘의 탄생: 한나의 눈물', '한나는 눈물의 기도로 사무엘을 얻고, 약속대로 하나님께 드린다.', '["실로 성막 앞, 한나가 입술만 움직이며 울고 있다", "엘리가 오해하지만, 한나의 진심을 듣고 축복한다", "아이가 태어나고, 한나가 품에 안고 조용히 웃는다", "사무엘이 결연한 표정으로 선다"]'::jsonb, '[[], [], [], ["samuel"]]'::jsonb, ARRAY['hannah', 'eli', 'samuel']::text[], '[{"book": "삼상", "from": "1:1", "to": "1:28"}]'::jsonb, -1105, -1105, 'approx', 18, '실로', 31.9, 35.3, 'published'),
    ('era_judges', '095 언약궤 사건: 회개와 승리', '언약궤의 아픔 이후, 백성은 회개하고 하나님은 구원을 보여주신다.', '["전투에서 언약궤를 들고 나가지만 패배한다", "블레셋 땅에서 재앙이 번지며 언약궤가 불편한 존재가 된다", "사무엘이 두 손을 들어 다급하게 몸짓한다", "블레셋이 올라오지만, 하나님이 도우시고 백성이 승리한다"]'::jsonb, '[[], [], ["samuel"], []]'::jsonb, ARRAY['samuel']::text[], '[{"book": "삼상", "from": "4:1", "to": "4:11"}, {"book": "삼상", "from": "5:1", "to": "6:21"}, {"book": "삼상", "from": "7:3", "to": "7:13"}]'::jsonb, -1075, -1075, 'approx', 19, '미스바', 31.83, 35.17, 'published'),
    ('era_monarchy', '096 왕을 요구하다: 우리도 왕을', '백성은 ‘우리도 왕을’ 요구하고, 사무엘은 하나님 앞에서 그 무게를 경고한다.', '["사무엘이 결연한 표정으로 선다", "사무엘이 마음 아파하며 기도한다, 고요한 밤", "사무엘이 왕의 폐해를 설명한다, 사람들의 표정이 굳는다", "백성들이 사무엘에게 그래도 왕을 달라고 말한다"]'::jsonb, '[["samuel"], ["samuel"], ["samuel"], ["samuel"]]'::jsonb, ARRAY['samuel']::text[], '[{"book": "삼상", "from": "8:1", "to": "8:22"}]'::jsonb, -1050, -1050, 'approx', 1, '라마/이스라엘(전승)', 31.92, 35.21, 'published'),
    ('era_monarchy', '097 사울의 기름부음: 숨은 청년', '사울은 예상치 못한 자리에서 기름부음을 받고 첫 왕의 길에 들어선다.', '["젊은 청년 사울이 길에서 나귀를 찾으며 헤맨다", "젊은 사울이 사무엘을 만나 대화하며 놀라는 장면", "사무엘이 젊은 사울에게 기름을 붓는 장면", "젊은 사울이 결연한 표정으로 곧게 선다"]'::jsonb, '[["saul"], ["saul", "samuel"], ["saul", "samuel"], ["saul"]]'::jsonb, ARRAY['saul', 'samuel']::text[], '[{"book": "삼상", "from": "9:1", "to": "10:16"}]'::jsonb, -1050, -1050, 'approx', 2, '라마(전승)', 31.92, 35.21, 'published'),
    ('era_monarchy', '098 사울의 첫 승리: 얍베스 길르앗', '사울은 첫 위기에서 백성을 모아 구원하고 왕권을 굳힌다.', '["위협 소식이 전해진다, 사람들의 얼굴이 창백해진다", "사울이 전령을 보내 이스라엘 병력을 소집하는 장면", "전투 후, 얍베스가 구원받고 환호가 터진다", "길갈에서 사울의 왕권이 확인된다, 사무엘이 축복한다"]'::jsonb, '[[], ["saul"], [], ["saul", "samuel"]]'::jsonb, ARRAY['saul', 'samuel']::text[], '[{"book": "삼상", "from": "11:1", "to": "11:15"}]'::jsonb, -1049, -1049, 'approx', 3, '얍베스 길르앗(전승)', 32.38, 35.56, 'published'),
    ('era_monarchy', '099 사울의 불순종: 왕의 균열', '사울의 조급함과 자기합리화는 왕으로서의 길에 균열을 만든다.', '["전투 전, 사울이 조급해하며 제사를 대신 드린다", "사무엘이 상대를 바라보며 기다린다", "사무엘이 사울을 엄하게 꾸짖는다", "사무엘이 뒤돌아서 떠나자 사울이 옷자락을 붙잡고, 옷자락이 찢어진다"]'::jsonb, '[["saul"], ["samuel"], ["saul", "samuel"], ["saul", "samuel"]]'::jsonb, ARRAY['saul', 'samuel']::text[], '[{"book": "삼상", "from": "13:7", "to": "13:14"}, {"book": "삼상", "from": "15:1", "to": "15:23"}]'::jsonb, -1045, -1045, 'approx', 4, '길갈(전승)', 31.85, 35.45, 'published'),
    ('era_monarchy', '100 다윗의 기름부음: 새로운 선택', '하나님은 사람의 기준이 아닌 마음을 보시고 다윗을 택하신다.', '["사무엘이 어떤 집에 들어가는 장면", "사무엘이 여러 청년들 앞에서 고개를 젓는 모습", "젊은 다윗이 들판에서 양을 치다가 집으로 불려온다", "사무엘이 젊은 다윗에게 기름을 붓는 장면"]'::jsonb, '[["samuel"], ["samuel"], ["david"], ["david", "samuel"]]'::jsonb, ARRAY['david', 'samuel', 'jesse']::text[], '[{"book": "삼상", "from": "16:1", "to": "16:13"}]'::jsonb, -1030, -1030, 'approx', 5, '베들레헴', 31.7, 35.2, 'published'),
    ('era_monarchy', '101 다윗과 골리앗: 돌 하나', '소년 다윗은 믿음으로 거인을 맞서 전세를 뒤집는다.', '["골리앗의 조롱이 울리고 이스라엘 진영이 움츠러든다", "18세쯤의 젊은 다윗이 사울 앞에 결연한 표정으로 서 있다", "18세쯤의 젊은 다윗이 시냇가에서 돌을 집어 들고 물매를 고른다", "돌이 날아가고 골리앗이 쓰러지며 진영의 공기가 바뀐다"]'::jsonb, '[[], ["david", "saul"], ["david"], []]'::jsonb, ARRAY['david', 'goliath', 'saul']::text[], '[{"book": "삼상", "from": "17:32", "to": "17:50"}]'::jsonb, -1025, -1025, 'approx', 6, '엘라 골짜기', 31.69, 34.93, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_monarchy', '102 사울의 시기: 다윗의 도망 시작', '사울의 질투는 다윗을 적으로 만들고 도망의 길을 연다.', '["백성들이 환호하고, 사울의 표정은 굳어지고, 20대 초반의 젊은 다윗은 기쁜 얼굴로 서 있다", "사울이 창을 던지고, 20대 초반의 젊은 다윗이 몸을 피한다", "요나단이 20대 초반의 젊은 다윗과 언약을 맺고 눈물로 작별한다", "20대 초반의 젊은 다윗이 밤길로 사라지고, 뒤에서 군사들의 발소리가 따라온다"]'::jsonb, '[["david", "saul"], ["david", "saul"], ["david", "jonathan"], ["david"]]'::jsonb, ARRAY['david', 'saul', 'jonathan']::text[], '[{"book": "삼상", "from": "18:6", "to": "20:42"}]'::jsonb, -1024, -1015, 'approx', 7, '기브아(사울의 성, 전승)', 31.85, 35.25, 'published'),
    ('era_monarchy', '103 다윗이 사울을 살려주다: 동굴의 순간', '다윗은 복수의 기회를 놓아주며 ‘손대지 않음’으로 자신의 길을 지킨다.', '["다윗 일행이 동굴 안에 몸을 숨기고 긴장한 채 웅크리고 있다", "사울이 다윗 일행이 숨어 있는 동굴 안으로 무심코 들어오는 모습", "다윗이 동굴 안에서 사울의 옷자락만 조용히 자른다", "동굴 안에서 사울이 울며 고개를 숙이고, 다윗은 괜찮다고 손짓하는 장면"]'::jsonb, '[["david"], ["saul"], ["david", "saul"], ["david", "saul"]]'::jsonb, ARRAY['david', 'saul']::text[], '[{"book": "삼상", "from": "24:1", "to": "24:22"}]'::jsonb, -1012, -1012, 'approx', 8, '엔게디(전승)', 31.46, 35.39, 'published'),
    ('era_monarchy', '104 사울의 최후: 엔돌과 길보아', '사울의 두려움은 어두운 선택으로 이어지고 결국 전장에서 끝난다.', '["블레셋 군대를 보고 사울이 떤다, 하늘은 침묵처럼 보인다", "밤, 사울이 엔돌로 향한다, 불안한 발걸음", "예언이 사울을 무너뜨린다, 사울이 바닥에 주저앉는다", "길보아 전투, 사울이 쓰러지고 왕정의 첫 장이 닫힌다"]'::jsonb, '[["saul"], ["saul"], ["saul"], ["saul"]]'::jsonb, ARRAY['saul']::text[], '[{"book": "삼상", "from": "28:5", "to": "28:20"}, {"book": "삼상", "from": "31:1", "to": "31:6"}]'::jsonb, -1010, -1010, 'approx', 9, '길보아 산(전승)', 32.49, 35.38, 'published'),
    ('era_monarchy', '105 다윗 즉위: 한 왕국으로', '다윗은 점진적으로 왕이 되어 마침내 온 이스라엘을 다스린다.', '["사무엘이 다윗에게 기름을 붓는 장면, 사람들의 시선이 모인다", "긴 갈등의 시간, 짧은, 서로 다른 진영이 흔들린다", "장로들이 다윗 앞에 선다", "예루살렘에 들어서는 다윗, 도시의 문이 열리고 새 시작이 열린다"]'::jsonb, '[["david", "samuel"], [], ["david"], ["david"]]'::jsonb, ARRAY['david', 'samuel']::text[], '[{"book": "삼하", "from": "2:1", "to": "2:7"}, {"book": "삼하", "from": "5:1", "to": "5:10"}]'::jsonb, -1005, -1000, 'approx', 10, '헤브론 → 예루살렘(전승)', 31.53, 35.1, 'published'),
    ('era_monarchy', '106 언약궤 입성: 춤과 기쁨', '다윗은 언약궤가 들어올 때 온 마음으로 기뻐하며 예배한다.', '["나팔 소리와 함께 행렬이 예루살렘으로 들어온다", "다윗이 체면보다 기쁨을 택해 춤춘다", "언약궤 앞에서 다윗이 멈추어 고개 숙인다", "다윗이 백성에게 음식을 나누며 축복하고, 도시는 환호로 찬다"]'::jsonb, '[[], ["david"], ["david"], ["david"]]'::jsonb, ARRAY['david']::text[], '[{"book": "삼하", "from": "6:12", "to": "6:19"}]'::jsonb, -1000, -1000, 'approx', 11, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '107 다윗 언약: 집을 세우리라', '하나님은 다윗에게 ‘네 집과 왕위를 견고케 하겠다’는 약속을 주신다.', '["다윗이 결연한 표정으로 선다, 나는 백향목에 거하나, 나단이 듣는다", "밤, 나단이 말씀을 듣고 얼굴이 굳는다, 경외", "다윗과 나단이 엄숙한 표정으로 손짓한다", "다윗이 무릎 꿇고 기도한다, 약속의 무게가 방에 남는다"]'::jsonb, '[["david", "nathan"], ["nathan"], ["david", "nathan"], ["david"]]'::jsonb, ARRAY['david', 'nathan']::text[], '[{"book": "삼하", "from": "7:1", "to": "7:17"}]'::jsonb, -995, -995, 'approx', 12, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '108 밧세바 사건: 나단의 책망', '다윗의 죄가 드러나고, 나단 앞에서 다윗은 회개한다.', '["왕궁의 고요한 밤, 다윗의 시선이 멈춘다, 선택의 순간", "다윗이 궁전 침상 곁에서 밧세바를 부르며 잘못된 욕망의 선택을 시작한다", "나단이 결연한 표정으로 서 있고, 다윗이 분노하다가 멈춘다", "궁전 안에서 다윗이 나단 앞에 엎드려 통곡하는 모습"]'::jsonb, '[["david"], ["david"], ["david", "nathan"], ["david", "nathan"]]'::jsonb, ARRAY['david', 'nathan']::text[], '[{"book": "삼하", "from": "11:1", "to": "12:13"}]'::jsonb, -990, -990, 'approx', 13, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '109 압살롬의 반역: 도망치는 왕', '압살롬의 반역으로 다윗은 예루살렘을 떠나며 눈물로 길을 간다.', '["늙은 왕 다윗의 아들 압살롬이 젊은 청년의 모습으로 사람들의 편을 모으며 반역하는 장면", "사독이라는 레위인이 언약궤를 메어 다윗 앞에 가져다 놓지만, 늙은 왕 다윗이 손을 가로젓는 모습", "늙은 왕 다윗과 일행이 감람산을 울며 오르는 모습", "늙은 왕 다윗이 60대 남자 후새에게 성으로 들어가라고 말하고, 후새가 성으로 들어가는 모습"]'::jsonb, '[[], ["david"], ["david"], ["david"]]'::jsonb, ARRAY['david']::text[], '[{"book": "삼하", "from": "15:1", "to": "15:37"}]'::jsonb, -975, -975, 'approx', 14, '예루살렘 → 요단 동편(전승)', 31.78, 35.22, 'published'),
    ('era_monarchy', '110 인구조사와 제단: 다윗의 선택', '잘못된 자랑이 재앙을 부르고, 다윗은 값을 치르고 제단을 세운다.', '["늙은 왕 다윗이 군사들에게 인구 조사를 명하는 장면", "재앙이 땅을 덮치고, 늙은 왕 다윗이 후회하는 모습", "늙은 왕 다윗이 결연한 표정으로 타작마당을 사들이는 장면", "늙은 왕 다윗이 불이 타오르는 제단 앞에서 기도하며 재앙이 그치는 장면"]'::jsonb, '[["david"], ["david"], ["david"], ["david"]]'::jsonb, ARRAY['david']::text[], '[{"book": "삼하", "from": "24:10", "to": "24:25"}]'::jsonb, -970, -970, 'approx', 15, '예루살렘(아라우나 타작마당, 전승)', 31.78, 35.23, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

commit;
