-- Generated by tools/seed/build_200_stories_seed_sql.py
-- Generated at UTC: 2026-04-29T03:10:51.809477+00:00
-- Target table: events
-- (character_codes / bible_refs / story_scenes / scene_characters live
--  on the events row itself; person_eras and events_ordered are views.)
begin;

-- 시드 INSERT 가 알림 트리거(broadcast)를 깨우는 것 방지. tx 종료 후 자동 복구.
alter table events disable trigger trg_notify_on_new_event;

-- Upsert events from 200 stories
with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_apostolic', '안디옥 교회: 선교의 출발', '안디옥 교회는 금식과 기도 가운데 바울과 바나바를 파송한다.', '["안디옥 교회는 금식하며 함께 기도한다", "성령께서 바울과 바나바를 따로 세우라고 하신다", "공동체는 두 사람에게 안수하며 파송한다", "바울과 바나바는 길을 나서며 선교를 시작한다"]'::jsonb, '[[], ["paul", "barnabas"], ["paul", "barnabas"], ["paul", "barnabas"]]'::jsonb, ARRAY['barnabas', 'paul']::text[], '[{"book": "행", "from": "13:1", "to": "13:3"}]'::jsonb, 46, 46, 'approx', 10, '안디옥(시리아)', 36.202, 36.16, 'published'),
    ('era_monarchy', '언약궤 입성: 춤과 기쁨', '다윗은 언약궤가 들어올 때 온 마음으로 기뻐하며 예배한다.', '["나팔 소리와 함께 행렬이 예루살렘으로 들어온다", "다윗이 체면보다 기쁨을 택해 춤춘다", "언약궤 앞에서 다윗이 멈추어 고개 숙인다", "다윗이 백성에게 음식을 나누며 축복하고, 도시는 환호로 찬다"]'::jsonb, '[[], ["david"], ["david"], ["david"]]'::jsonb, ARRAY['david']::text[], '[{"book": "삼하", "from": "6:12", "to": "6:19"}]'::jsonb, -1000, -1000, 'approx', 10, '예루살렘', 31.78, 35.22, 'published'),
    ('era_exile_return', '에스라의 귀환: 말씀으로 정리하다', '에스라는 말씀의 사람으로 돌아와 공동체를 재정비한다.', '["에스라가 두루마리를 펼쳐 읽는다, 눈빛이 단단하다", "귀환 행렬이 길을 나선다, 먼지 나는 길 위의 결단", "예루살렘에 도착한 에스라가 현실을 보고 고개를 숙인다", "에스라가 율법을 연구하고 행하며 가르치기로 뜻을 정했다가 울린다"]'::jsonb, '[["ezra"], [], ["ezra"], ["ezra"]]'::jsonb, ARRAY['ezra']::text[], '[{"book": "스", "from": "7:1", "to": "7:10"}]'::jsonb, -458, -458, 'approx', 10, '바벨론 → 예루살렘(전승)', 32.55, 44.42, 'published'),
    ('era_patriarch', '이삭 탄생과 하갈 추방', '약속의 아들이 태어나지만 가정의 갈등은 하갈을 광야로 내몬다.', '["사라가 아기 이삭을 안고 환하게 웃는다", "사라의 차가운 눈빛이 앞쪽에 크게 보이고, 뒤편에서는 열 살쯤 된 이스마엘이 어린 이삭을 놀린다", "하갈이 물가죽을 들고 열 살쯤 된 이스마엘과 함께 집을 떠난다", "하갈이 우물 앞에서 열 살쯤 된 이스마엘을 안아 일으켜 세운다"]'::jsonb, '[["sarah", "isaac"], ["sarah", "isaac", "ishmael"], ["hagar", "ishmael"], ["hagar", "ishmael"]]'::jsonb, ARRAY['sarah', 'isaac', 'hagar', 'ishmael']::text[], '[{"book": "창", "from": "21:1", "to": "21:21"}]'::jsonb, -2066, -2066, 'approx', 10, '브엘세바 주변(전승)', 31.25, 34.8, 'published'),
    ('era_nt_apostolic', '1차 선교(1): 구브로 살라미–바보', '바울과 바나바는 구브로에서 복음을 전하며 첫 여정을 시작한다.', '["바울과 바나바는 구브로에 도착해 회당에서 말씀을 전한다", "섬을 지나며 여러 곳에 복음을 전한다", "총독 앞에서 복음이 선포되고 분위기가 바뀐다", "일행은 다음 선교지를 향해 다시 길을 나선다"]'::jsonb, '[["paul", "barnabas", "john_mark"], ["paul", "barnabas", "john_mark"], ["paul", "barnabas"], ["paul", "barnabas", "john_mark"]]'::jsonb, ARRAY['paul', 'barnabas', 'john_mark']::text[], '[{"book": "행", "from": "13:4", "to": "13:12"}]'::jsonb, 46, 46, 'approx', 11, '구브로(살라미 → 바보)', 34.775, 32.424, 'published'),
    ('era_exile_return', '느헤미야의 파송: 무너진 성벽 소식', '느헤미야는 예루살렘 소식을 듣고 눈물로 기도한 뒤 파송을 받는다.', '["느헤미야가 소식을 듣고 무너진 얼굴로 앉아 운다", "느헤미야가 밤의 기도, 주의 이름을 경외하는 종들을 기억하소서", "상대를 바라보며 기다린다, 느헤미야가 숨을 고른다", "왕의 허락과 편지가 주어진다, 느헤미야가 고개 숙여 감사한다"]'::jsonb, '[["nehemiah"], ["nehemiah"], ["nehemiah"], ["nehemiah"]]'::jsonb, ARRAY['nehemiah']::text[], '[{"book": "느", "from": "1:1", "to": "1:11"}, {"book": "느", "from": "2:1", "to": "2:8"}]'::jsonb, -445, -445, 'approx', 11, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_monarchy', '다윗 언약: 집을 세우리라', '하나님은 다윗에게 ‘네 집과 왕위를 견고케 하겠다’는 약속을 주신다.', '["다윗이 결연한 표정으로 선다, 나는 백향목에 거하나, 나단이 듣고 끄덕인다", "밤, 나단이 말씀을 듣고 얼굴이 굳는다, 경외", "다윗과 나단이 엄숙한 표정으로 손짓한다", "다윗이 무릎 꿇고 기도한다, 약속의 무게가 방에 남는다"]'::jsonb, '[["david", "nathan"], ["nathan"], ["david", "nathan"], ["david"]]'::jsonb, ARRAY['david', 'nathan']::text[], '[{"book": "삼하", "from": "7:1", "to": "7:17"}]'::jsonb, -995, -995, 'approx', 11, '예루살렘', 31.78, 35.22, 'published'),
    ('era_exodus', '만나와 메추라기: 하늘의 양식', '먹을 것이 없던 광야에서 하나님은 매일의 양식을 주시며 ‘신뢰’를 훈련하신다.', '["백성이 불평한다, 애굽의 냄비가 그립다", "아침, 땅 위에 하얀 것들이 덮인다, 이것이 무엇이냐?", "모세가 결연한 표정으로 선다", "집 안에 쌓아 둔 만나가 벌레가 생기고 냄새가 나며 썩어 간다, 사람들이 놀라 뒤로 물러선다"]'::jsonb, '[[], [], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "16:1", "to": "16:36"}]'::jsonb, -1446, -1446, 'approx', 11, '신 광야(전승)', 28.9, 33.3, 'published'),
    ('era_nt_public_ministry', '산상수훈(3): 먼저 하나님 나라를 구하라', '예수님은 기도와 염려, 좁은 문과 반석 위의 삶으로 제자의 길을 가르치신다.', '["예수는 구제와 기도를 은밀히 하라고 가르치신다", "예수는 주기도문을 가르치신다", "예수는 염려하지 말고 먼저 하나님 나라를 구하라고 하신다", "예수는 좁은 문과 반석 위의 삶을 말씀하신다"]'::jsonb, '[["jesus"], ["jesus"], ["jesus"], ["jesus"]]'::jsonb, ARRAY[]::text[], '[{"book": "마", "from": "6:1", "to": "7:29"}]'::jsonb, 28, 28, 'approx', 11, '갈릴리 산지(전승)', 32.85, 35.55, 'published'),
    ('era_judges', '언약궤 사건: 회개와 승리', '언약궤의 아픔 이후, 백성은 회개하고 하나님은 구원을 보여주신다.', '["전투에서 언약궤를 들고 나가지만 패배한다", "사무엘이 두 손을 들어 다급하게 몸짓한다", "블레셋이 올라오지만, 하나님이 도우시고 백성이 승리한다"]'::jsonb, '[[], ["samuel"], []]'::jsonb, ARRAY['samuel']::text[], '[{"book": "삼상", "from": "4:1", "to": "4:11"}, {"book": "삼상", "from": "5:1", "to": "6:21"}, {"book": "삼상", "from": "7:3", "to": "7:13"}]'::jsonb, -1075, -1075, 'approx', 11, '미스바', 31.83, 35.17, 'published'),
    ('era_patriarch', '이삭 번제: 멈추게 하시는 하나님', '극한의 시험 속에서 하나님은 아브라함을 멈추게 하시고 대안을 준비하신다.', '["새벽, 아브라함이 나무를 챙기고 서른 살 남짓한 젊은 이삭이 곁에서 함께 길을 나선다", "제단 위에 누운 서른 살 남짓한 젊은 이삭 곁에서 아브라함의 손이 떨린다", "아브라함이 풀숲 뒤의 숫양을 보고 서른 살 남짓한 젊은 이삭을 풀어준다"]'::jsonb, '[["abraham", "isaac"], ["abraham", "isaac"], ["abraham", "isaac", "god"]]'::jsonb, ARRAY['abraham', 'isaac', 'god']::text[], '[{"book": "창", "from": "22:1", "to": "22:18"}]'::jsonb, -2055, -2055, 'approx', 11, '모리아(예루살렘, 전승)', 31.78, 35.22, 'published'),
    ('era_nt_apostolic', '1차 선교(2): 비시디아 안디옥', '바울은 회당에서 설교하고, 복음은 이방인에게 크게 확장된다.', '["회당에 모인 사람들이 바울의 말을 듣는다", "바울은 예수를 통한 구원을 길게 전한다", "이방인들은 기뻐하지만 반대도 함께 커진다", "바울과 바나바는 다음 도시로 떠난다"]'::jsonb, '[["paul", "barnabas"], ["paul"], ["paul", "barnabas"], ["paul", "barnabas"]]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "13:13", "to": "13:52"}]'::jsonb, 46, 46, 'approx', 12, '비시디아 안디옥(소아시아)', 38.35, 31.18, 'published'),
    ('era_patriarch', '사라의 죽음과 막벨라 굴', '아브라함은 약속의 땅에서 첫 소유지로 묘지를 산다.', '["사라의 죽음 앞에서 아브라함이 조용히 울며 고개를 숙인다", "성문 앞에서 아브라함이 예의를 지키며 매장지를 요청한다", "아브라함이 은을 세어 땅값을 직접 지불한다", "막벨라 굴에 장사한 뒤 아브라함이 오래 서 있다"]'::jsonb, '[["abraham", "sarah"], ["abraham"], ["abraham"], ["abraham"]]'::jsonb, ARRAY['abraham', 'sarah']::text[], '[{"book": "창", "from": "23:1", "to": "23:20"}]'::jsonb, -2030, -2030, 'approx', 12, '헤브론(막벨라, 전승)', 31.53, 35.1, 'published'),
    ('era_exile_return', '성벽 재건: 밤의 조사와 한 손엔 무기', '느헤미야는 밤에 성벽을 살핀 뒤 재건을 이끌었고, 백성은 한 손에 돌 한 손에 무기를 들고 성을 세웠다.', '["밤, 느헤미야가 소수와 함께 성벽을 따라 조사한다", "성벽을 재건하는 건축 현장", "건축 현장에서 한 손엔 돌, 한 손엔 무기를 들고 성벽을 세우는 모습", "나팔 소리에 사람들이 모이고, 하나님이 싸우신다는 외침에 모두가 고개를 드는 장면"]'::jsonb, '[["nehemiah"], ["nehemiah"], ["nehemiah"], ["nehemiah"]]'::jsonb, ARRAY['nehemiah']::text[], '[{"book": "느", "from": "2:11", "to": "2:20"}, {"book": "느", "from": "4:10", "to": "4:20"}]'::jsonb, -445, -445, 'approx', 12, '예루살렘', 31.78, 35.22, 'published'),
    ('era_exodus', '아말렉 전투: 팔이 내려갈 때', '전투의 승패는 숫자가 아니라 ‘붙드는 손’에서 드러난다.', '["여호수아가 병력을 정리하고 달려나간다", "언덕 위 모세가 손을 들자 이스라엘이 밀어붙인다", "아론과 훌이 양쪽에서 받친다", "해 질 무렵 승리, 모세가 결연한 표정으로 선다"]'::jsonb, '[["joshua"], ["moses"], ["moses", "aaron"], ["moses"]]'::jsonb, ARRAY['moses', 'joshua', 'aaron']::text[], '[{"book": "출", "from": "17:8", "to": "17:16"}]'::jsonb, -1446, -1446, 'approx', 12, '르비딤(전승)', 28.75, 33.35, 'published'),
    ('era_monarchy', '인구조사와 제단: 다윗의 선택', '잘못된 자랑이 재앙을 부르고, 다윗은 값을 치르고 제단을 세운다.', '["늙은 왕 다윗이 군사들에게 인구 조사를 명하는 장면", "재앙이 땅을 덮치고, 늙은 왕 다윗이 후회하는 모습", "늙은 왕 다윗이 결연한 표정으로 타작마당을 사들이는 장면", "늙은 왕 다윗이 불이 타오르는 제단 앞에서 기도하며 재앙이 그치는 장면"]'::jsonb, '[["david"], ["david"], ["david"], ["david"]]'::jsonb, ARRAY['david']::text[], '[{"book": "삼하", "from": "24:10", "to": "24:25"}]'::jsonb, -970, -970, 'approx', 12, '예루살렘(아라우나 타작마당, 전승)', 31.78, 35.23, 'published'),
    ('era_nt_public_ministry', '폭풍을 잠잠케 하심', '두려움 속 제자들 앞에서 예수님은 바람과 물결을 잠잠케 하신다.', '["배 위, 폭풍이 몰아치고 제자들이 물을 퍼낸다", "제자들이 두 손을 들어 다급하게 몸짓한다", "예수님이 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "제자들이 서로를 바라본다, 두려움과 놀람이 엇갈린다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "4:35", "to": "4:41"}, {"book": "마", "from": "8:23", "to": "8:27"}, {"book": "눅", "from": "8:22", "to": "8:25"}]'::jsonb, 28, 28, 'approx', 12, '갈릴리 호수', 32.83, 35.59, 'published'),
    ('era_nt_apostolic', '1차 선교(3): 이고니온', '표적과 논쟁이 함께 일어나고, 박해의 조짐이 짙어진다.', '["바울과 바나바는 이고니온 회당에서 복음을 전한다", "많은 사람이 믿지만 반대도 빠르게 커진다", "도시는 둘로 갈리고 긴장이 높아진다", "두 사람은 박해를 피해 다른 곳으로 옮긴다"]'::jsonb, '[["paul", "barnabas"], ["paul", "barnabas"], ["paul", "barnabas"], ["paul", "barnabas"]]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:1", "to": "14:7"}]'::jsonb, 47, 47, 'approx', 13, '이고니온(코니아)', 37.874, 32.493, 'published'),
    ('era_patriarch', '리브가: 이삭의 결혼', '기도와 만남을 통해 리브가가 이삭의 아내로 선택된다.', '["우물가에서 리브가가 물을 길어 낙타들에게까지 먹인다", "늙은 종과 낙타들, 리브가가 함께 리브가의 집으로 들어간다", "사십 대쯤의 젊은 이삭이 들판에서 리브가를 처음 맞이한다"]'::jsonb, '[["rebekah"], ["rebekah"], ["isaac", "rebekah"]]'::jsonb, ARRAY['isaac', 'rebekah']::text[], '[{"book": "창", "from": "24:1", "to": "24:67"}]'::jsonb, -2026, -2026, 'approx', 13, '하란 주변(전승)', 36.87, 39.03, 'published'),
    ('era_monarchy', '솔로몬 즉위: 지혜의 선택', '솔로몬은 왕으로 세워지고 ‘지혜’를 구해 길을 연다.', '["다윗의 마지막 지시를 솔로몬이 긴장한 얼굴로 듣는다", "솔로몬의 즉위 장면, 군중의 환호가 터진다", "밤의 꿈속에 하나님이 솔로몬에게 나타나시는 장면", "솔로몬이 언약궤 앞에 서서 번제와 감사의 제물을 드리고 신하들은 기쁜 표정을 짓는다"]'::jsonb, '[["solomon", "david"], ["solomon"], ["solomon", "god"], ["solomon"]]'::jsonb, ARRAY['solomon', 'david', 'god']::text[], '[{"book": "왕상", "from": "1:28", "to": "3:15"}]'::jsonb, -970, -967, 'approx', 13, '예루살렘', 31.78, 35.22, 'published'),
    ('era_exodus', '시내산 도착: 십계명과 하나님 기준', '하나님은 구원받은 백성에게 살아갈 길을 선포하신다.', '["하나님의 빛이 산 위에서 음성이 울린다", "모세가 고개를 끄덕인다", "모세가 어두운 구름 속으로 들어간다, 결단의 뒷모습"]'::jsonb, '[["god"], ["moses"], ["moses"]]'::jsonb, ARRAY['moses', 'god']::text[], '[{"book": "출", "from": "20:1", "to": "31:18"}]'::jsonb, -1446, -1446, 'approx', 13, '시내산(전승)', 28.54, 33.98, 'published'),
    ('era_nt_public_ministry', '야이로의 딸과 혈루증 여인', '절박한 믿음이 이어지는 길 위에서 예수님은 치유와 생명의 능력을 보이신다.', '["야이로가 무릎 꿇고 간청한다", "군중 속 여인이 예수의 옷자락을 만지고 멈춘다", "예수 앞쪽에 서 있고, 여인이 울며 고개 숙인다", "집에 도착해 달리다굼이 울리고, 아이가 일어나는 순간 모두가 숨을 삼킨다"]'::jsonb, '[[], ["jesus"], ["jesus"], []]'::jsonb, ARRAY['jesus', 'jairus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "5:21", "to": "5:43"}, {"book": "마", "from": "9:18", "to": "9:26"}, {"book": "눅", "from": "8:40", "to": "8:56"}]'::jsonb, 28, 28, 'approx', 13, '가버나움(전승)', 32.88, 35.57, 'published'),
    ('era_exile_return', '율법 낭독: 울음에서 기쁨으로', '말씀이 낭독되자 백성은 울고, 지도자들은 ‘기쁨이 힘’이라 격려한다.', '["에스라가 군중들에게 두루마리를 선포하는 장면", "느헤미야가 울지 말라고 백성들을 다독이는 장면", "에스라와 느헤미야와 백성들이 음식을 나누며 기뻐하는 장면"]'::jsonb, '[["ezra"], ["nehemiah"], ["ezra", "nehemiah"]]'::jsonb, ARRAY['ezra', 'nehemiah']::text[], '[{"book": "느", "from": "8:1", "to": "8:12"}]'::jsonb, -444, -444, 'approx', 13, '예루살렘 수문 앞 광장(전승)', 31.78, 35.23, 'published'),
    ('era_nt_apostolic', '1차 선교(4): 루스드라–더베', '루스드라와 더베에서 전도가 이어지지만, 폭력적 박해도 뒤따른다.', '["루스드라에서 걷지 못하던 사람이 바울의 말을 듣고 일어나자 무리가 크게 술렁인다", "사람들은 바울과 바나바를 신들로 여기며 제사를 드리려 하고, 두 사람은 급히 이를 말린다", "바울은 심한 박해를 겪고도 다시 일어선다", "일행은 더베로 가서 복음을 이어 전한다"]'::jsonb, '[["paul", "barnabas"], ["paul", "barnabas"], ["paul"], ["paul", "barnabas"]]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:8", "to": "14:20"}]'::jsonb, 47, 47, 'approx', 14, '루스드라 → 더베(갈라디아)', 37.58, 32.28, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_exodus', '금송아지: 아래에서 벌어진 일', '기다림을 견디지 못한 백성은 우상을 만들고 언약을 깨뜨린다.', '["백성이 아론을 둘러싼다", "금이 모이고 송아지 형상이 세워진다, 환호가 터진다", "산에서 내려오는 모세, 소리를 듣고 표정이 굳는다", "모세가 돌판을 던져 깨뜨린다, 진영이 얼어붙는다"]'::jsonb, '[["aaron"], [], ["moses"], ["moses"]]'::jsonb, ARRAY['moses', 'aaron']::text[], '[{"book": "출", "from": "32:1", "to": "32:35"}]'::jsonb, -1446, -1446, 'approx', 14, '시내산 진(전승)', 28.54, 33.98, 'published'),
    ('era_monarchy', '성전 건축: 손으로 짓는 집', '솔로몬은 오랜 준비 끝에 성전을 건축한다.', '["목재와 돌이 모인다, 일꾼들의 발걸음이 분주하다", "돌을 다듬는 소리, 조용히 올라가는 구조", "마지막 기둥이 세워지고, 성전이 완성된다. 솔로몬이 기뻐한다"]'::jsonb, '[[], [], ["solomon"]]'::jsonb, ARRAY['solomon']::text[], '[{"book": "왕상", "from": "5:1", "to": "6:38"}]'::jsonb, -966, -959, 'approx', 14, '예루살렘 성전 터(전승)', 31.78, 35.23, 'published'),
    ('era_nt_public_ministry', '오병이어', '작은 나눔이 시작점이 되어 많은 사람이 먹고 남는다.', '["저녁이 가까워지자 제자들이 많은 무리의 먹을 것을 걱정한다", "한 아이가 떡 다섯 개와 물고기 두 마리를 내놓지만, 모두에게는 턱없이 적어 보인다", "예수는 무리를 앉게 하시고 떡과 물고기를 축사한 뒤 제자들을 통해 나누어 주신다", "모든 사람이 배불리 먹고도 열두 바구니가 남자, 제자들이 놀란다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "6:34", "to": "6:44"}, {"book": "마", "from": "14:13", "to": "14:21"}, {"book": "눅", "from": "9:10", "to": "9:17"}, {"book": "요", "from": "6:1", "to": "6:13"}]'::jsonb, 29, 29, 'approx', 14, '갈릴리 호숫가 들판(전승)', 32.84, 35.54, 'published'),
    ('era_patriarch', '장자권: 한 그릇의 거래', '에서는 배고픔에 장자의 권리를 가볍게 팔고 야곱은 그것을 붙잡는다.', '["사냥에서 돌아온 에서가 지친 몸으로 장막으로 들어온다", "붉은 죽 냄새 앞에서 에서가 허기를 참지 못하고 야곱을 바라본다", "야곱이 장자권을 요구하고 에서가 망설인다", "에서가 허겁지겁 먹고, 뒤편에서는 야곱이 그 모습을 지켜본다"]'::jsonb, '[["esau"], ["esau", "jacob"], ["esau", "jacob"], ["esau", "jacob"]]'::jsonb, ARRAY['esau', 'jacob']::text[], '[{"book": "창", "from": "25:19", "to": "25:34"}]'::jsonb, -2006, -2006, 'approx', 14, '브엘세바 일대(전승)', 31.25, 34.8, 'published'),
    ('era_nt_apostolic', '1차 선교(5): 안디옥(시리아)로 귀환 보고', '1차 여행을 마치고 돌아와 하나님이 하신 일을 교회에 보고한다.', '["바울과 바나바는 안디옥 교회로 돌아온다", "교회가 모이고 두 사람은 선교 이야기를 전한다", "이방인에게 믿음의 문이 열렸다는 소식이 퍼진다", "공동체는 하나님이 하신 일을 함께 기뻐한다"]'::jsonb, '[["paul", "barnabas"], ["paul", "barnabas"], ["paul", "barnabas"], []]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:21", "to": "14:28"}]'::jsonb, 48, 48, 'approx', 15, '안디옥(시리아)', 36.202, 36.16, 'published'),
    ('era_exodus', '모세의 중보: 다시 시작', '모세는 백성을 위해 중보하고 하나님은 관계 회복의 길을 여신다.', '["모세가 장막 밖에서 기도한다, 얼굴에 간절함", "하나님의 빛이 임한다", "새 돌판을 들고 내려오는 모세, 관계의 재출발"]'::jsonb, '[["moses"], ["god"], ["moses"]]'::jsonb, ARRAY['moses', 'god']::text[], '[{"book": "출", "from": "33:7", "to": "34:10"}]'::jsonb, -1446, -1446, 'approx', 15, '시내산(전승)', 28.54, 33.98, 'published'),
    ('era_nt_public_ministry', '변화산', '예수님의 영광이 드러나고 제자들은 ‘그의 말을 들으라’는 음성을 듣는다.', '["예수와 세 제자가 산을 오르며 숨을 고른다", "예수의 모습이 빛나고, 모세와 엘리야가 함께 선다", "베드로가 결연한 표정으로 선다", "하늘에서 빛이 비치고, 제자들이 엎드린다"]'::jsonb, '[["jesus"], ["moses", "elijah", "jesus"], ["peter"], []]'::jsonb, ARRAY['jesus', 'peter', 'james', 'john', 'moses', 'elijah']::text[], '[{"book": "막", "from": "9:2", "to": "9:13"}, {"book": "마", "from": "17:1", "to": "17:13"}, {"book": "눅", "from": "9:28", "to": "9:36"}]'::jsonb, 29, 29, 'approx', 15, '변화산(전승, 다볼/헤르몬 견해)', 33.417, 35.857, 'published'),
    ('era_monarchy', '솔로몬: 이방의 경탄부터 타락까지', '솔로몬의 지혜와 영화는 이방을 놀라게 했지만, 말년의 타락은 왕국의 균열을 예고했다.', '["낙타 행렬이 도착한다, 이국적 선물들이 펼쳐진다", "스바 여왕이 수수께끼를 던지고, 솔로몬이 조용히 대답한다", "솔로몬이 이방 여인들을 들여오며 마음이 흐려지는 장면", "늙은 솔로몬이 생을 마치고 궁정이 조용해지는 장면"]'::jsonb, '[[], ["solomon"], ["solomon"], ["solomon"]]'::jsonb, ARRAY['solomon']::text[], '[{"book": "왕상", "from": "10:1", "to": "11:43"}]'::jsonb, -950, -950, 'approx', 15, '예루살렘', 31.78, 35.22, 'published'),
    ('era_patriarch', '축복 가로채기: 속임수의 밤', '야곱은 속임수로 이삭의 축복을 받고 도망길에 오른다.', '["늙은 리브가가 급히 계획을 말하고 야곱이 망설인다", "야곱이 염소 가죽을 두르고 늙은 이삭 앞에 선다, 숨죽인 긴장", "에서가 이삭 앞에서 기도해 달라고 간청하지만, 이삭은 더 줄 축복이 없다는 듯 고개를 떨군다", "에서가 돌아와 울부짖고, 야곱은 짐을 챙겨 도망친다"]'::jsonb, '[["jacob", "rebekah"], ["jacob", "isaac"], ["esau", "isaac"], ["jacob", "esau"]]'::jsonb, ARRAY['jacob', 'esau', 'isaac', 'rebekah']::text[], '[{"book": "창", "from": "27:1", "to": "27:45"}]'::jsonb, -1985, -1985, 'approx', 15, '브엘세바 일대(전승)', 31.25, 34.8, 'published'),
    ('era_nt_apostolic', '2차 선교(1): 드로아에서 마게도냐로', '드로아에서 ‘마게도냐로 건너오라’는 인도를 받고 방향이 바뀐다.', '["바울 일행은 드로아에서 다음 길을 기다린다", "밤에 바울은 마게도냐로 오라는 환상을 본다", "일행은 그 인도를 따라 방향을 정한다", "배는 바다를 건너 새로운 땅으로 향한다"]'::jsonb, '[["paul", "silas", "timothy"], ["paul"], ["paul", "silas", "timothy"], ["paul", "silas", "timothy"]]'::jsonb, ARRAY['paul', 'silas', 'timothy']::text[], '[{"book": "행", "from": "16:6", "to": "16:10"}]'::jsonb, 49, 49, 'approx', 16, '드로아', 39.812, 26.173, 'published'),
    ('era_exodus', '놋뱀: 바라보라', '원망 속에서 고통이 번지지만, 하나님은 ‘바라봄’으로 살 길을 주신다.', '["백성이 모세를 둘러싸고 원망을 쏟아낸다, 왜 우리를 이 광야로 데려왔느냐", "불뱀들이 진영에 나타나 백성을 물어 사람들이 공포에 빠진다, 피나 상처는 직접 보이지 않음", "모세가 장대를 세우고 표징을 올린다", "사람들이 고개를 들어 바라본다, 얼굴이 서서히 안정된다"]'::jsonb, '[[], [], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "민", "from": "21:4", "to": "21:9"}]'::jsonb, -1408, -1408, 'approx', 16, '광야(에돔 길, 전승)', 30, 35.5, 'published'),
    ('era_nt_public_ministry', '베드로의 고백과 수난 예고', '베드로의 고백 이후 예수님은 십자가의 길을 처음으로 분명히 예고하신다.', '["길을 가던 예수와 제자들이 멈추고, 예수는 사람들이 자신을 누구라 하는지 물으신다", "베드로가 앞으로 나서서 예수는 그리스도라고 고백한다", "예수는 자신이 고난을 받고 죽임당한 뒤 다시 살아날 것을 처음으로 밝히신다", "베드로가 만류하자 예수는 제자들 앞에서 그의 생각을 바로잡으시고, 모두가 충격에 잠긴다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter"], ["jesus", "peter"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "8:27", "to": "8:33"}, {"book": "마", "from": "16:13", "to": "16:23"}, {"book": "눅", "from": "9:18", "to": "9:22"}]'::jsonb, 29, 29, 'approx', 16, '가이사랴 빌립보', 33.248, 35.694, 'published'),
    ('era_patriarch', '벧엘의 꿈: 사다리와 약속', '도망자 야곱은 길 위에서 ‘함께하심’의 약속을 받는다.', '["야곱이 돌을 베고 누운다, 밤바람 소리만 들린다", "하나님의 빛이 임한다", "야곱이 돌기둥을 세우고 기름을 붓는다, 여기가 하나님의 집이다"]'::jsonb, '[["jacob"], ["god"], ["jacob", "god"]]'::jsonb, ARRAY['jacob', 'god']::text[], '[{"book": "창", "from": "28:10", "to": "28:22"}]'::jsonb, -1985, -1985, 'approx', 16, '벧엘(전승)', 31.93, 35.22, 'published'),
    ('era_monarchy', '엘리야와 갈멜: 불의 응답', '엘리야는 하나님이 참 하나님이심을 불의 응답으로 드러낸다.', '["바알 선지자들의 소란, 사람들의 얼굴이 흔들린다", "엘리야가 제단에 물을 붓고 조용히 기도한다", "불이 임하고 백성이 엎드린다, 여호와 그가 하나님이시로다!"]'::jsonb, '[[], ["elijah"], ["elijah"]]'::jsonb, ARRAY['elijah']::text[], '[{"book": "왕상", "from": "18:20", "to": "18:39"}]'::jsonb, -860, -860, 'approx', 16, '갈멜 산', 32.83, 34.97, 'published'),
    ('era_nt_apostolic', '2차 선교(2): 빌립보—루디아와 감옥의 찬양', '빌립보에서 복음은 가정과 감옥 한복판까지 스며든다.', '["강가에서 루디아가 복음을 듣고 마음을 연다", "바울과 실라는 감옥에 갇히지만 밤중에도 찬양한다", "큰 흔들림 속에 옥문이 열리고 간수는 두려워한다", "간수의 집은 말씀을 듣고 하나님을 믿게 되며 기쁨으로 가득해진다"]'::jsonb, '[["paul", "silas", "timothy", "lydia"], ["paul", "silas"], ["paul", "silas"], ["paul", "silas", "lydia"]]'::jsonb, ARRAY['paul', 'silas', 'timothy', 'lydia']::text[], '[{"book": "행", "from": "16:11", "to": "16:34"}]'::jsonb, 50, 50, 'approx', 17, '빌립보', 41.012, 24.286, 'published'),
    ('era_patriarch', '라반의 집: 레아와 라헬', '야곱은 라헬을 사랑하지만 속임수로 레아와도 결혼하게 된다.', '["우물가에서 라헬을 처음 본 야곱이 큰 돌을 옮긴다", "라반이 야곱과 계약을 맺고, 라반은 야곱보다 훨씬 늙어 보인다", "혼인 밤, 얼굴을 가린 신부를 두고 아침에 레아임을 알아차린 야곱이 충격을 받는다", "야곱이 다시 7년을 약속하고 라헬을 맞는다"]'::jsonb, '[["jacob", "rachel"], ["laban", "jacob"], ["jacob", "leah"], ["jacob", "rachel"]]'::jsonb, ARRAY['jacob', 'laban', 'leah', 'rachel']::text[], '[{"book": "창", "from": "29:1", "to": "29:30"}]'::jsonb, -1984, -1977, 'approx', 17, '하란(전승)', 36.87, 39.03, 'published'),
    ('era_nt_public_ministry', '비유: 선한 사마리아인', '예수님은 선한 사마리아인 비유로 참된 이웃 사랑이 무엇인지 가르치신다.', '["율법교사가 예수께 다가와 내 이웃이 누구인지 묻는다", "길가에 쓰러진 사람, 제사장과 레위인이 지나친다", "사마리아인이 멈추어 상처를 싸매고 짐승에 태운다", "예수는 누가 이웃이 되었는지 되묻고, 율법교사는 자비를 베푼 사람이라고 답한다"]'::jsonb, '[[], [], [], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "눅", "from": "10:25", "to": "10:37"}]'::jsonb, 30, 30, 'approx', 17, '예루살렘-여리고 길(전승)', 31.8, 35.4, 'published'),
    ('era_monarchy', '호렙의 엘리야: 조용한 음성', '엘리야는 절망 속에서 ‘세미한 음성’으로 다시 부르심을 받는다.', '["엘리야가 광야에 쓰러진다, 차라리 죽여 주옵소서", "천사의 돌봄, 빵과 물, 엘리야가 다시 일어난다", "엘리야 앞에서 큰 바람과 지진과 불이 지나가고, 그 뒤에 고요가 온다"]'::jsonb, '[["elijah"], ["elijah"], ["elijah"]]'::jsonb, ARRAY['elijah']::text[], '[{"book": "왕상", "from": "19:1", "to": "19:18"}]'::jsonb, -860, -860, 'approx', 17, '호렙 산(전승)', 28.54, 33.98, 'published'),
    ('era_nt_apostolic', '2차 선교(3): 데살로니가—소동과 도피', '데살로니가에서 복음이 퍼지자 반대가 폭동으로 번진다.', '["바울 일행은 회당에서 복음을 전한다", "몇 사람은 믿지만 반대의 목소리도 커진다", "도시에는 소동이 일어나고 긴장이 번진다", "형제들은 밤에 바울 일행을 급히 피신시킨다"]'::jsonb, '[["paul", "silas", "timothy"], ["paul", "silas", "timothy"], ["paul", "silas", "timothy"], ["paul", "silas", "timothy"]]'::jsonb, ARRAY['paul', 'silas', 'timothy']::text[], '[{"book": "행", "from": "17:1", "to": "17:9"}]'::jsonb, 50, 50, 'approx', 18, '데살로니가', 40.64, 22.944, 'published'),
    ('era_nt_public_ministry', '비유: 탕자의 귀환', '잃은 아들을 맞이하는 아버지의 품이 하나님 나라의 심장을 드러낸다.', '["작은아들이 아버지에게 유산을 요구한 뒤 집을 떠나 먼 나라로 간다", "재산을 다 써버린 아들은 굶주림 속에 돼지우리에서 비참한 처지를 깨닫는다", "집으로 돌아오는 아들을 본 아버지는 먼저 달려가 끌어안고 잔치를 준비한다", "큰아들은 돌아온 동생을 위한 잔치에 마음이 상하지만, 아버지는 함께 기뻐하자고 권한다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['jesus']::text[], '[{"book": "눅", "from": "15:11", "to": "15:32"}]'::jsonb, 30, 30, 'approx', 18, '베레아(요단 동편, 추정)', 31.93, 35.62, 'published'),
    ('era_monarchy', '엘리야 승천: 겉옷의 계승', '엘리야는 떠나고, 엘리사는 겉옷과 사명을 이어받는다.', '["늙은 흰머리 노인 엘리야가 엘리사에게 마지막 길을 함께 가자고 말하는 장면", "늙은 노인 엘리야가 겉옷으로 요단강 물을 치자 길이 열리는 장면", "늙은 노인 엘리야가 불수레와 함께 하늘로 들려 올라가고, 엘리사가 울부짖는 장면", "엘리사가 겉옷을 들고 요단을 치자 물이 갈라지는 장면"]'::jsonb, '[["elijah", "elisha"], ["elijah"], ["elijah", "elisha"], ["elisha"]]'::jsonb, ARRAY['elijah', 'elisha']::text[], '[{"book": "왕하", "from": "2:1", "to": "2:14"}]'::jsonb, -850, -850, 'approx', 18, '요단강 근처(전승)', 31.85, 35.55, 'published'),
    ('era_patriarch', '열두 아들의 시작: 이름에 담긴 마음', '경쟁과 상처 속에서도 열두 지파의 뿌리가 형성된다.', '["레아가 결연한 표정으로 선다", "라헬이 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "아이들이 늘어나고 장막 사이 경쟁이 깊어진다", "마지막에 라헬이 요셉을 낳고 안도의 숨을 쉰다"]'::jsonb, '[["leah"], ["rachel"], [], ["rachel"]]'::jsonb, ARRAY['jacob', 'leah', 'rachel']::text[], '[{"book": "창", "from": "29:31", "to": "30:24"}]'::jsonb, -1977, -1965, 'approx', 18, '하란(전승)', 36.87, 39.03, 'published'),
    ('era_nt_apostolic', '2차 선교(4): 베뢰아—말씀을 상고하다', '베뢰아 사람들은 말씀을 상고하며 복음을 받아들인다.', '["베뢰아 사람들은 열린 마음으로 말씀을 듣는다", "그들은 두루마리를 펴고 날마다 확인한다", "많은 이가 믿지만 방해도 다시 따라온다", "바울은 떠나고 실라와 디모데는 남아 돕는다"]'::jsonb, '[["paul", "silas", "timothy"], ["paul", "silas", "timothy"], ["paul", "silas", "timothy"], ["paul", "silas", "timothy"]]'::jsonb, ARRAY['paul', 'silas', 'timothy']::text[], '[{"book": "행", "from": "17:10", "to": "17:15"}]'::jsonb, 50, 50, 'approx', 19, '베뢰아', 40.523, 22.203, 'published'),
    ('era_nt_public_ministry', '나사로의 부활', '예수님은 ‘나는 부활이요 생명’이라 하시며 나사로를 일으키신다.', '["베다니에 슬픔이 가득하고, 마르다와 마리아 곁에 사람들이 모여 있다", "마르다가 예수를 맞으며 조용히 말을 건넨다", "예수는 무덤 앞에 서서 돌을 옮기게 하신다", "예수의 부르심에 나사로가 나오고, 사람들은 놀란다"]'::jsonb, '[["martha", "mary"], ["jesus", "martha"], ["jesus"], ["jesus", "lazarus"]]'::jsonb, ARRAY['jesus', 'lazarus', 'martha', 'mary']::text[], '[{"book": "요", "from": "11:1", "to": "11:44"}]'::jsonb, 32, 32, 'approx', 19, '베다니', 31.774, 35.263, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_monarchy', '나아만: 요단의 일곱 번', '자존심을 내려놓을 때 치유가 찾아온다.', '["문둥병에 걸린 젊은 장수 나아만이 이스라엘로 향하는 장면", "작은 종이 젊은 장수 나아만에게 말하고, 나아만은 화를 내는 장면", "젊은 장수 나아만이 분한 얼굴로 요단강 물에 몸을 담그는 장면", "젊은 장수 나아만의 문둥병이 깨끗이 나은 장면"]'::jsonb, '[["naaman"], ["naaman"], ["naaman"], ["naaman"]]'::jsonb, ARRAY['naaman', 'elisha']::text[], '[{"book": "왕하", "from": "5:1", "to": "5:14"}]'::jsonb, -845, -845, 'approx', 19, '사마리아/요단강(전승)', 32.46, 35.55, 'published'),
    ('era_patriarch', '야곱의 번성: 양떼의 기묘한 계약', '야곱은 라반의 집에서 번성하고 라반과 갈등이 깊어진다.', '["야곱이 떠나겠다고 말하자 라반이 붙잡는다", "양떼 계약이 정해지고, 야곱이 표식을 구분한다", "야곱의 떼가 늘어나며 라반의 얼굴이 굳는다", "야곱이 가족에게 속삭인다, 이제 떠나야 한다"]'::jsonb, '[["jacob", "laban"], ["jacob"], ["jacob", "laban"], ["jacob"]]'::jsonb, ARRAY['jacob', 'laban']::text[], '[{"book": "창", "from": "30:25", "to": "31:16"}]'::jsonb, -1965, -1961, 'approx', 19, '하란(전승)', 36.87, 39.03, 'published'),
    ('era_nt_apostolic', '2차 선교(5): 아덴—아레오바고 설교', '바울은 ‘알지 못하는 신’ 제단을 출발점으로 창조주와 부활을 선포한다.', '["아덴의 거리는 우상으로 가득하고 바울은 깊이 생각한다", "바울은 사람들과 토론하며 아레오바고에 선다", "그는 알지 못하는 신을 말하며 창조주를 전한다", "부활의 말을 들은 사람들은 서로 다른 반응을 보인다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "17:16", "to": "17:34"}]'::jsonb, 51, 51, 'approx', 20, '아덴(아레오바고)', 37.972, 23.725, 'published'),
    ('era_patriarch', '도피와 언약: 라반과의 마지막', '야곱은 라반을 떠나고, 추격 끝에 언약으로 갈등을 마무리한다.', '["야곱이 밤에 장막을 접고 몰래 길을 나선다", "라반이 분노한 얼굴로 야곱을 추격해 따라잡는다", "야곱과 라반이 격한 말다툼 끝에 돌무더기를 쌓아 경계 표를 만든다", "야곱과 라반이 서로 맹세하고 각자의 길로 갈라진다"]'::jsonb, '[["jacob"], ["jacob", "laban"], ["jacob", "laban"], ["jacob", "laban"]]'::jsonb, ARRAY['jacob', 'laban']::text[], '[{"book": "창", "from": "31:17", "to": "31:55"}]'::jsonb, -1961, -1961, 'approx', 20, '길르앗(전승)', 32, 35.7, 'published'),
    ('era_nt_public_ministry', '예루살렘 입성', '예수님은 겸손한 왕으로 입성하시고 군중은 환호한다.', '["감람산 길에서 제자들이 나귀를 끌고 온다", "예수는 나귀를 타고 예루살렘으로 들어가신다", "군중은 길에 옷과 가지를 펴고 호산나를 외친다", "예수는 성을 바라보며 잠시 걸음을 멈추신다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], [], ["jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "11:1", "to": "11:11"}, {"book": "마", "from": "21:1", "to": "21:11"}, {"book": "눅", "from": "19:28", "to": "19:40"}, {"book": "요", "from": "12:12", "to": "12:19"}]'::jsonb, 33, 33, 'approx', 20, '예루살렘', 31.778, 35.222, 'published'),
    ('era_monarchy', '히스기야와 산헤립: 두려움의 편지', '포위 속에서 히스기야는 편지를 성전에 펼치고 하나님께 매달린다.', '["성벽 아래 조롱", "히스기야가 편지를 들고 성전으로 들어간다", "히스기야가 성전에서 편지를 펼쳐 두고 간절히 기도하는 장면", "이사야가 히스기야에게 와서 하나님의 말씀을 선포하는 장면"]'::jsonb, '[[], ["hezekiah"], ["hezekiah"], ["hezekiah", "isaiah"]]'::jsonb, ARRAY['hezekiah', 'isaiah']::text[], '[{"book": "왕하", "from": "18:13", "to": "19:19"}, {"book": "사", "from": "36:1", "to": "37:20"}]'::jsonb, -701, -701, 'approx', 20, '예루살렘', 31.78, 35.22, 'published'),
    ('era_nt_apostolic', '2차 선교(6): 고린도—정착과 견딤', '고린도에서 바울은 오래 머물며 공동체를 세우고 박해를 견딘다.', '["바울은 아굴라와 브리스길라를 만나 함께 지낸다", "그는 일하며 꾸준히 복음을 전한다", "반대와 재판 속에서도 바울은 물러서지 않는다", "바울은 고린도를 떠나 다음 여정을 향해 길을 나선다"]'::jsonb, '[["paul", "aquila"], ["paul", "aquila"], ["paul"], ["paul", "aquila"]]'::jsonb, ARRAY['paul', 'aquila']::text[], '[{"book": "행", "from": "18:1", "to": "18:18"}]'::jsonb, 51, 52, 'approx', 21, '고린도', 37.939, 22.932, 'published'),
    ('era_nt_public_ministry', '성전 정화', '예수님은 성전을 ‘기도의 집’으로 회복시키려 하신다.', '["성전 뜰은 장사하는 사람들과 돈 바꾸는 이들로 붐빈다", "예수는 장사하는 자들을 내쫓고 상을 엎으신다", "예수는 성전은 기도하는 집이라고 선언하신다", "성전은 조용해지고 사람들은 놀란다"]'::jsonb, '[[], ["jesus"], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "막", "from": "11:15", "to": "11:19"}, {"book": "마", "from": "21:12", "to": "21:17"}, {"book": "눅", "from": "19:45", "to": "19:48"}, {"book": "요", "from": "2:13", "to": "2:17"}]'::jsonb, 33, 33, 'approx', 21, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_patriarch', '얍복강 씨름: 이스라엘', '야곱은 밤새 씨름하며 새 이름 ‘이스라엘’을 받는다.', '["강가의 어둠 속에서 야곱이 혼자 숨을 고른다", "천사 같은 신비한 존재가 야곱을 붙잡고 서로 씨름을 시작한다", "천사 같은 신비한 존재가 야곱의 엉덩이 뼈를 쳐서 쓰러뜨리며 야곱이 땅에 넘어진다", "이스라엘이라는 새 이름을 받은 야곱이 절뚝이며 동틀 무렵 선다"]'::jsonb, '[["jacob"], ["jacob"], ["jacob"], ["jacob"]]'::jsonb, ARRAY['jacob']::text[], '[{"book": "창", "from": "32:24", "to": "32:32"}]'::jsonb, -1960, -1960, 'approx', 21, '얍복 강가(전승)', 32.06, 35.74, 'published'),
    ('era_monarchy', '히스기야의 병과 바벨론 사신', '회복 이후의 자랑은 또 다른 위기를 예고한다.', '["히스기야가 병상에서 울며 기도하는 장면", "이사야가 히스기야에게 와서 나을 것이라고 말하는 장면", "히스기야가 다 나은 뒤 바벨론 사신들에게 보물을 자랑하는 장면", "이사야가 히스기야에게 보물을 가리키며 호통치는 장면"]'::jsonb, '[["hezekiah"], ["hezekiah", "isaiah"], ["hezekiah"], ["hezekiah", "isaiah"]]'::jsonb, ARRAY['hezekiah', 'isaiah']::text[], '[{"book": "왕하", "from": "20:1", "to": "20:19"}, {"book": "사", "from": "38:1", "to": "39:8"}]'::jsonb, -700, -700, 'approx', 21, '예루살렘', 31.78, 35.22, 'published'),
    ('era_nt_apostolic', '3차 선교(1): 에베소—확장과 충돌', '에베소에서 복음이 크게 확장되며 도시의 질서와도 충돌한다.', '["에베소에서 바울의 가르침이 널리 퍼져 간다", "많은 사람이 말씀을 듣고 삶을 돌이킨다", "복음의 영향이 커지자 도시에도 긴장이 생긴다", "소동이 일어나지만 말씀의 흐름은 멈추지 않는다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "19:1", "to": "19:41"}]'::jsonb, 53, 55, 'approx', 22, '에베소', 37.949, 27.364, 'published'),
    ('era_patriarch', '에서와 화해: 달려오는 형', '두려움으로 맞이한 재회는 포옹과 눈물로 풀린다.', '["야곱이 가족을 줄 세우고 멀리서 다가오는 에서와 무리를 보며 긴장한다", "에서와 무리가 다가오고 야곱이 땅에 엎드린다", "에서가 야곱을 껴안고 울고 야곱도 울음을 삼킨다", "야곱이 준비한 선물을 에서에게 직접 건네며 화해를 확인한다"]'::jsonb, '[["jacob", "esau"], ["jacob", "esau"], ["jacob", "esau"], ["jacob", "esau"]]'::jsonb, ARRAY['jacob', 'esau']::text[], '[{"book": "창", "from": "33:1", "to": "33:11"}]'::jsonb, -1960, -1960, 'approx', 22, '야복/에돔 경계(전승)', 32.1, 35.6, 'published'),
    ('era_monarchy', '요시야의 개혁: 율법책을 찾다', '잊힌 율법이 발견되자 요시야는 회개하고 나라를 새로 세우려 한다.', '["성전 수리 중 두루마리가 발견된다, 사람들이 숨을 삼킨다", "신하가 왕 앞에서 율법을 읽자 요시야가 옷을 찢는다", "백성이 언약을 갱신한다"]'::jsonb, '[[], ["josiah"], []]'::jsonb, ARRAY['josiah']::text[], '[{"book": "왕하", "from": "22:8", "to": "23:25"}]'::jsonb, -622, -622, 'approx', 22, '예루살렘 성전', 31.78, 35.23, 'published'),
    ('era_nt_public_ministry', '최후의 만찬', '예수님은 떡과 잔으로 새 언약을 세우시고 배신을 예고하신다.', '["다락방에 예수와 제자들이 함께 둘러앉는다", "예수는 떡과 잔을 나누시며 새 언약을 말씀하신다", "예수는 제자들 가운데 한 사람이 자신을 팔 것이라 하신다", "유다는 자리를 떠나고 방 안의 분위기는 무거워진다"]'::jsonb, '[["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["judas", "jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "14:12", "to": "14:26"}, {"book": "마", "from": "26:17", "to": "26:30"}, {"book": "눅", "from": "22:7", "to": "22:23"}, {"book": "요", "from": "13:1", "to": "13:30"}]'::jsonb, 33, 33, 'approx', 22, '예루살렘 다락방(전승)', 31.776, 35.233, 'published'),
    ('era_nt_apostolic', '3차 선교(2): 마게도냐—교회를 굳게 하다', '바울은 마게도냐를 돌며 성도들을 격려하고 공동체를 세운다.', '["바울은 여러 도시를 다시 찾아간다", "그는 성도들을 만나 말씀으로 격려한다", "공동체들은 다시 힘을 얻고 굳게 선다", "바울은 다음 여정을 향해 계속 나아간다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "20:1", "to": "20:2"}]'::jsonb, 56, 56, 'approx', 23, '마게도냐(빌립보/데살로니가 권역)', 40.64, 22.944, 'published'),
    ('era_nt_public_ministry', '겟세마네: 뜻이 이루어지다', '예수님은 고뇌 속에서 아버지의 뜻에 자신을 맡기신다.', '["예수는 제자들과 함께 겟세마네로 들어가신다", "예수는 홀로 아버지의 뜻을 구하며 기도하신다", "돌아와 보니 제자들은 잠들어 있다", "예수는 기도를 마치고 다가올 일을 맞으러 일어나신다"]'::jsonb, '[["jesus", "peter", "james", "john"], ["jesus"], ["jesus", "peter", "james", "john"], ["jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'james', 'john']::text[], '[{"book": "막", "from": "14:32", "to": "14:42"}, {"book": "마", "from": "26:36", "to": "26:46"}, {"book": "눅", "from": "22:39", "to": "22:46"}]'::jsonb, 33, 33, 'approx', 23, '겟세마네(감람산)', 31.78, 35.24, 'published'),
    ('era_patriarch', '벧엘 귀환: 라헬의 죽음', '야곱의 가정은 이동 중 큰 상실을 겪고도 약속의 길을 이어간다.', '["야곱이 결연한 표정으로 귀환 길을 재촉한다", "길 위에서 라헬이 진통하고 그 곁에 선 야곱이 초조하게 지켜본다", "라헬의 숨이 가늘어지고 갓난 베냐민 옆에서 야곱이 비통한 얼굴로 서 있다", "야곱이 무덤 기둥을 세우고 오래 서 있다"]'::jsonb, '[["jacob"], ["rachel", "jacob"], ["rachel", "benjamin", "jacob"], ["jacob"]]'::jsonb, ARRAY['jacob', 'rachel', 'benjamin']::text[], '[{"book": "창", "from": "35:1", "to": "35:20"}]'::jsonb, -1955, -1955, 'approx', 23, '베들레헴 길(전승)', 31.7, 35.2, 'published'),
    ('era_monarchy', '예루살렘 포위: 왕의 몰락', '포위는 길어지고, 마지막 순간 왕과 도시는 무너진다.', '["시드기야가 기근 속에서 근심하는 모습", "성벽이 뚫리고 도시가 혼란에 빠진다", "시드기야가 도망가다 붙잡히는 모습", "도시의 불빛이 꺼지고, 시대가 끝난다"]'::jsonb, '[["zedekiah"], [], ["zedekiah"], []]'::jsonb, ARRAY['zedekiah']::text[], '[{"book": "왕하", "from": "25:1", "to": "25:7"}]'::jsonb, -588, -586, 'approx', 23, '예루살렘', 31.78, 35.22, 'published'),
    ('era_nt_apostolic', '3차 선교(3): 헬라(고린도)—머무름과 결심', '바울은 헬라에서 머물며 다음 행선과 위험을 준비한다.', '["바울은 헬라에 머물며 사역을 이어 간다", "그는 시간을 보내며 다음 길을 준비한다", "위험의 기척 속에서도 바울의 결심은 더 분명해진다", "바울은 다음 여정을 향해 길을 다시 정한다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "20:2", "to": "20:3"}]'::jsonb, 56, 57, 'approx', 24, '고린도(헬라)', 37.939, 22.932, 'published'),
    ('era_patriarch', '요셉의 꿈: 형제들의 시기', '요셉의 꿈과 편애가 형제들의 마음을 뒤틀리게 한다.', '["17세 안팎의 어린 요셉이 채색옷을 입고 형들 사이를 지나가자 미묘한 거리감이 흐른다", "17세 안팎의 어린 요셉이 채색옷을 입고 꿈을 이야기하자 형들의 표정이 굳는다. 꿈 이야기에는 곡식단 하나가 가운데 있고 주변에 다른 곡식단들이 중앙 곡식단에게 절하고 있는 모습이 나온다", "야곱이 17세 안팎의 어린 요셉을 꾸짖지만 마음속에는 그 말을 담아둔다"]'::jsonb, '[["joseph"], ["joseph"], ["jacob", "joseph"]]'::jsonb, ARRAY['joseph', 'jacob', 'reuben', 'simeon', 'levi', 'judah', 'naphtali', 'gad', 'asher', 'issachar', 'zebulun', 'benjamin']::text[], '[{"book": "창", "from": "37:1", "to": "37:11"}]'::jsonb, -1915, -1915, 'approx', 24, '헤브론 주변(전승)', 31.53, 35.1, 'published'),
    ('era_nt_public_ministry', '체포: 배신의 입맞춤', '유다의 배신으로 예수님이 체포되고 제자들은 흩어진다.', '["유다가 무리를 이끌고 밤길로 들어온다", "유다가 예수께 다가와 입맞춤으로 신호를 보낸다", "제자들은 소란 속에 당황하고 저항하려 한다", "예수는 붙잡혀 끌려가고 제자들은 흩어진다"]'::jsonb, '[["judas"], ["judas", "jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'judas', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot']::text[], '[{"book": "막", "from": "14:43", "to": "14:52"}, {"book": "마", "from": "26:47", "to": "26:56"}, {"book": "눅", "from": "22:47", "to": "22:53"}, {"book": "요", "from": "18:1", "to": "18:11"}]'::jsonb, 33, 33, 'approx', 24, '겟세마네(감람산)', 31.78, 35.24, 'published'),
    ('era_nt_apostolic', '3차 선교(4): 밀레도—에베소 장로들과 작별', '바울은 장로들을 불러 눈물로 권면하고 다시는 못 볼지도 모른다고 말한다.', '["밀레도에 모인 장로들 앞에 바울이 선다", "바울은 지난 사역을 돌아보며 마지막 권면을 전한다", "그는 다시는 서로 얼굴을 보지 못할 수 있다고 말한다", "모두가 울며 작별하고 바울은 배에 오른다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "20:17", "to": "20:38"}]'::jsonb, 57, 57, 'approx', 25, '밀레도', 37.53, 27.276, 'published'),
    ('era_patriarch', '요셉이 팔리다: 구덩이와 은', '시기는 요셉을 구덩이에 던지고 끝내 종으로 팔아넘긴다.', '["17세 안팎의 어린 요셉이 멀리서 오자 형들이 모여 속삭인다", "17세 안팎의 어린 요셉의 옷을 빼앗고 구덩이에 던지자 절규가 메아리친다", "17세 안팎의 어린 요셉은 구덩이에 있고, 유다가 다른 형들을 말리며 손을 뻗어 제지한다", "형들의 손에 은이 쥐어지고 멀리서는 17세 안팎의 어린 요셉이 상인들에게 끌려가듯 팔려간다"]'::jsonb, '[["joseph"], ["joseph"], ["joseph", "judah"], ["joseph"]]'::jsonb, ARRAY['joseph', 'judah']::text[], '[{"book": "창", "from": "37:12", "to": "37:36"}]'::jsonb, -1915, -1915, 'approx', 25, '도단(전승)', 32.42, 35.18, 'published'),
    ('era_nt_public_ministry', '재판: 빌라도 앞', '예수님은 불의한 재판을 받으시고 침묵 속에서 길을 걸으신다.', '["예수는 빌라도 앞에 서고 지도자들은 고발을 이어 간다", "빌라도는 예수에게 여러 가지를 묻지만 예수는 잠잠히 계신다", "지도자들은 더 강하게 몰아붙이고 빌라도는 흔들린다", "끝내 판결이 내려지고 예수는 십자가의 길로 넘겨진다"]'::jsonb, '[["jesus", "pilate"], ["jesus", "pilate"], ["pilate"], ["jesus", "pilate"]]'::jsonb, ARRAY['jesus', 'pilate']::text[], '[{"book": "막", "from": "15:1", "to": "15:15"}, {"book": "마", "from": "27:11", "to": "27:26"}, {"book": "눅", "from": "23:1", "to": "23:25"}, {"book": "요", "from": "18:28", "to": "19:16"}]'::jsonb, 33, 33, 'approx', 25, '예루살렘(총독 관저, 전승)', 31.778, 35.225, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_apostolic', '로마행(1): 예루살렘 체포', '성전 소동으로 바울이 붙잡히며 ‘로마까지’의 여정이 시작된다.', '["예루살렘 성전에서 바울을 둘러싼 소동이 일어난다", "군중은 바울을 붙잡고 거세게 몰아붙인다", "병사들이 바울을 계단 위로 데려가며 상황을 수습한다", "묶인 바울 앞에 로마로 이어질 긴 여정이 시작된다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "21:27", "to": "21:36"}]'::jsonb, 57, 57, 'approx', 26, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_patriarch', '보디발의 집: 성실과 누명', '요셉은 유혹을 거절하지만 누명을 쓰고 감옥으로 내려간다.', '["종으로 팔려 온 요셉이 보디발의 집 살림을 정리하며 보디발에게 신뢰를 얻고 열쇠를 넘겨받는다", "한 여자가 침대에 앉아 다리를 꼰 채 요셉에게 말을 걸고, 요셉은 앞쪽에 서서 굳은 표정으로 대답한다", "옷을 남기고 달아나는 요셉 뒤로 여자의 고함이 터진다", "감옥에 갇힌 요셉이 죄수들의 일을 맡아 분주히 정리한다"]'::jsonb, '[["potiphar", "joseph"], ["joseph"], ["joseph"], ["joseph"]]'::jsonb, ARRAY['joseph', 'potiphar']::text[], '[{"book": "창", "from": "39:1", "to": "39:23"}]'::jsonb, -1910, -1909, 'approx', 26, '애굽(전승)', 29.85, 31.25, 'published'),
    ('era_nt_public_ministry', '십자가: 끝까지 사랑', '예수님은 십자가에서 마지막까지 사랑을 드러내신다.', '["예수는 골고다로 향하는 길을 걸어가신다", "십자가가 세워지고 사람들은 멀리서 지켜본다", "예수는 마지막 말씀을 남기신다", "예수의 죽음 앞에 사람들이 깊은 충격에 잠긴다"]'::jsonb, '[["jesus"], ["jesus"], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "막", "from": "15:21", "to": "15:39"}, {"book": "마", "from": "27:32", "to": "27:54"}, {"book": "눅", "from": "23:26", "to": "23:49"}, {"book": "요", "from": "19:17", "to": "19:37"}]'::jsonb, 33, 33, 'approx', 26, '골고다(예루살렘)', 31.778, 35.229, 'published'),
    ('era_nt_apostolic', '로마행(2): 가이사랴 재판과 상소', '바울은 재판 자리에서 증언하고 ‘가이사에게 상소’한다.', '["가이사랴 재판정에 바울이 다시 선다", "총독들과 왕 앞에서 바울은 자신의 믿음을 증언한다", "논의가 이어지지만 바울은 흔들리지 않는다", "바울은 끝내 가이사에게 상소한다"]'::jsonb, '[["paul", "festus", "agrippa"], ["paul", "festus", "agrippa"], ["paul", "festus", "agrippa"], ["paul", "festus"]]'::jsonb, ARRAY['paul', 'festus', 'agrippa']::text[], '[{"book": "행", "from": "24:10", "to": "24:27"}, {"book": "행", "from": "25:7", "to": "25:12"}, {"book": "행", "from": "26:1", "to": "26:32"}]'::jsonb, 59, 59, 'approx', 27, '가이사랴', 32.5, 34.89, 'published'),
    ('era_patriarch', '바로의 꿈: 총리 요셉', '바로의 꿈을 해석한 요셉은 애굽의 총리로 세워진다.', '["바로가 꿈에서 깨어 불안해하고 신하들이 술렁인다", "요셉이 일곱 해 풍년과 일곱 해 흉년을 설명하며 계획을 제시한다", "바로가 옆에서 지켜보는 가운데, 요셉은 파라오가 아닌 애굽의 총리로서 절제된 흰 관복과 금청 장식, 얇은 머리띠를 하고 사람들 앞에 선다"]'::jsonb, '[["pharaoh"], ["joseph"], ["pharaoh", "joseph"]]'::jsonb, ARRAY['joseph', 'pharaoh']::text[], '[{"book": "창", "from": "41:1", "to": "41:57"}]'::jsonb, -1900, -1900, 'approx', 27, '애굽(전승)', 29.85, 31.25, 'published'),
    ('era_nt_public_ministry', '부활과 승천: 새 시작', '부활하신 예수님은 제자들에게 사명을 주시고 승천하신다.', '["새벽에 여인들이 빈 무덤 앞에 선다", "부활하신 예수는 여인들과 제자들에게 나타나신다", "예수는 제자들에게 사명을 맡기신다", "예수는 감람산에서 승천하시고 제자들은 하늘을 바라본다"]'::jsonb, '[["mary_magdalene"], ["jesus", "mary_magdalene"], ["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus", "peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'mary_magdalene', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "마", "from": "28:1", "to": "28:20"}, {"book": "눅", "from": "24:1", "to": "24:53"}, {"book": "요", "from": "20:1", "to": "20:29"}, {"book": "행", "from": "1:1", "to": "1:11"}]'::jsonb, 33, 33, 'approx', 27, '예루살렘(무덤) → 감람산(전승)', 31.78, 35.24, 'published'),
    ('era_nt_apostolic', '로마행(3): 폭풍의 항해', '폭풍 속에서 바울은 ‘두려워 말라’는 약속으로 사람들을 붙든다.', '["거센 바람이 배를 뒤흔들고 사람들은 두려움에 빠진다", "오랜 폭풍 속에 모두가 지쳐 간다", "바울은 하나님이 살려 주실 것이라며 사람들을 붙든다", "배는 계속 흔들리지만 사람들은 다시 버틸 힘을 얻는다"]'::jsonb, '[[], [], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "27:13", "to": "27:26"}]'::jsonb, 59, 59, 'approx', 28, '지중해 항로(그레데 근처, 전승)', 35.2, 25.1, 'published'),
    ('era_patriarch', '요셉의 정체 공개: 울음의 방', '요셉은 더 이상 참지 못하고 형제들에게 자신을 드러낸다.', '["파라오처럼 보이지 않는 애굽 총리 요셉이 형들 앞에서 울음을 터뜨리자 형들은 당황해 얼어붙는다", "요셉이 총리의 겉모습 일부를 내려놓고 자신이 요셉임을 밝히자 형들이 크게 놀란다", "파라오처럼 보이지 않는 총리 차림의 요셉이 베냐민을 끌어안고, 형들은 뒤에서 놀란 얼굴로 그 모습을 바라본다"]'::jsonb, '[["joseph"], ["joseph"], ["joseph", "benjamin"]]'::jsonb, ARRAY['joseph']::text[], '[{"book": "창", "from": "45:1", "to": "45:15"}]'::jsonb, -1885, -1885, 'approx', 28, '애굽(요셉의 집, 전승)', 29.85, 31.25, 'published'),
    ('era_patriarch', '고센 정착: 만남과 눈물', '요셉은 야곱을 맞이하고, 이스라엘은 고센에 자리 잡는다.', '["애굽 총리 요셉이 전차를 타고 신하들과 고센으로 달려간다", "애굽 총리 요셉과 야곱이 마주 보고 끌어안고 운다", "애굽 총리 요셉이 가족을 바로 앞에 세우며 예의를 지킨다", "바로와 야곱이 서로 이야기하고 그 사이에 애굽 총리 요셉이 서 있다"]'::jsonb, '[["joseph"], ["jacob", "joseph"], ["joseph", "pharaoh"], ["pharaoh", "jacob", "joseph"]]'::jsonb, ARRAY['jacob', 'joseph', 'pharaoh']::text[], '[{"book": "창", "from": "46:28", "to": "47:12"}]'::jsonb, -1880, -1879, 'approx', 29, '고센 땅(나일 델타, 전승)', 30.8, 31.85, 'published'),
    ('era_nt_apostolic', '로마행(4): 멜리데(몰타) 표류', '난파 후 섬에 도착하고, 바울을 통한 표징으로 사람들이 마음을 연다.', '["난파한 사람들이 멜리데 섬 해안에 간신히 오른다", "섬사람들은 비와 추위 속에서 불을 피워 맞아 준다", "바울이 독사에 물리고도 해를 입지 않자 섬사람들은 크게 놀란다", "바울이 병든 이들을 고치자 섬사람들은 일행을 존중하며 필요한 것을 채워 준다"]'::jsonb, '[["paul"], [], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "27:39", "to": "27:44"}, {"book": "행", "from": "28:1", "to": "28:10"}]'::jsonb, 60, 60, 'approx', 29, '몰타(멜리데)', 35.9, 14.51, 'published'),
    ('era_nt_apostolic', '로마행(5): 로마 도착', '바울은 로마에 도착해 묶인 상태로도 복음을 전한다.', '["바울은 마침내 로마에 들어선다", "그는 묶인 몸이지만 머물 곳을 얻게 된다", "찾아오는 사람들에게 하나님 나라를 전한다", "복음은 로마 한가운데서도 막히지 않는다"]'::jsonb, '[["paul"], ["paul"], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "28:14", "to": "28:31"}]'::jsonb, 60, 62, 'approx', 30, '로마', 41.902, 12.496, 'published'),
    ('era_patriarch', '야곱의 축복: 열두 아들', '야곱은 마지막 순간 아들들을 불러 각 지파의 길을 예언적으로 선언한다.', '["늙은 야곱이 침상에서 힘들게 몸을 일으킨다", "애굽 총리의 옷을 입은 요셉이 두 아들을 데려오고 야곱의 손이 교차한다", "늙은 야곱이 아들들을 바라보며 무거운 축복의 말을 남긴다", "턱수염과 머리가 하얗게 센 늙은 야곱이 마지막 숨을 고르며 눈을 감는다"]'::jsonb, '[["jacob"], ["jacob", "joseph"], ["jacob"], ["jacob"]]'::jsonb, ARRAY['jacob', 'joseph']::text[], '[{"book": "창", "from": "48:1", "to": "48:22"}, {"book": "창", "from": "49:1", "to": "49:28"}]'::jsonb, -1860, -1860, 'approx', 30, '애굽(전승)', 29.85, 31.25, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;


alter table events enable trigger trg_notify_on_new_event;
commit;
