-- Generated by tools/seed/build_200_stories_seed_sql.py
-- Generated at UTC: 2026-04-21T13:04:44.664680+00:00
-- Target table: events
-- (person_codes / bible_refs / story_scenes / scene_persons live
--  on the events row itself; person_eras and events_ordered are views.)
begin;

-- Upsert events from 200 stories
with seed_events (era_code, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_monarchy', '111 솔로몬 즉위: 지혜의 선택', '솔로몬은 왕으로 세워지고 ‘지혜’를 구해 길을 연다.', '["다윗의 마지막 지시를 솔로몬이 긴장한 얼굴로 듣는다", "솔로몬의 즉위 장면, 군중의 환호가 터진다", "밤의 꿈속에 하나님이 솔로몬에게 나타나시는 장면", "솔로몬이 언약궤 앞에 서서 번제와 감사의 제물을 드리고 신하들은 기쁜 표정을 짓는다"]'::jsonb, '[["solomon", "david"], ["solomon"], ["solomon", "god"], ["solomon"]]'::jsonb, ARRAY['solomon', 'david', 'god']::text[], '[{"book": "왕상", "from": "1:28", "to": "3:15"}]'::jsonb, -970, -967, 'approx', 16, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '112 성전 건축: 손으로 짓는 집', '솔로몬은 오랜 준비 끝에 성전을 건축한다.', '["목재와 돌이 모인다, 일꾼들의 발걸음이 분주하다", "돌을 다듬는 소리, 조용히 올라가는 구조", "빛이 반사되어 은은히 번진다", "마지막 기둥이 세워지고, 성전이 완성된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['solomon']::text[], '[{"book": "왕상", "from": "5:1", "to": "6:38"}]'::jsonb, -966, -959, 'approx', 17, '예루살렘 성전 터(전승)', 31.78, 35.23, 'published'),
    ('era_monarchy', '113 성전 봉헌: 기도와 영광', '솔로몬의 봉헌 기도 후 하나님의 임재가 성전을 채운다.', '["언약궤가 성전으로 들어온다, 제사장들이 조심히 걷는다", "솔로몬이 두 손을 들고 기도한다, 엄숙", "구름이 성전을 덮는다, 제사장들이 멈칫한다", "솔로몬이 사람들은 숨죽인 채 임재를 느끼며 고개를 숙인다"]'::jsonb, '[[], ["solomon"], [], ["solomon"]]'::jsonb, ARRAY['solomon']::text[], '[{"book": "왕상", "from": "8:1", "to": "8:11"}]'::jsonb, -959, -959, 'approx', 18, '예루살렘 성전', 31.78, 35.23, 'published'),
    ('era_monarchy', '114 솔로몬: 이방의 경탄부터 타락까지', '솔로몬의 지혜와 영화는 이방을 놀라게 했지만, 말년의 타락은 왕국의 균열을 예고했다.', '["낙타 행렬이 도착한다, 이국적 선물들이 펼쳐진다", "스바 여왕이 수수께끼를 던지고, 솔로몬이 조용히 대답한다", "솔로몬이 이방 여인들을 들여오며 마음이 흐려지는 장면", "늙은 솔로몬이 생을 마치고 궁정이 조용해지는 장면"]'::jsonb, '[[], ["solomon"], ["solomon"], ["solomon"]]'::jsonb, ARRAY['solomon']::text[], '[{"book": "왕상", "from": "10:1", "to": "11:43"}]'::jsonb, -950, -950, 'approx', 19, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '115 왕국의 분열과 역사', '왕국은 남과 북으로 갈라졌고, 결국 북이스라엘과 남유다는 각각 심판 속에 무너졌다.', '["내부에서 남과 북이 두 갈래로 갈라져 서로 맞서는 모습", "완전히 분열된 북왕국과 남왕국의 모습", "북왕국 이스라엘이 BC 722년에 앗수르에 의해 멸망하는 장면", "남왕국 유다가 BC 586년에 바벨론에 의해 멸망하는 장면"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "왕상", "from": "12:1", "to": "16:34"}]'::jsonb, -930, -930, 'approx', 20, '세겜(전승)', 32.22, 35.28, 'published'),
    ('era_monarchy', '116 엘리야와 갈멜: 불의 응답', '엘리야는 하나님이 참 하나님이심을 불의 응답으로 드러낸다.', '["바알 선지자들의 소란, 사람들의 얼굴이 흔들린다", "엘리야가 결연한 표정으로 선다", "엘리야가 제단에 물을 붓고 조용히 기도한다", "불이 임하고 백성이 엎드린다, 여호와 그가 하나님이시로다!"]'::jsonb, '[[], ["elijah"], ["elijah"], ["elijah"]]'::jsonb, ARRAY['elijah']::text[], '[{"book": "왕상", "from": "18:20", "to": "18:39"}]'::jsonb, -860, -860, 'approx', 21, '갈멜 산', 32.83, 34.97, 'published'),
    ('era_monarchy', '117 호렙의 엘리야: 조용한 음성', '엘리야는 절망 속에서 ‘세미한 음성’으로 다시 부르심을 받는다.', '["엘리야가 광야에 쓰러진다, 차라리 죽여 주옵소서", "천사의 돌봄, 빵과 물, 엘리야가 다시 일어난다", "늙은 엘리야 앞에서 큰 바람과 지진과 불이 지나가고, 그 뒤에 고요가 온다", "조용한 음성, 엘리야가 얼굴을 가리고 다시 길을 나선다"]'::jsonb, '[["elijah"], ["elijah"], ["elijah"], ["elijah"]]'::jsonb, ARRAY['elijah']::text[], '[{"book": "왕상", "from": "19:1", "to": "19:18"}]'::jsonb, -860, -860, 'approx', 22, '호렙 산(전승)', 28.54, 33.98, 'published'),
    ('era_monarchy', '118 나봇의 포도원: 빼앗긴 정의', '권력은 거짓 증언으로 무고한 자를 무너뜨리고, 예언은 죄를 드러낸다.', '["중년 남자 아합 왕이 40대 남자 나봇에게 포도원을 팔라고 권유하지만 거절당하는 장면", "아합 왕이 뒤에 앉아 있고, 이세벨 여왕이 악한 표정으로 편지를 쓰는 장면", "성문 밖에서 백성 무리가 나봇을 돌로 치고, 멀리 나봇이 쓰러지는 장면", "엘리야가 아합과 이세벨에게 재앙이 임할 것을 호통치며 선포하는 장면"]'::jsonb, '[["ahab"], ["ahab"], [], ["elijah", "ahab"]]'::jsonb, ARRAY['ahab', 'elijah']::text[], '[{"book": "왕상", "from": "21:1", "to": "21:19"}]'::jsonb, -855, -855, 'approx', 23, '이스르엘(전승)', 32.56, 35.32, 'published'),
    ('era_monarchy', '119 엘리야 승천: 겉옷의 계승', '엘리야는 떠나고, 엘리사는 겉옷과 사명을 이어받는다.', '["늙은 노인 엘리야가 엘리사에게 마지막 길을 함께 가자고 말하는 장면", "늙은 노인 엘리야가 겉옷으로 요단강 물을 치자 길이 열리는 장면", "늙은 노인 엘리야가 불수레와 함께 하늘로 들려 올라가고, 엘리사가 울부짖는 장면", "엘리사가 겉옷을 들고 요단을 치자 물이 갈라지는 장면"]'::jsonb, '[["elijah", "elisha"], ["elijah"], ["elijah", "elisha"], ["elisha"]]'::jsonb, ARRAY['elijah', 'elisha']::text[], '[{"book": "왕하", "from": "2:1", "to": "2:14"}]'::jsonb, -850, -850, 'approx', 24, '요단강 근처(전승)', 31.85, 35.55, 'published'),
    ('era_monarchy', '120 나아만: 요단의 일곱 번', '자존심을 내려놓을 때 치유가 찾아온다.', '["문둥병에 걸린 젊은 장수 나아만이 이스라엘로 향하는 장면", "엘리사의 작은 종이 나아만에게 말하고, 나아만은 화를 내는 장면", "젊은 장수 나아만이 분한 얼굴로 요단강 물에 몸을 담그는 장면", "젊은 장수 나아만의 문둥병이 깨끗이 나은 장면"]'::jsonb, '[["naaman"], ["naaman"], ["naaman"], ["naaman"]]'::jsonb, ARRAY['naaman', 'elisha']::text[], '[{"book": "왕하", "from": "5:1", "to": "5:14"}]'::jsonb, -845, -845, 'approx', 25, '사마리아/요단강(전승)', 32.46, 35.55, 'published'),
    ('era_monarchy', '121 예후의 혁명: 칼날의 교체', '예후는 급진적 정변으로 왕조를 교체하지만 폭력의 그림자를 남긴다.', '["젊은 청년 예후가 선지자에게 기름부음을 받는 장면", "젊은 청년 예후가 전차와 함께 어떤 왕을 무너뜨리는 장면", "젊은 청년 예후가 어떤 왕후의 몰락을 지켜보는 장면", "젊은 청년 예후가 금송아지를 섬기며 이스라엘이 죄에서 떠나지 않는 장면"]'::jsonb, '[["jehu"], ["jehu"], ["jehu"], ["jehu"]]'::jsonb, ARRAY['jehu']::text[], '[{"book": "왕하", "from": "9:1", "to": "10:31"}]'::jsonb, -841, -841, 'approx', 26, '이스르엘/사마리아(전승)', 32.56, 35.32, 'published'),
    ('era_monarchy', '122 북왕국 멸망: 사마리아 함락', '오랜 경고 끝에 북왕국은 무너지고 백성은 흩어진다.', '["성벽 위 병사들, 포위가 길어지고 식량이 줄어든다", "성이 뚫리고 사람들이 달아난다, 혼란의 소리", "사슬에 묶인 행렬이 먼 곳으로 끌려간다", "텅 빈 도시, 바람만 불고, 끝이 남는다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "왕하", "from": "17:5", "to": "17:23"}]'::jsonb, -722, -722, 'approx', 27, '사마리아', 32.28, 35.19, 'published'),
    ('era_monarchy', '123 히스기야와 산헤립: 두려움의 편지', '포위 속에서 히스기야는 편지를 성전에 펼치고 하나님께 매달린다.', '["성벽 아래 조롱", "히스기야가 편지를 들고 성전으로 들어간다", "히스기야가 성전에서 편지를 펼쳐 두고 간절히 기도하는 장면", "이사야가 히스기야에게 와서 하나님의 말씀을 선포하는 장면"]'::jsonb, '[[], ["hezekiah"], ["hezekiah"], ["hezekiah", "isaiah"]]'::jsonb, ARRAY['hezekiah', 'isaiah']::text[], '[{"book": "왕하", "from": "18:13", "to": "19:19"}, {"book": "사", "from": "36:1", "to": "37:20"}]'::jsonb, -701, -701, 'approx', 28, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '124 히스기야의 병과 바벨론 사신', '회복 이후의 자랑은 또 다른 위기를 예고한다.', '["히스기야가 병상에서 울며 기도하는 장면", "이사야가 히스기야에게 와서 나을 것이라고 말하는 장면", "히스기야가 다 나은 뒤 바벨론 사신들에게 보물을 자랑하는 장면", "이사야가 히스기야에게 보물을 가리키며 호통치는 장면"]'::jsonb, '[["hezekiah"], ["hezekiah", "isaiah"], ["hezekiah"], ["hezekiah", "isaiah"]]'::jsonb, ARRAY['hezekiah', 'isaiah']::text[], '[{"book": "왕하", "from": "20:1", "to": "20:19"}, {"book": "사", "from": "38:1", "to": "39:8"}]'::jsonb, -700, -700, 'approx', 29, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '125 요시야의 개혁: 율법책을 찾다', '잊힌 율법이 발견되자 요시야는 회개하고 나라를 새로 세우려 한다.', '["성전 수리 중 두루마리가 발견된다, 사람들이 숨을 삼킨다", "josiah가 josiah가 josiah가 josiah가 josiah가 josiah가 왕 앞에서 율법을 읽자 요시야가 옷을 찢는다", "배경과 분위기만 보이는", "백성이 언약을 갱신한다"]'::jsonb, '[[], ["josiah"], [], []]'::jsonb, ARRAY['josiah']::text[], '[{"book": "왕하", "from": "22:8", "to": "23:25"}]'::jsonb, -622, -622, 'approx', 30, '예루살렘 성전', 31.78, 35.23, 'published'),
    ('era_monarchy', '126 예레미야의 소명: 불타는 말씀', '예레미야는 두려움 속에서도 ‘내가 네 입에 말을 두었다’는 부르심을 받는다.', '["젊은 예레미야가 멈칫한다, 나는 아이라 말할 줄 모릅니다", "하나님의 빛이 젊은 예레미야에게 임하는 장면", "예레미야에게 하나님의 말씀이 주어지는 장면", "예레미야가 도시를 바라보는 장면"]'::jsonb, '[["jeremiah"], ["jeremiah", "god"], ["jeremiah", "god"], ["jeremiah"]]'::jsonb, ARRAY['jeremiah', 'god']::text[], '[{"book": "렘", "from": "1:4", "to": "1:10"}]'::jsonb, -627, -627, 'approx', 31, '아나돗(전승)', 31.84, 35.26, 'published'),
    ('era_monarchy', '127 바벨론의 압박: 첫 포로', '바벨론의 힘 앞에서 유다는 흔들리고, 일부가 포로로 끌려간다.', '["성벽 밖에 바벨론 군대의 깃발이 늘어선다", "궁 안에서 협상과 두려움이 교차한다", "여호야긴 왕이 백성들과 함께 바벨론에 잡혀가는 장면", "새로운 20살 왕 시드기야가 바벨론을 배신하는 장면"]'::jsonb, '[[], [], ["jehoiachin"], ["zedekiah"]]'::jsonb, ARRAY['jehoiachin']::text[], '[{"book": "왕하", "from": "24:10", "to": "24:17"}]'::jsonb, -597, -597, 'approx', 32, '예루살렘', 31.78, 35.22, 'published'),
    ('era_monarchy', '128 예루살렘 포위: 왕의 몰락', '포위는 길어지고, 마지막 순간 왕과 도시는 무너진다.', '["시드기야가 기근 속에서 근심하는 모습", "성벽이 뚫리고 도시가 혼란에 빠진다", "시드기야가 도망가다 붙잡히는 모습", "도시의 불빛이 꺼지고, 시대가 끝난다"]'::jsonb, '[["zedekiah"], [], ["zedekiah"], []]'::jsonb, ARRAY['zedekiah']::text[], '[{"book": "왕하", "from": "25:1", "to": "25:7"}]'::jsonb, -588, -586, 'approx', 33, '예루살렘', 31.78, 35.22, 'published'),
    ('era_exile_return', '129 예루살렘 함락: 성전이 불타다', '성전이 파괴되고 백성은 포로로 끌려가며 포로 시대가 시작된다.', '["성전 쪽으로 번지는 불빛과 연기", "israelites가 israelites가 israelites가 israelites가 israelites가 israelites가 사람들이 집을 떠나 끌려간다, 울음소리가 멀어진다", "배경과 분위기만 보이는", "텅 빈 도시에 바람만 남고, 화면이 천천히 어두워진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "왕하", "from": "25:8", "to": "25:21"}]'::jsonb, -586, -586, 'approx', 1, '예루살렘', 31.78, 35.23, 'published'),
    ('era_exile_return', '130 남은 자의 선택: 두 갈래 길', '남은 자들은 두려움 속에서 떠나고, 예레미야의 경고는 외면된다.', '["백성들이 예레미야에게 와서 기도를 간구하는 장면", "하나님의 말씀이 예레미야에게 임하는 장면", "예레미야가 사람들에게 하나님의 말씀을 강하게 전하지만 사람들은 듣지 않고 가버리는 장면", "예레미야가 바로의 궁전 대문 벽돌 축대에 큰 돌 여러 개를 진흙으로 감추는 장면"]'::jsonb, '[["jeremiah"], ["jeremiah", "god"], ["jeremiah"], ["jeremiah"]]'::jsonb, ARRAY['jeremiah']::text[], '[{"book": "렘", "from": "42:1", "to": "43:7"}]'::jsonb, -585, -585, 'approx', 2, '유다 땅(미스바/애굽 길, 전승)', 31.83, 35.17, 'published'),
    ('era_exile_return', '131 에스겔의 소명: 보좌의 환상', '포로지에서 에스겔은 하나님의 영광을 보고 파수꾼의 사명을 받는다.', '["강가에 앉은 에스겔, 하늘이 갈라지는 듯한 빛", "바퀴와 생물의 환상, 에스겔이 몸을 떤다", "배경과 분위기만 보이는", "에스겔이 일어나 포로 공동체를 바라본다, 파수꾼의 눈빛"]'::jsonb, '[["ezekiel"], ["ezekiel"], [], ["ezekiel"]]'::jsonb, ARRAY['ezekiel']::text[], '[{"book": "겔", "from": "1:1", "to": "3:11"}]'::jsonb, -593, -593, 'approx', 3, '그발 강가(바벨론, 전승)', 32.55, 44.42, 'published'),
    ('era_exile_return', '132 마른 뼈: 숨이 들어오다', '절망의 뼈들에게 말씀과 숨이 임해 회복의 그림이 그려진다.', '["뼈들로 가득한 골짜기, 바람도 없는 정적", "에스겔이 대언하라는 명령", "에스겔이 서 있는 가운데 마른 뼈 위에 힘줄과 살이 덮이기 시작한다", "숨이 돌아온 사람들이 일어서고 그 한가운데 에스겔이 서 있다"]'::jsonb, '[[], ["ezekiel"], ["ezekiel"], ["ezekiel"]]'::jsonb, ARRAY['ezekiel']::text[], '[{"book": "겔", "from": "37:1", "to": "37:14"}]'::jsonb, -585, -585, 'approx', 4, '그발 강가(추정)', 32.55, 44.42, 'published'),
    ('era_exile_return', '133 다니엘: 뜻을 정하다', '다니엘은 낯선 제국 한복판에서 믿음의 기준을 세운다.', '["궁정의 화려한 식탁, 다니엘이 멈춘다", "다니엘이 앞쪽에 서 있고, 관리가 난처해한다", "다니엘이 왕에게 단정한 제안을 하는 장면", "다니엘이 이전보다 더 건강한 모습으로 왕 앞에 서고 왕이 놀라는 장면"]'::jsonb, '[["daniel"], ["daniel"], ["daniel"], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "1:8", "to": "1:20"}]'::jsonb, -605, -605, 'approx', 5, '바벨론', 32.55, 44.42, 'published'),
    ('era_exile_return', '134 풀무불: 다니엘과 세 친구', '우상 숭배 강요 앞에서 믿음은 굴복 대신 신실함을 택한다.', '["다니엘과 세 친구가 거대한 금 신상 앞에서 서 있고, 다른 사람들은 모두 엎드린다", "다니엘과 세 친구가 왕 앞에서 믿음을 굽히지 않는 장면", "풀무불 속에서 다니엘과 세 친구가 함께 서 있는 장면", "왕이 다니엘과 세 친구를 칭찬하는 모습"]'::jsonb, '[["daniel"], ["daniel"], ["daniel"], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "3:1", "to": "3:30"}]'::jsonb, -585, -585, 'approx', 6, '바벨론(전승)', 32.55, 44.42, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_persons,
  s.person_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_persons = excluded.scene_persons,
  person_codes = excluded.person_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_exile_return', '135 벨사살의 잔치: 벽에 쓴 글', '교만한 잔치에 ‘손 글씨’가 나타나고, 심판이 선포된다.', '["화려한 잔치, 웃음과 술잔 소리로 가득하다", "벽에 나타난 손 글씨, 모두가 얼어붙는다", "다니엘이 해석한다, 너는 저울에 달려 부족함이 보였다", "왕이 다니엘에게 자주색 옷을 입히게 하며 금 사슬을 그의 목에 걸어 주는 장면"]'::jsonb, '[[], [], ["daniel"], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "5:1", "to": "5:31"}]'::jsonb, -539, -539, 'approx', 7, '바벨론', 32.55, 44.42, 'published'),
    ('era_exile_return', '136 사자굴: 멈추지 않는 기도', '금지령 속에서도 다니엘은 기도를 멈추지 않고, 구원은 새벽에 드러난다.', '["관원들이 계략을 꾸민다, 그의 하나님을 걸어야 한다", "다니엘이 창을 열고 기도한다, 소문이 퍼진다", "신하들이 왕에게 말하고, 왕이 괴로워하는 장면", "새벽, 다니엘의 목소리가 들린다, 하나님이 사자들의 입을 막으셨습니다"]'::jsonb, '[[], ["daniel"], [], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "6:1", "to": "6:28"}]'::jsonb, -537, -537, 'approx', 8, '바벨론/메대-바사(전승)', 32.55, 44.42, 'published'),
    ('era_exile_return', '137 고레스 칙령: 돌아가라', '고레스의 칙령으로 귀환의 문이 열리고 성전 재건이 시작된다.', '["칙령이 낭독된다, 사람들이 서로를 바라본다", "누군가 울음을 터뜨린다, 돌아갈 수 있다", "짐을 싸고 긴 행렬이 길을 나선다", "멀리 예루살렘 방향으로 해가 뜬다, 희망의 톤"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['cyrus']::text[], '[{"book": "스", "from": "1:1", "to": "1:4"}]'::jsonb, -538, -538, 'approx', 9, '바벨론 → 예루살렘(전승)', 32.55, 44.42, 'published'),
    ('era_exile_return', '138 제단과 예배 회복', '폐허 위에서 먼저 예배가 회복되고 제단이 다시 세워진다.', '["returnees가 returnees가 returnees가 손에 돌을 들고 있다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 제단을 쌓고 불을 밝힌다, 모두가 숨을 죽인다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 제사가 드려지고, 오래 잊었던 노래가 다시 울린다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 어떤 이는 울고 어떤 이는 기뻐한다, 처음이 다시 시작된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "스", "from": "3:1", "to": "3:6"}]'::jsonb, -537, -537, 'approx', 10, '예루살렘(성전 터)', 31.78, 35.23, 'published'),
    ('era_exile_return', '139 성전 재건: 방해와 완공', '방해가 이어지지만 성전은 결국 다시 세워진다.', '["주변 사람들이 접근한다, 긴장이 감돈다", "거절 후 방해와 협박이 시작된다, 작업이 멈춘다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 다시 망치 소리, 돌이 쌓이고 골조가 올라간다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 완공 예배, 사람들의 얼굴에 눈물과 웃음이 함께 있다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "스", "from": "4:1", "to": "4:6"}, {"book": "스", "from": "6:13", "to": "6:22"}]'::jsonb, -536, -516, 'approx', 11, '예루살렘', 31.78, 35.23, 'published'),
    ('era_exile_return', '140 에스더: 왕후가 되다', '에스더는 예상치 못한 자리에서 왕후가 되어 때를 기다린다.', '["에스더가 왕후가 되기 전, 다른 후보들과 함께 궁정에 모인 모습", "왕관이 없는 후보의 모습인 에스더가 왕 앞에 선다, 방 안이 숨을 죽인다", "왕이 왕관을 씌운다, 에스더의 얼굴이 굳어지며 책임을 느낀다", "모르드개가 멀리서 지켜본다, 때가 올 것 같은 눈빛"]'::jsonb, '[["esther"], ["esther"], ["esther"], ["mordecai"]]'::jsonb, ARRAY['esther', 'mordecai']::text[], '[{"book": "에", "from": "2:5", "to": "2:18"}]'::jsonb, -480, -480, 'approx', 12, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_exile_return', '141 하만의 음모: 유다인을 없애라', '모르드개의 거절은 하만의 분노를 불러 대규모 학살 음모로 번진다.', '["하만이 지나가고 모두가 절하지만, 모르드개만 서 있다", "하만의 얼굴이 붉어진다, 한 사람만이 아니라, 민족을", "하만이 제비를 던져 날짜를 정하는 장면", "조서가 퍼지고 수산 성이 어지러워진다, 에스더의 손이 떨린다"]'::jsonb, '[["haman", "mordecai"], ["haman"], ["haman"], ["esther"]]'::jsonb, ARRAY['esther', 'haman', 'mordecai']::text[], '[{"book": "에", "from": "3:1", "to": "3:15"}]'::jsonb, -474, -474, 'approx', 13, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_exile_return', '142 에스더의 결단: 죽으면 죽으리라', '에스더는 금식 후 왕 앞에 나아가기로 결단한다.', '["에스더가 망설인다, 부름 없이 나아가면", "모르드개가 앞쪽에 서 있다", "에스더가 결연한 표정으로 선다", "에스더가 문을 향해 걸어간다, 죽으면 죽으리라"]'::jsonb, '[["esther"], ["mordecai"], ["esther"], ["esther"]]'::jsonb, ARRAY['esther', 'mordecai']::text[], '[{"book": "에", "from": "4:10", "to": "4:17"}]'::jsonb, -474, -474, 'approx', 14, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_exile_return', '143 잔치의 반전: 하만의 몰락', '에스더의 잔치 자리에서 음모가 폭로되고 하만은 무너진다.', '["왕과 에스더가 이야기하는 장면", "하만이 궁궐 안에 나무를 세우는 장면", "잔치 자리에서 왕과 에스더와 대신들이 앉아 있고, 하만은 머리를 싸고 번뇌하며, 모르드개가 말을 타고 잔치로 들어오는 모습", "하만이 자기가 세운 나무에 달리는 장면"]'::jsonb, '[["esther"], ["haman"], ["esther", "haman", "mordecai"], ["haman"]]'::jsonb, ARRAY['esther', 'haman', 'mordecai']::text[], '[{"book": "에", "from": "5:1", "to": "7:10"}]'::jsonb, -474, -474, 'approx', 15, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_exile_return', '144 부림절: 살아남은 날', '구원의 반전은 기억의 축제가 되어 공동체를 살린다.', '["사람들이 서로를 확인하며 안도의 숨을 쉰다", "모르드개가 편지를 쓰고 소식이 퍼진다", "선물을 나누고 음식을 나누는 앞쪽에 서 있고, 웃음과 눈물이 섞인다", "달력에 표시되는 부림, 기억이 제도가 된다"]'::jsonb, '[[], ["mordecai"], [], []]'::jsonb, ARRAY['esther', 'mordecai']::text[], '[{"book": "에", "from": "9:20", "to": "9:28"}]'::jsonb, -473, -473, 'approx', 16, '페르시아 전역(상징)', 32.19, 48.26, 'published'),
    ('era_exile_return', '145 에스라의 귀환: 말씀으로 정리하다', '에스라는 말씀의 사람으로 돌아와 공동체를 재정비한다.', '["에스라가 두루마리를 펼쳐 읽는다, 눈빛이 단단하다", "귀환 행렬이 길을 나선다, 먼지 나는 길 위의 결단", "예루살렘에 도착한 에스라가 현실을 보고 고개를 숙인다", "에스라가 율법을 연구하고 행하며 가르치기로 뜻을 정했다가 울린다"]'::jsonb, '[["ezra"], [], ["ezra"], ["ezra"]]'::jsonb, ARRAY['ezra']::text[], '[{"book": "스", "from": "7:1", "to": "7:10"}]'::jsonb, -458, -458, 'approx', 17, '바벨론 → 예루살렘(전승)', 32.55, 44.42, 'published'),
    ('era_exile_return', '146 느헤미야의 파송: 무너진 성벽 소식', '느헤미야는 예루살렘 소식을 듣고 눈물로 기도한 뒤 파송을 받는다.', '["느헤미야가 소식을 듣고 무너진 얼굴로 앉아 운다", "느헤미야가 밤의 기도, 주의 이름을 경외하는 종들을 기억하소서", "상대를 바라보며 기다린다, 느헤미야가 숨을 고른다", "왕의 허락과 편지가 주어진다, 느헤미야가 고개 숙여 감사한다"]'::jsonb, '[["nehemiah"], ["nehemiah"], ["nehemiah"], ["nehemiah"]]'::jsonb, ARRAY['nehemiah']::text[], '[{"book": "느", "from": "1:1", "to": "1:11"}, {"book": "느", "from": "2:1", "to": "2:8"}]'::jsonb, -445, -445, 'approx', 18, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_exile_return', '147 성벽 재건: 밤의 조사와 한 손엔 무기', '느헤미야는 밤에 성벽을 살핀 뒤 재건을 이끌었고, 백성은 한 손에 돌 한 손에 무기를 들고 성을 세웠다.', '["밤, 느헤미야가 소수와 함께 성벽을 따라 조사한다", "성벽을 재건하는 건축 현장", "건축 현장에서 한 손엔 돌, 한 손엔 무기를 들고 성벽을 세우는 모습", "나팔 소리에 사람들이 모이고, 하나님이 싸우신다는 외침에 모두가 고개를 드는 장면"]'::jsonb, '[["nehemiah"], ["nehemiah"], ["nehemiah"], ["nehemiah"]]'::jsonb, ARRAY['nehemiah']::text[], '[{"book": "느", "from": "2:11", "to": "2:20"}, {"book": "느", "from": "4:10", "to": "4:20"}]'::jsonb, -445, -445, 'approx', 19, '예루살렘', 31.78, 35.22, 'published'),
    ('era_exile_return', '149 율법 낭독: 울음에서 기쁨으로', '말씀이 낭독되자 백성은 울고, 지도자들은 ‘기쁨이 힘’이라 격려한다.', '["에스라가 군중들에게 두루마리를 선포하는 장면", "말씀을 듣고 사람들이 기뻐서 우는 장면", "느헤미야가 울지 말라고 백성들을 다독이는 장면", "에스라와 느헤미야와 백성들이 음식을 나누며 기뻐하는 장면"]'::jsonb, '[["ezra"], [], ["nehemiah"], ["ezra", "nehemiah"]]'::jsonb, ARRAY['ezra', 'nehemiah']::text[], '[{"book": "느", "from": "8:1", "to": "8:12"}]'::jsonb, -444, -444, 'approx', 20, '예루살렘 수문 앞 광장(전승)', 31.78, 35.23, 'published'),
    ('era_exile_return', '150 언약 갱신: 다시 서명하다', '공동체는 죄를 고백하고 서약하며 새로운 질서를 세운다.', '["사람들이 금식하며 머리를 숙인다, 재를 뒤집어쓴 모습", "긴 고백 기도, 과거의 이야기들이 흘러간다", "지도자들이 문서에 서명한다, 붓 끝이 떨린다", "사람들의 얼굴이 조금씩 밝아진다, 다시 시작이 선언된다"]'::jsonb, '[["nehemiah"], ["nehemiah"], ["nehemiah"], ["nehemiah"]]'::jsonb, ARRAY['nehemiah']::text[], '[{"book": "느", "from": "9:1", "to": "10:39"}]'::jsonb, -444, -444, 'approx', 21, '예루살렘', 31.78, 35.22, 'published'),
    ('era_nt_public_ministry', '151 세례 요한의 탄생 예고', '제사장 사가랴에게 천사가 나타나 세례 요한의 탄생을 알린다.', '["성전 안, 사가랴가 향을 사르며 조용히 서 있다", "갑자기 빛, 가브리엘이 나타나 사가랴가 굳어 선다", "놀람이 번진다", "사가랴가 말을 못하게 되고, 밖에 나온 그는 손짓만 한다"]'::jsonb, '[[], ["gabriel"], [], []]'::jsonb, ARRAY['zechariah', 'gabriel', 'elizabeth']::text[], '[{"book": "눅", "from": "1:5", "to": "1:25"}]'::jsonb, 5, 5, 'approx', 1, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_nt_public_ministry', '152 마리아 수태고지와 찬양', '마리아는 천사의 소식을 받고 엘리사벳을 찾아가 찬양한다.', '["나사렛의 집, 가브리엘이 결연한 표정으로 선다", "마리아가 조용히 고개를 끄덕인다", "마리아가 길을 떠나 유대 산지로 달려간다", "마리아와 엘리사벳이 결연한 표정으로 선다"]'::jsonb, '[["gabriel"], ["mary"], ["mary"], ["mary", "elizabeth"]]'::jsonb, ARRAY['mary', 'gabriel', 'elizabeth']::text[], '[{"book": "눅", "from": "1:26", "to": "1:56"}]'::jsonb, 5, 5, 'approx', 2, '나사렛 → 유대 산지(전승)', 32.7, 35.303, 'published'),
    ('era_nt_public_ministry', '153 예수 탄생과 목자들', '베들레헴에서 예수님이 태어나고 목자들이 기쁜 소식을 듣는다.', '["인구조사로 붐비는 베들레헴, 요셉과 마리아가 자리를 찾지 못한다", "조용한 밤, 아기가 태어나 구유에 눕혀진다", "들판의 목자들 앞에 천사가 나타나 천사가 나타나고 목자들이 놀라 눈을 들어 올린다", "목자들이 급히 달려와 아기를 보고, 돌아가며 소문을 퍼뜨린다"]'::jsonb, '[["mary", "joseph"], [], [], []]'::jsonb, ARRAY['jesus', 'mary', 'joseph']::text[], '[{"book": "눅", "from": "2:1", "to": "2:20"}]'::jsonb, 4, 4, 'approx', 3, '베들레헴', 31.705, 35.202, 'published'),
    ('era_nt_public_ministry', '154 동방박사와 피신', '동방박사가 경배하고, 헤롯의 위협으로 가족은 애굽으로 피신한다.', '["예루살렘 궁정, 별 이야기에 헤롯의 얼굴이 굳는다", "베들레헴의 집, 박사들이 예물을 드리며 경배한다", "꿈에서 경고를 받고 박사들이 다른 길로 돌아간다", "요셉이 급히 가족을 깨워 밤길로 애굽을 향해 떠난다"]'::jsonb, '[[], [], [], ["joseph"]]'::jsonb, ARRAY['jesus', 'mary', 'joseph', 'herod']::text[], '[{"book": "마", "from": "2:1", "to": "2:15"}]'::jsonb, 4, 4, 'approx', 4, '예루살렘 → 베들레헴 → 애굽(전승)', 31.778, 35.222, 'published'),
    ('era_nt_public_ministry', '155 어린 예수의 성전 사건', '소년 예수는 성전에서 율법교사들과 대화하며 자신의 정체를 드러낸다.', '["유월절 후 귀가 행렬 속, 마리아가 예수를 찾다가 멈칫한다", "부모가 예루살렘으로 되돌아가 급히 찾아다닌다", "성전 안, 예수가 교사들과 질문·대답을 나누고 모두가 놀란다", "예수 앞쪽에 서 있고, 부모가 말없이 바라본다"]'::jsonb, '[["mary", "jesus"], [], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus', 'mary', 'joseph']::text[], '[{"book": "눅", "from": "2:41", "to": "2:52"}]'::jsonb, 8, 8, 'approx', 5, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_nt_public_ministry', '156 예수의 세례', '예수님이 세례를 받으실 때 하늘의 음성과 표징이 나타난다.', '["요단강가, 요한이 사람들을 세례 주는 가운데 예수가 앞으로 나온다", "요한이 망설이자 예수가 조용히 고개를 끄덕인다", "물에서 올라오는 순간 하늘이 열리는 듯한 빛이 비친다", "하늘에서 빛이 비치고, 사람들이 숨을 삼킨다"]'::jsonb, '[["jesus", "john_the_baptist"], ["jesus", "john_the_baptist"], [], []]'::jsonb, ARRAY['jesus', 'john_the_baptist']::text[], '[{"book": "마", "from": "3:13", "to": "3:17"}, {"book": "막", "from": "1:9", "to": "1:11"}, {"book": "눅", "from": "3:21", "to": "3:22"}, {"book": "요", "from": "1:29", "to": "1:34"}]'::jsonb, 27, 27, 'approx', 6, '요단강(여리고 근처, 전승)', 31.85, 35.55, 'published'),
    ('era_nt_public_ministry', '157 광야 시험', '예수님은 광야에서 유혹을 말씀으로 이기며 사명의 방향을 확정하신다.', '["끝없는 광야, 예수가 지친 얼굴로 걷다가 멈춘다", "예수님이 조용히 고개를 끄덕인다", "높은 곳의 시험, 예수는 흔들리지 않는다", "유혹이 물러가고, 고요 속에 예수가 다시 길을 나선다"]'::jsonb, '[["jesus"], ["jesus"], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "마", "from": "4:1", "to": "4:11"}, {"book": "막", "from": "1:12", "to": "1:13"}, {"book": "눅", "from": "4:1", "to": "4:13"}]'::jsonb, 27, 27, 'approx', 7, '유대 광야(전승)', 31.75, 35.3, 'published'),
    ('era_nt_public_ministry', '158 제자 부르심: 그물을 버리다', '예수님은 어부들을 부르시고 그들은 삶의 방향을 바꾼다.', '["호숫가, 그물을 손질하는 어부들, 예수가 다가온다", "베드로가 멈칫한다", "배가 뒤로 밀리며 그물이 가득하다", "그들이 그물을 내려놓고 예수를 따라 길을 걷는다"]'::jsonb, '[["jesus"], ["peter"], [], ["jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james', 'john']::text[], '[{"book": "막", "from": "1:16", "to": "1:20"}, {"book": "마", "from": "4:18", "to": "4:22"}, {"book": "눅", "from": "5:1", "to": "5:11"}, {"book": "요", "from": "1:35", "to": "1:51"}]'::jsonb, 27, 27, 'approx', 8, '갈릴리 호수(가버나움 근처)', 32.88, 35.57, 'published'),
    ('era_nt_public_ministry', '159 산상수훈: 복 있는 사람', '예수님은 하나님 나라의 새로운 가치와 삶의 기준을 선포하신다.', '["산비탈에 사람들이 모여 앉고, 예수가 자리에 앉는다", "복이 있나니, 선포가 이어지고 사람들의 표정이 바뀐다", "너희는 빛이라 말하며 예수가 손으로 도시를 가리킨다", "반석 위에 집을 짓는 자 비유로 마무리되고 군중이 놀란다"]'::jsonb, '[["jesus"], [], ["jesus"], []]'::jsonb, ARRAY['jesus']::text[], '[{"book": "마", "from": "5:1", "to": "7:29"}]'::jsonb, 28, 28, 'approx', 9, '갈릴리 산지(전승)', 32.85, 35.55, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_persons,
  s.person_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_persons = excluded.scene_persons,
  person_codes = excluded.person_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_public_ministry', '160 폭풍을 잠잠케 하심', '두려움 속 제자들 앞에서 예수님은 바람과 물결을 잠잠케 하신다.', '["배 위, 폭풍이 몰아치고 제자들이 물을 퍼낸다", "제자들이 두 손을 들어 다급하게 몸짓한다", "예수님이 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "제자들이 서로를 바라본다, 두려움과 놀람이 엇갈린다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "4:35", "to": "4:41"}, {"book": "마", "from": "8:23", "to": "8:27"}, {"book": "눅", "from": "8:22", "to": "8:25"}]'::jsonb, 28, 28, 'approx', 10, '갈릴리 호수', 32.83, 35.59, 'published'),
    ('era_nt_public_ministry', '161 야이로의 딸과 혈루증 여인', '절박한 믿음이 이어지는 길 위에서 예수님은 치유와 생명의 능력을 보이신다.', '["야이로가 무릎 꿇고 간청한다", "군중 속 여인이 예수의 옷자락을 만지고 멈춘다", "예수 앞쪽에 서 있고, 여인이 울며 고개 숙인다", "집에 도착해 달리다굼이 울리고, 아이가 일어나는 순간 모두가 숨을 삼킨다"]'::jsonb, '[[], ["jesus"], ["jesus"], []]'::jsonb, ARRAY['jesus', 'jairus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "5:21", "to": "5:43"}, {"book": "마", "from": "9:18", "to": "9:26"}, {"book": "눅", "from": "8:40", "to": "8:56"}]'::jsonb, 28, 28, 'approx', 11, '가버나움(전승)', 32.88, 35.57, 'published'),
    ('era_nt_public_ministry', '162 오병이어', '작은 나눔이 시작점이 되어 많은 사람이 먹고 남는다.', '["제자들이 결연한 표정으로 선다", "제자들이 당황한다", "떡과 물고기가 들려오고, 예수가 축사하며 떼어 준다", "사람들이 배부르고 바구니가 쌓인다, 제자들이 말없이 서로를 본다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "6:34", "to": "6:44"}, {"book": "마", "from": "14:13", "to": "14:21"}, {"book": "눅", "from": "9:10", "to": "9:17"}, {"book": "요", "from": "6:1", "to": "6:13"}]'::jsonb, 29, 29, 'approx', 12, '갈릴리 호숫가 들판(전승)', 32.84, 35.54, 'published'),
    ('era_nt_public_ministry', '163 변화산', '예수님의 영광이 드러나고 제자들은 ‘그의 말을 들으라’는 음성을 듣는다.', '["예수와 세 제자가 산을 오르며 숨을 고른다", "예수의 모습이 빛나고, 모세와 엘리야가 함께 선다", "베드로가 결연한 표정으로 선다", "하늘에서 빛이 비치고, 제자들이 엎드린다"]'::jsonb, '[["jesus"], ["moses", "elijah", "jesus"], ["peter"], []]'::jsonb, ARRAY['jesus', 'peter', 'james', 'john', 'moses', 'elijah']::text[], '[{"book": "막", "from": "9:2", "to": "9:13"}, {"book": "마", "from": "17:1", "to": "17:13"}, {"book": "눅", "from": "9:28", "to": "9:36"}]'::jsonb, 29, 29, 'approx', 13, '변화산(전승, 다볼/헤르몬 견해)', 33.417, 35.857, 'published'),
    ('era_nt_public_ministry', '164 베드로의 고백과 수난 예고', '베드로의 고백 이후 예수님은 십자가의 길을 처음으로 분명히 예고하신다.', '["제자들이 멈춘다", "베드로가 앞쪽에 서 있고, 공기가 바뀐다", "예수님과 베드로가 함께 서서 서로를 바라본다", "제자들이 충격에 잠긴다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter"], ["jesus", "peter"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "8:27", "to": "8:33"}, {"book": "마", "from": "16:13", "to": "16:23"}, {"book": "눅", "from": "9:18", "to": "9:22"}]'::jsonb, 29, 29, 'approx', 14, '가이사랴 빌립보', 33.248, 35.694, 'published'),
    ('era_nt_public_ministry', '165 비유: 선한 사마리아인', '예수님은 이웃의 의미를 ‘경계 밖의 자비’로 재정의하신다.', '["배경과 분위기만 보이는 앞쪽에 서 있고, 내 이웃이 누구입니까?", "길가에 쓰러진 사람, 제사장과 레위인이 지나친다", "사마리아인이 멈추어 상처를 싸매고 짐승에 태운다", "예수 앞쪽에 서 있고, 교사가 말문이 막힌다"]'::jsonb, '[[], [], [], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "눅", "from": "10:25", "to": "10:37"}]'::jsonb, 30, 30, 'approx', 15, '예루살렘-여리고 길(전승)', 31.8, 35.4, 'published'),
    ('era_nt_public_ministry', '166 비유: 탕자의 귀환', '잃은 아들을 맞이하는 아버지의 품이 하나님 나라의 심장을 드러낸다.', '["아들이 집을 나가 돈을 쥐고 달아난다, 흥분", "먼 나라, 빈손이 된 아들이 돼지우리 옆에서 고개를 떨군다", "집으로 돌아오는 길, 아버지가 달려가 껴안는다", "배경과 분위기만 보이는"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['jesus']::text[], '[{"book": "눅", "from": "15:11", "to": "15:32"}]'::jsonb, 30, 30, 'approx', 16, '베레아(요단 동편, 추정)', 31.93, 35.62, 'published'),
    ('era_nt_public_ministry', '167 나사로의 부활', '예수님은 ‘나는 부활이요 생명’이라 하시며 나사로를 일으키신다.', '["배경과 분위기만 보이는", "예수 앞쪽에 서 있고, 마르다의 눈이 흔들린다", "예수님이 두 손을 들어 다급하게 몸짓한다", "나사로가 걸어 나오고 군중이 얼어붙는다"]'::jsonb, '[[], ["jesus"], ["jesus"], []]'::jsonb, ARRAY['jesus', 'lazarus', 'martha', 'mary']::text[], '[{"book": "요", "from": "11:1", "to": "11:44"}]'::jsonb, 32, 32, 'approx', 17, '베다니', 31.774, 35.263, 'published'),
    ('era_nt_public_ministry', '168 예루살렘 입성', '예수님은 겸손한 왕으로 입성하시고 군중은 환호한다.', '["감람산 길, 제자들이 나귀를 끌고 온다", "예수가 나귀를 타고 내려오자 군중이 옷과 가지를 펼친다", "호산나!, 환호가 퍼지고 종교 지도자들의 눈빛이 굳는다", "예수가 성을 바라보며 잠깐 멈춘다, 분위기가 바뀐다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], [], ["jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "11:1", "to": "11:11"}, {"book": "마", "from": "21:1", "to": "21:11"}, {"book": "눅", "from": "19:28", "to": "19:40"}, {"book": "요", "from": "12:12", "to": "12:19"}]'::jsonb, 33, 33, 'approx', 18, '예루살렘', 31.778, 35.222, 'published'),
    ('era_nt_public_ministry', '169 성전 정화', '예수님은 성전을 ‘기도의 집’으로 회복시키려 하신다.', '["성전 뜰, 거래 소리와 동전 소리가 가득하다", "예수가 분명한 손짓으로 흐름을 멈춘다, 사람들의 놀란 얼굴", "내 집은 기도하는 집 선언에 분위기가 얼어붙는다", "지도자들이 멀리서 이를 갈며 서로 눈짓한다"]'::jsonb, '[[], ["jesus"], [], []]'::jsonb, ARRAY['jesus']::text[], '[{"book": "막", "from": "11:15", "to": "11:19"}, {"book": "마", "from": "21:12", "to": "21:17"}, {"book": "눅", "from": "19:45", "to": "19:48"}, {"book": "요", "from": "2:13", "to": "2:17"}]'::jsonb, 33, 33, 'approx', 19, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_nt_public_ministry', '170 최후의 만찬', '예수님은 떡과 잔으로 새 언약을 세우시고 배신을 예고하신다.', '["다락방에 둘러앉은 제자들, 예수가 조용히 떡을 든다", "배경과 분위기만 보이는", "예수님이 결연한 표정으로 선다", "유다가 자리에서 일어나 나가고, 문이 닫히며 방 안이 무거워진다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas", "jesus"], [], ["jesus"], ["judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "14:12", "to": "14:26"}, {"book": "마", "from": "26:17", "to": "26:30"}, {"book": "눅", "from": "22:7", "to": "22:23"}, {"book": "요", "from": "13:1", "to": "13:30"}]'::jsonb, 33, 33, 'approx', 20, '예루살렘 다락방(전승)', 31.776, 35.233, 'published'),
    ('era_nt_public_ministry', '171 겟세마네: 뜻이 이루어지다', '예수님은 고뇌 속에서 아버지의 뜻에 자신을 맡기신다.', '["밤의 감람산, 예수님이 결연한 표정으로 선다", "예수가 홀로 무릎 꿇고 기도한다, 숨소리가 거칠다", "제자들이 잠든 모습을 보고 예수가 조용히 흔든다", "예수님이 결연한 표정으로 선다"]'::jsonb, '[["jesus"], ["jesus"], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'james', 'john']::text[], '[{"book": "막", "from": "14:32", "to": "14:42"}, {"book": "마", "from": "26:36", "to": "26:46"}, {"book": "눅", "from": "22:39", "to": "22:46"}]'::jsonb, 33, 33, 'approx', 21, '겟세마네(감람산)', 31.78, 35.24, 'published'),
    ('era_nt_public_ministry', '172 체포: 배신의 입맞춤', '유다의 배신으로 예수님이 체포되고 제자들은 흩어진다.', '["횃불과 무장한 무리가 숲길로 들어온다", "유다가 다가와 입맞춤한다, 예수의 눈빛이 흔들리지 않는다", "제자들이 소란에 휩싸이고 누군가 칼을 휘두른다, 직접 묘사 최소", "예수가 묶여 끌려가고 제자들은 어둠 속으로 흩어진다"]'::jsonb, '[[], ["judas", "jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas", "jesus"]]'::jsonb, ARRAY['jesus', 'judas', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot']::text[], '[{"book": "막", "from": "14:43", "to": "14:52"}, {"book": "마", "from": "26:47", "to": "26:56"}, {"book": "눅", "from": "22:47", "to": "22:53"}, {"book": "요", "from": "18:1", "to": "18:11"}]'::jsonb, 33, 33, 'approx', 22, '겟세마네(감람산)', 31.78, 35.24, 'published'),
    ('era_nt_public_ministry', '173 재판: 빌라도 앞', '예수님은 불의한 재판을 받으시고 침묵 속에서 길을 걸으신다.', '["빌라도 앞, 고발이 쏟아지고 예수는 잠깐 고개를 든다", "배경과 분위기만 보이는", "배경과 분위기만 보이는", "빌라도가 손을 씻는 제스처, 예수에게 판결이 내려진다"]'::jsonb, '[["jesus"], [], [], ["jesus"]]'::jsonb, ARRAY['jesus', 'pilate']::text[], '[{"book": "막", "from": "15:1", "to": "15:15"}, {"book": "마", "from": "27:11", "to": "27:26"}, {"book": "눅", "from": "23:1", "to": "23:25"}, {"book": "요", "from": "18:28", "to": "19:16"}]'::jsonb, 33, 33, 'approx', 23, '예루살렘(총독 관저, 전승)', 31.778, 35.225, 'published'),
    ('era_nt_public_ministry', '174 십자가: 끝까지 사랑', '예수님은 십자가에서 마지막까지 사랑을 드러내신다.', '["언덕으로 오르는 행렬, 하늘이 점점 어두워지는 톤", "십자가가 세워지고, 주변은 조롱과 침묵이 엇갈린다, 직접 묘사 최소", "예수의 마지막 말들이 남는다, 다 이루었다", "예수님이 휘장이 찢어졌다는 소식, 백부장이 고개 숙인다"]'::jsonb, '[[], [], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "막", "from": "15:21", "to": "15:39"}, {"book": "마", "from": "27:32", "to": "27:54"}, {"book": "눅", "from": "23:26", "to": "23:49"}, {"book": "요", "from": "19:17", "to": "19:37"}]'::jsonb, 33, 33, 'approx', 24, '골고다(예루살렘)', 31.778, 35.229, 'published'),
    ('era_nt_public_ministry', '175 부활과 승천: 새 시작', '부활하신 예수님은 제자들에게 사명을 주시고 승천하신다.', '["새벽 무덤, 돌이 옮겨져 있고 여인들이 멈춰 선다", "예수님이 결연한 표정으로 선다", "예수가 제자들에게 사명을 준다, 땅 끝까지 증인이 되라", "감람산에서 승천, 제자들이 하늘을 바라보며 서 있다"]'::jsonb, '[[], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot"]]'::jsonb, ARRAY['jesus', 'mary_magdalene', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot']::text[], '[{"book": "마", "from": "28:1", "to": "28:20"}, {"book": "눅", "from": "24:1", "to": "24:53"}, {"book": "요", "from": "20:1", "to": "20:29"}, {"book": "행", "from": "1:1", "to": "1:11"}]'::jsonb, 33, 33, 'approx', 25, '예루살렘(무덤) → 감람산(전승)', 31.78, 35.24, 'published'),
    ('era_nt_apostolic', '176 오순절: 성령강림', '성령이 임하며 교회의 시대가 힘 있게 시작된다.', '["다락방, 사람들이 기도하며 숨죽인 채 기다린다", "갑자기 큰 바람 같은 소리, 모두가 놀라 고개를 든다", "불의 혀 같은 것이 나타나 머물고, 각기 다른 말이 터져 나온다", "밖의 군중이 몰려든다, 무슨 일이냐?, 웅성거림이 커진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'matthias']::text[], '[{"book": "행", "from": "2:1", "to": "2:13"}]'::jsonb, 33, 33, 'approx', 1, '예루살렘', 31.778, 35.222, 'published'),
    ('era_nt_apostolic', '177 베드로 설교: 하루에 삼천', '베드로의 설교로 많은 사람이 회개하고 공동체가 태어난다.', '["군중 앞에 선 베드로, 두려움 대신 담대함이 얼굴에 있다", "이 예수를 하나님이 주와 그리스도가 되게 하셨다가 울린다", "배경과 분위기만 보이는", "물가에서 세례가 이어지고, 떡을 떼는 공동체 앞쪽에 서 있고, 으로 전환된다"]'::jsonb, '[["peter"], [], [], []]'::jsonb, ARRAY['peter']::text[], '[{"book": "행", "from": "2:14", "to": "2:47"}]'::jsonb, 33, 33, 'approx', 2, '예루살렘', 31.778, 35.222, 'published'),
    ('era_nt_apostolic', '178 성전 미문 치유와 첫 박해', '치유로 군중이 모이고, 지도자들은 사도들을 막기 시작한다.', '["성전 문, 앉은 사람이 손을 내민다, 베드로가 멈춰 선다", "나사렛 예수 이름으로 일어나 걸어라, 사람이 벌떡 일어선다", "군중이 몰려들고 베드로가 예수를 증거한다", "관리들이 들이닥쳐 사도들을 붙잡는다, 밤이 깊어간다"]'::jsonb, '[["peter"], [], ["peter"], []]'::jsonb, ARRAY['peter', 'john']::text[], '[{"book": "행", "from": "3:1", "to": "3:26"}, {"book": "행", "from": "4:1", "to": "4:22"}]'::jsonb, 33, 33, 'approx', 3, '예루살렘 성전 미문', 31.778, 35.235, 'published'),
    ('era_nt_apostolic', '179 아나니아와 삽비라', '거짓은 공동체를 흔들고, 사건은 거룩함의 경고가 된다.', '["아나니아가 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "베드로가 상대를 바라보며 기다린다", "충격이 퍼지고 회중이 얼어붙는다, 직접 묘사 최소", "삽비라가 들어오고 같은 질문이 반복되며 두려움이 공동체를 덮는다"]'::jsonb, '[["ananias"], ["peter"], [], []]'::jsonb, ARRAY['ananias', 'sapphira', 'peter']::text[], '[{"book": "행", "from": "5:1", "to": "5:11"}]'::jsonb, 34, 34, 'approx', 4, '예루살렘', 31.778, 35.222, 'published'),
    ('era_nt_apostolic', '180 일곱 집사와 스데반 순교', '섬김의 구조가 세워지고, 스데반의 죽음은 흩어짐의 불씨가 된다.', '["구제 문제로 다툼이 생기고 사도들이 일곱 사람을 세운다", "배경과 분위기만 보이는", "분노가 폭발하고 스데반이 하늘을 바라본다, 직접 묘사 최소", "사울이 그 광경을 지켜본다, 그의 눈빛이 단단해진다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "matthias"], [], [], ["saul"]]'::jsonb, ARRAY['stephen', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'matthias', 'saul']::text[], '[{"book": "행", "from": "6:1", "to": "6:7"}, {"book": "행", "from": "7:54", "to": "8:1"}]'::jsonb, 35, 35, 'approx', 5, '예루살렘', 31.778, 35.222, 'published'),
    ('era_nt_apostolic', '181 사마리아 복음: 빌립의 전도', '박해로 흩어진 자리에서 복음은 사마리아까지 확장된다.', '["사람들이 짐을 싸며 흩어진다, 도시마다 소문이 번진다", "빌립이 사마리아에서 복음을 전하고 사람들이 몰려든다", "기쁨이 도시를 채우고, 사도들이 내려와 기도한다", "새 공동체가 세워지고 경계가 허물어짐을 암시한다"]'::jsonb, '[[], ["philip"], [], []]'::jsonb, ARRAY['philip']::text[], '[{"book": "행", "from": "8:4", "to": "8:25"}]'::jsonb, 35, 35, 'approx', 6, '사마리아', 32.28, 35.19, 'published'),
    ('era_nt_apostolic', '182 에티오피아 내시: 길 위의 만남', '한 사람의 질문이 길 위에서 답을 만나고, 복음은 더 먼 곳으로 간다.', '["얼굴에 의문이 가득하다", "빌립이 상대를 바라보며 기다린다", "물가에서 세례, 내시가 환하게 웃는다", "내시가 기쁨으로 길을 가고, 빌립은 다른 곳으로 인도된다"]'::jsonb, '[[], ["philip"], [], ["philip"]]'::jsonb, ARRAY['philip']::text[], '[{"book": "행", "from": "8:26", "to": "8:40"}]'::jsonb, 35, 35, 'approx', 7, '예루살렘-가사 길(전승)', 31.5, 34.47, 'published'),
    ('era_nt_apostolic', '183 사울 회심: 다메섹의 빛', '박해자 사울은 부르심을 만나고 방향이 완전히 바뀐다.', '["사울이 공문을 들고 다메섹으로 달린다, 눈빛이 날카롭다", "강한 빛이 비치고 사울이 쓰러진다, 사울아, 네가 어찌하여", "눈먼 사울이 손에 이끌려 들어간다, 도시가 낯설어진다", "아나니아가 안수하자 사울이 다시 보고, 조용히 일어난다"]'::jsonb, '[["saul"], ["saul"], ["saul"], ["saul", "ananias"]]'::jsonb, ARRAY['saul', 'ananias']::text[], '[{"book": "행", "from": "9:1", "to": "9:19"}]'::jsonb, 35, 35, 'approx', 8, '다메섹', 33.51, 36.29, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_persons,
  s.person_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_persons = excluded.scene_persons,
  person_codes = excluded.person_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_apostolic', '184 고넬료: 이방인에게도', '베드로는 편견을 넘어 이방인에게도 성령이 임함을 목격한다.', '["고넬료가 기도하다 환상을 보고 사람을 보낸다", "베드로가 환상 속 천을 보고 멈칫한다", "베드로가 결연한 표정으로 선다", "성령의 표징에 모두가 놀란다, 베드로가 고개를 끄덕인다"]'::jsonb, '[[], ["peter"], ["peter"], ["peter"]]'::jsonb, ARRAY['peter', 'cornelius']::text[], '[{"book": "행", "from": "10:1", "to": "10:48"}, {"book": "행", "from": "11:1", "to": "11:18"}]'::jsonb, 38, 38, 'approx', 9, '가이사랴', 32.5, 34.89, 'published'),
    ('era_nt_apostolic', '185 안디옥 교회: 선교의 출발', '안디옥 교회는 금식과 기도 가운데 바울과 바나바를 파송한다.', '["금식과 기도 중 공동체가 조용히 고개를 든다", "따로 세우라는 인도에 모두가 숨을 삼킨다", "안수 앞쪽에 서 있고, 바울과 바나바가 서로를 바라본다", "배가 있는 항구를 향해 걸어 나간다"]'::jsonb, '[[], [], ["barnabas", "paul"], []]'::jsonb, ARRAY['barnabas', 'paul']::text[], '[{"book": "행", "from": "13:1", "to": "13:3"}]'::jsonb, 46, 46, 'approx', 10, '안디옥(시리아)', 36.202, 36.16, 'published'),
    ('era_nt_apostolic', '186 1차 선교(1): 구브로 살라미–바보', '바울과 바나바는 구브로에서 복음을 전하며 첫 여정을 시작한다.', '["배가 항구에 닿고, 회당으로 향하는 발걸음이 빠르다", "반대와 긴장이 오가지만, 복음이 선포된다", "분위기가 뒤집히는 순간, 총독의 표정이 달라진다", "바울이 지도를 펼치며 다음 목적지를 가리킨다"]'::jsonb, '[[], [], [], ["paul"]]'::jsonb, ARRAY['paul', 'barnabas', 'john_mark']::text[], '[{"book": "행", "from": "13:4", "to": "13:12"}]'::jsonb, 46, 46, 'approx', 11, '구브로(살라미 → 바보)', 34.775, 32.424, 'published'),
    ('era_nt_apostolic', '187 1차 선교(2): 비시디아 안디옥', '바울은 회당에서 설교하고, 복음은 이방인에게 크게 확장된다.', '["회당, 사람들이 바울의 말을 기다리며 숨죽인다", "설교 후 이방인들이 기뻐하며 몰려든다", "반대가 커지고 도시의 공기가 갈라진다", "두 사람은 먼지를 털고 다음 도시로 떠난다"]'::jsonb, '[["paul"], [], [], []]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "13:13", "to": "13:52"}]'::jsonb, 46, 46, 'approx', 12, '비시디아 안디옥(소아시아)', 38.35, 31.18, 'published'),
    ('era_nt_apostolic', '188 1차 선교(3): 이고니온', '표적과 논쟁이 함께 일어나고, 박해의 조짐이 짙어진다.', '["많은 사람이 믿지만, 반대가 조직적으로 커진다", "두 사람이 서로 눈빛을 맞추고 도시를 떠날 결심을 한다"]'::jsonb, '[[], []]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:1", "to": "14:7"}]'::jsonb, 47, 47, 'approx', 13, '이고니온(코니아)', 37.874, 32.493, 'published'),
    ('era_nt_apostolic', '189 1차 선교(4): 루스드라–더베', '루스드라와 더베에서 전도가 이어지지만, 폭력적 박해도 뒤따른다.', '["군중의 열기가 오르며 상황이 급변한다, 긴장", "바울이 상처를 안고도 다시 일어나 다음 도시로 걷는다"]'::jsonb, '[[], ["paul"]]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:8", "to": "14:20"}]'::jsonb, 47, 47, 'approx', 14, '루스드라 → 더베(갈라디아)', 37.58, 32.28, 'published'),
    ('era_nt_apostolic', '190 1차 선교(5): 안디옥(시리아)로 귀환 보고', '1차 여행을 마치고 돌아와 하나님이 하신 일을 교회에 보고한다.', '["안디옥 교회에 모인 사람들, 바울이 숨을 고르고 말문을 연다", "이방인에게 믿음의 문이 열렸다는 보고에 모두가 놀라 미소 짓는다"]'::jsonb, '[["paul"], []]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:21", "to": "14:28"}]'::jsonb, 48, 48, 'approx', 15, '안디옥(시리아)', 36.202, 36.16, 'published'),
    ('era_nt_apostolic', '191 2차 선교(1): 드로아에서 마게도냐로', '드로아에서 ‘마게도냐로 건너오라’는 인도를 받고 방향이 바뀐다.', '["밤의 환상, 바울이 벌떡 일어나 지도를 펼친다", "배가 바다를 건너며 유럽 선교의 문이 열린다"]'::jsonb, '[["paul"], []]'::jsonb, ARRAY['paul', 'silas', 'timothy']::text[], '[{"book": "행", "from": "16:6", "to": "16:10"}]'::jsonb, 49, 49, 'approx', 16, '드로아', 39.812, 26.173, 'published'),
    ('era_nt_apostolic', '192 2차 선교(2): 빌립보—루디아와 감옥의 찬양', '빌립보에서 복음은 가정과 감옥 한복판까지 스며든다.', '["강가에서 루디아가 마음이 열리고 집 문이 열린다", "한밤중 찬양, 큰 흔들림, 과 문이 열리는", "배경과 분위기만 보이는", "집에서 세례와 식탁, 두려움이 기쁨으로 바뀐다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['paul', 'silas', 'timothy', 'lydia']::text[], '[{"book": "행", "from": "16:11", "to": "16:34"}]'::jsonb, 50, 50, 'approx', 17, '빌립보', 41.012, 24.286, 'published'),
    ('era_nt_apostolic', '193 2차 선교(3): 데살로니가—소동과 도피', '데살로니가에서 복음이 퍼지자 반대가 폭동으로 번진다.', '["회당의 논쟁이 길어지고, 거리의 소문이 커진다", "밤에 형제들이 바울 일행을 급히 피신시킨다"]'::jsonb, '[[], ["paul"]]'::jsonb, ARRAY['paul', 'silas', 'timothy']::text[], '[{"book": "행", "from": "17:1", "to": "17:9"}]'::jsonb, 50, 50, 'approx', 18, '데살로니가', 40.64, 22.944, 'published'),
    ('era_nt_apostolic', '194 2차 선교(4): 베뢰아—말씀을 상고하다', '베뢰아 사람들은 말씀을 상고하며 복음을 받아들인다.', '["사람들이 두루마리를 펼쳐 확인한다, 고개를 끄덕인다", "데살로니가에서 온 방해 소식에 바울이 홀로 떠날 준비를 한다"]'::jsonb, '[[], ["paul"]]'::jsonb, ARRAY['paul', 'silas', 'timothy']::text[], '[{"book": "행", "from": "17:10", "to": "17:15"}]'::jsonb, 50, 50, 'approx', 19, '베뢰아', 40.523, 22.203, 'published'),
    ('era_nt_apostolic', '195 2차 선교(5): 아덴—아레오바고 설교', '바울은 ‘알지 못하는 신’ 제단을 출발점으로 창조주와 부활을 선포한다.', '["우상으로 가득한 거리, 바울이 멈춰 깊게 숨을 쉰다", "배경과 분위기만 보이는", "바울이 부활을 말하자 어떤 이는 비웃고 어떤 이는 더 듣겠다고 남는다", "바울이 조용히 도시를 떠난다, 다음 목적지가 열린다"]'::jsonb, '[["paul"], [], ["paul"], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "17:16", "to": "17:34"}]'::jsonb, 51, 51, 'approx', 20, '아덴(아레오바고)', 37.972, 23.725, 'published'),
    ('era_nt_apostolic', '196 2차 선교(6): 고린도—정착과 견딤', '고린도에서 바울은 오래 머물며 공동체를 세우고 박해를 견딘다.', '["바울이 아굴라·브리스길라와 함께 일하며 밤엔 가르친다", "재판 자리에서 바울이 침착히 선다, 결국 사건이 흩어진다"]'::jsonb, '[["paul"], ["paul"]]'::jsonb, ARRAY['paul', 'aquila']::text[], '[{"book": "행", "from": "18:1", "to": "18:18"}]'::jsonb, 51, 52, 'approx', 21, '고린도', 37.939, 22.932, 'published'),
    ('era_nt_apostolic', '197 3차 선교(1): 에베소—확장과 충돌', '에베소에서 복음이 크게 확장되며 도시의 질서와도 충돌한다.', '["두란노 서원, 사람들이 오가며 가르침이 퍼진다", "바울이 소동이 벌어지고 에베소 사람의 아데미!, 함성이 극장에 울린다"]'::jsonb, '[[], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "19:1", "to": "19:41"}]'::jsonb, 53, 55, 'approx', 22, '에베소', 37.949, 27.364, 'published'),
    ('era_nt_apostolic', '198 3차 선교(2): 마게도냐—교회를 굳게 하다', '바울은 마게도냐를 돌며 성도들을 격려하고 공동체를 세운다.', '["바울이 여러 도시를 지나며 손을 얹고 격려한다, 여정"]'::jsonb, '[["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "20:1", "to": "20:2"}]'::jsonb, 56, 56, 'approx', 23, '마게도냐(빌립보/데살로니가 권역)', 40.64, 22.944, 'published'),
    ('era_nt_apostolic', '199 3차 선교(3): 헬라(고린도)—머무름과 결심', '바울은 헬라에서 머물며 다음 행선과 위험을 준비한다.', '["바울이 편지를 쓰고, 지도 위에 예루살렘을 표시한다, 결심"]'::jsonb, '[["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "20:2", "to": "20:3"}]'::jsonb, 56, 57, 'approx', 24, '고린도(헬라)', 37.939, 22.932, 'published'),
    ('era_nt_apostolic', '200 3차 선교(4): 밀레도—에베소 장로들과 작별', '바울은 장로들을 불러 눈물로 권면하고 다시는 못 볼지도 모른다고 말한다.', '["해변가 작별, 바울이 결연한 표정으로 선다, 내가 다시 얼굴을 보지 못할지라", "모두가 울며 껴안고, 배가 떠나는 것을 오래 바라본다"]'::jsonb, '[["paul"], []]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "20:17", "to": "20:38"}]'::jsonb, 57, 57, 'approx', 25, '밀레도', 37.53, 27.276, 'published'),
    ('era_nt_apostolic', '201 로마행(1): 예루살렘 체포', '성전 소동으로 바울이 붙잡히며 ‘로마까지’의 여정이 시작된다.', '["군중의 함성, 바울이 붙잡혀 계단으로 끌려간다"]'::jsonb, '[["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "21:27", "to": "21:36"}]'::jsonb, 57, 57, 'approx', 26, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_nt_apostolic', '202 로마행(2): 가이사랴 재판과 상소', '바울은 재판 자리에서 증언하고 ‘가이사에게 상소’한다.', '["재판정, 바울이 결연한 표정으로 선다", "아그립바가 속삭인다, 네가 나를 설득하려 하는구나"]'::jsonb, '[["paul"], []]'::jsonb, ARRAY['paul', 'festus', 'agrippa']::text[], '[{"book": "행", "from": "24:10", "to": "24:27"}, {"book": "행", "from": "25:7", "to": "25:12"}, {"book": "행", "from": "26:1", "to": "26:32"}]'::jsonb, 59, 59, 'approx', 27, '가이사랴', 32.5, 34.89, 'published'),
    ('era_nt_apostolic', '203 로마행(3): 폭풍의 항해', '폭풍 속에서 바울은 ‘두려워 말라’는 약속으로 사람들을 붙든다.', '["파도가 배를 삼킬 듯 흔들고, 사람들은 절망한다", "바울이 결연한 표정으로 선다"]'::jsonb, '[[], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "27:13", "to": "27:26"}]'::jsonb, 59, 59, 'approx', 28, '지중해 항로(그레데 근처, 전승)', 35.2, 25.1, 'published'),
    ('era_nt_apostolic', '204 로마행(4): 멜리데(몰타) 표류', '난파 후 섬에 도착하고, 바울을 통한 표징으로 사람들이 마음을 연다.', '["비와 추위 속, 섬사람들이 불을 피워 준다", "사람들의 시선이 바울에게 모이고, 분위기가 환대로 바뀐다"]'::jsonb, '[[], ["paul"]]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "27:39", "to": "27:44"}, {"book": "행", "from": "28:1", "to": "28:10"}]'::jsonb, 60, 60, 'approx', 29, '몰타(멜리데)', 35.9, 14.51, 'published'),
    ('era_nt_apostolic', '205 로마행(5): 로마 도착', '바울은 로마에 도착해 묶인 상태로도 복음을 전한다.', '["로마의 길, 바울이 쇠사슬을 찬 채 걸어 들어온다", "집에서 사람들을 맞아 담대히 가르친다, 아무도 금하지 못하더라"]'::jsonb, '[["paul"], []]'::jsonb, ARRAY['paul']::text[], '[{"book": "행", "from": "28:14", "to": "28:31"}]'::jsonb, 60, 62, 'approx', 30, '로마', 41.902, 12.496, 'published'),
    ('era_nt_post_apostolic', '206 성전 파괴: 예루살렘의 큰 전환', 'AD 70 예루살렘 성전이 파괴되며 시대의 큰 전환이 일어난다.', '["배경과 분위기만 보이는", "배경과 분위기만 보이는", "도시에서 연기와 붕괴의 소식이 번진다", "폐허를 바라보는 사람들, 역사의 갈림이 조용히 남는다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "마", "from": "24:1", "to": "24:2"}, {"book": "눅", "from": "21:5", "to": "21:6"}]'::jsonb, 70, 70, 'exact', 1, '예루살렘', 31.778, 35.235, 'published'),
    ('era_nt_post_apostolic', '207 밧모섬의 요한: 계시의 시작', '요한은 밧모섬에서 환상 가운데 계시를 받는다.', '["바닷바람 부는 섬, 요한이 홀로 앉아 기도한다", "나팔 소리 같은 큰 음성이 들리고 요한이 뒤돌아본다", "빛나는 환상, 요한이 두려움에 엎드린다", "기록하여 보내라 명령에 요한이 두루마리를 붙잡는다"]'::jsonb, '[["john"], ["john"], ["john"], ["john"]]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "1:9", "to": "1:20"}]'::jsonb, 95, 95, 'approx', 2, '밧모섬', 37.31, 26.55, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_persons,
  s.person_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_persons = excluded.scene_persons,
  person_codes = excluded.person_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_post_apostolic', '208 일곱 교회 편지: 촛대 사이의 말씀', '일곱 교회에 칭찬과 책망, 약속이 전달된다.', '["요한이 편지를 쓰기 시작한다, 촛불이 흔들린다", "처음 사랑을 버렸다 같은 말이 떨어지고 요한이 잠깐 멈춘다", "이기는 자에게 약속이 이어진다, 희망의 톤이 스친다", "편지가 봉해지고 사자가 길을 떠난다, 전달의"]'::jsonb, '[["john"], ["john"], [], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "2:1", "to": "3:22"}]'::jsonb, 95, 95, 'approx', 3, '소아시아(일곱 교회 중심: 에베소)', 37.95, 27.37, 'published'),
    ('era_nt_consummation', '209 하늘 보좌: 문이 열리다', '요한은 하늘 보좌의 환상을 보고 경배의 중심을 목격한다.', '["문이 열리는 듯한", "보좌와 무지개 같은 빛, 번개와 음성이 울린다", "생물들이 거룩하다를 반복하고 요한이 숨을 삼킨다", "배경과 분위기만 보이는"]'::jsonb, '[[], [], ["john"], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "4:1", "to": "4:11"}]'::jsonb, null, null, 'approx', 1, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_consummation', '210 어린양: 두루마리를 받다', '어린양이 두루마리를 받아 역사의 열쇠를 여는 존재로 드러난다.', '["봉인된 두루마리, 누가 열 수 있는가 질문이 울린다", "요한이 울다가 유다 지파의 사자 소리를 듣고 고개를 든다", "어린양이 보좌 앞으로 나아가 두루마리를 받는다", "하늘의 찬양이 폭발하듯 번지고 경배가 가득 찬다"]'::jsonb, '[[], ["john"], [], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "5:1", "to": "5:14"}]'::jsonb, null, null, 'approx', 2, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_consummation', '211 일곱 인: 역사의 문이 열리다', '봉인이 하나씩 열리며 심판과 경고의 흐름이 전개된다.', '["첫 봉인이 열리고 전개가 시작되는 긴장감", "연속되는 봉인들로 세상이 흔들리는 이미지", "사람들의 질문과 두려움이 커지는", "보호의 표가 강조되며 끝까지 버팀의 톤으로 마무리된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "6:1", "to": "7:17"}]'::jsonb, null, null, 'approx', 3, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_consummation', '212 일곱 나팔: 경고의 울림', '나팔이 울리며 경고가 반복되고 회개의 촉구가 이어진다.', '["하늘의 잠깐 침묵 후, 첫 나팔이 울린다", "땅과 바다에 재앙 이미지가 번진다", "angels가 angels가 두 증인의 앞쪽에 서 있고, 이 스쳐 지나가며 긴장감이 높아진다", "angels가 angels가 angels가 angels가 angels가 angels가 마지막 나팔과 함께 나라가 주의 것이 되었다 선언이 울린다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "8:1", "to": "11:19"}]'::jsonb, null, null, 'approx', 4, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_consummation', '213 용과 두 짐승: 대립의 정점', '거대한 대립이 드러나고, 믿는 자들의 인내가 강조된다.', '["하늘의 전쟁 같은 이미지, 대립이 시작된다", "땅 위에 권세가 등장하며 사람들의 시선이 흔들린다", "표와 충성의 선택이 강조되는", "배경과 분위기만 보이는"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "12:1", "to": "13:18"}]'::jsonb, null, null, 'approx', 5, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_consummation', '214 바벨론의 멸망: 무너지는 화려함', '교만한 체계가 무너지고, 애통과 해방의 대비가 나타난다.', '["화려한 도시 이미지가 등장하고, 사람들의 욕망이 번쩍인다", "배경과 분위기만 보이는", "배경과 분위기만 보이는", "하늘의 기쁨과 땅의 애통이 대비되며 마무리된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "17:1", "to": "17:18"}, {"book": "계", "from": "18:1", "to": "18:24"}]'::jsonb, null, null, 'approx', 6, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_consummation', '215 최후 심판과 새 하늘 새 땅', '심판이 지나고 새 예루살렘과 영원한 회복이 선포된다.', '["큰 보좌 앞에 모두가 서는 앞쪽에 서 있고, 책들이 펼쳐진다", "처음 하늘과 처음 땅이 지나갔다 선언으로 화면이 전환된다", "새 예루살렘이 내려오는 이미지, 빛과 성벽", "눈물을 씻기시니라는 약속과 함께, 밝은 새 아침으로 끝난다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "20:11", "to": "20:15"}, {"book": "계", "from": "21:1", "to": "22:5"}]'::jsonb, null, null, 'approx', 7, '밧모섬(추정)', 37.31, 26.55, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_persons, person_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_persons,
  s.person_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_persons = excluded.scene_persons,
  person_codes = excluded.person_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

commit;
