-- Generated by tools/seed/build_200_stories_seed_sql.py
-- Generated at UTC: 2026-04-27T09:46:32.535371+00:00
-- Target table: events
-- (character_codes / bible_refs / story_scenes / scene_characters live
--  on the events row itself; person_eras and events_ordered are views.)
begin;

-- 시드 INSERT 가 알림 트리거(broadcast)를 깨우는 것 방지. tx 종료 후 자동 복구.
alter table events disable trigger trg_notify_on_new_event;

-- Upsert events from 200 stories
with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_post_apostolic', '성전 파괴: 예루살렘의 큰 전환', 'AD 70 예루살렘 성전이 파괴되며 시대의 큰 전환이 일어난다.', '["배경과 분위기만 보이는", "배경과 분위기만 보이는", "도시에서 연기와 붕괴의 소식이 번진다", "폐허를 바라보는 사람들, 역사의 갈림이 조용히 남는다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "마", "from": "24:1", "to": "24:2"}, {"book": "눅", "from": "21:5", "to": "21:6"}]'::jsonb, 70, 70, 'exact', 1, '예루살렘', 31.778, 35.235, 'published'),
    ('era_nt_public_ministry', '세례 요한의 탄생 예고', '제사장 사가랴에게 천사가 나타나 세례 요한의 탄생을 알린다.', '["성전 안, 사가랴가 향을 사르며 조용히 서 있다", "갑자기 빛, 가브리엘이 나타나 사가랴가 굳어 선다", "놀람이 번진다", "사가랴가 말을 못하게 되고, 밖에 나온 그는 손짓만 한다"]'::jsonb, '[[], ["gabriel"], [], []]'::jsonb, ARRAY['zechariah', 'gabriel', 'elizabeth']::text[], '[{"book": "눅", "from": "1:5", "to": "1:25"}]'::jsonb, 5, 5, 'approx', 1, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_patriarch', '아브라함의 부르심: 떠나라', '하나님이 아브라함을 부르시고 약속의 길을 여신다.', '["하란의 일상 속에서 아브라함이 멈춰 서서 먼 곳을 바라본다", "하나님의 빛이 임하고 아브라함이 숨을 고른다", "아브라함이 장막을 접고 가족이 짐을 낙타에 싣는다", "가나안으로 향하는 길 위에서 아브라함이 제단을 세운다"]'::jsonb, '[["abraham"], ["abraham", "god"], ["abraham"], ["abraham"]]'::jsonb, ARRAY['abraham', 'god']::text[], '[{"book": "창", "from": "12:1", "to": "12:9"}]'::jsonb, -2100, -2100, 'approx', 1, '하란', 36.87, 39.03, 'published'),
    ('era_exile_return', '예루살렘 함락: 성전이 불타다', '성전이 파괴되고 백성은 포로로 끌려가며 포로 시대가 시작된다.', '["성전 쪽으로 번지는 불빛과 연기", "israelites가 israelites가 israelites가 israelites가 israelites가 israelites가 사람들이 집을 떠나 끌려간다, 울음소리가 멀어진다", "배경과 분위기만 보이는", "텅 빈 도시에 바람만 남고, 화면이 천천히 어두워진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "왕하", "from": "25:8", "to": "25:21"}]'::jsonb, -586, -586, 'approx', 1, '예루살렘', 31.78, 35.23, 'published'),
    ('era_nt_apostolic', '오순절: 성령강림', '성령이 임하며 교회의 시대가 힘 있게 시작된다.', '["다락방, 사람들이 기도하며 숨죽인 채 기다린다", "갑자기 큰 바람 같은 소리, 모두가 놀라 고개를 든다", "불의 혀 같은 것이 나타나 머물고, 각기 다른 말이 터져 나온다", "밖의 군중이 몰려든다, 무슨 일이냐?, 웅성거림이 커진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'matthias']::text[], '[{"book": "행", "from": "2:1", "to": "2:13"}]'::jsonb, 33, 33, 'approx', 1, '예루살렘', 31.778, 35.222, 'published'),
    ('era_monarchy', '왕을 요구하다: 우리도 왕을', '백성은 ‘우리도 왕을’ 요구하고, 사무엘은 하나님 앞에서 그 무게를 경고한다.', '["사무엘이 결연한 표정으로 선다", "사무엘이 마음 아파하며 기도한다, 고요한 밤", "사무엘이 왕의 폐해를 설명한다, 사람들의 표정이 굳는다", "백성들이 사무엘에게 그래도 왕을 달라고 말한다"]'::jsonb, '[["samuel"], ["samuel"], ["samuel"], ["samuel"]]'::jsonb, ARRAY['samuel']::text[], '[{"book": "삼상", "from": "8:1", "to": "8:22"}]'::jsonb, -1050, -1050, 'approx', 1, '라마/이스라엘(전승)', 31.92, 35.21, 'published'),
    ('era_judges', '요단강 도하: 물이 멈추다', '이스라엘은 요단강을 건너며 약속의 땅에 들어선다.', '["여호수아가 시켜 제사장들이 언약궤를 메고 요단강 앞에 선다", "제사장들의 발이 물을 밟자 요단강 물이 갈라진다", "이스라엘 백성이 마른 땅으로 요단강을 건너간다", "여호수아가 시켜 열두 사람이 제사장들의 발이 섰던 곳에 돌을 세운다"]'::jsonb, '[["joshua"], [], [], ["joshua"]]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "3:1", "to": "4:24"}]'::jsonb, -1406, -1406, 'approx', 1, '요단강(여리고 맞은편, 전승)', 31.85, 35.55, 'published'),
    ('era_exodus', '이스라엘의 압제와 산파들', '바로는 이스라엘을 두려워해 학대하고, 산파들은 하나님을 두려워해 생명을 지킨다.', '["벽돌 굽는 현장, 감독의 고함과 지친 얼굴들", "바로의 명령이 내려온다, 남자 아기는 죽여라", "산파들이 서로를 바라본다, 떨리지만 고개를 끄덕인다", "아기가 숨 쉬는 소리, 산파들이 조용히 아이를 품고 숨긴다"]'::jsonb, '[[], ["pharaoh"], [], []]'::jsonb, ARRAY['pharaoh']::text[], '[{"book": "출", "from": "1:1", "to": "1:22"}]'::jsonb, -1446, -1446, 'approx', 1, '애굽(고센 일대, 전승)', 30.8, 31.85, 'published'),
    ('era_primeval', '창조: 7일과 안식', '하나님이 말씀으로 세상을 창조하시고 안식으로 완성하신다.', '["완전한 어둠과 혼돈이 가득한 태초의 세계", "하나님의 빛이 임하며 어둠이 갈라지고 질서가 생겨난다", "하늘과 바다와 땅, 식물과 별과 동물이 차례로 채워지고 사람은 전혀 보이지 않는다", "넓은 세상이 고요한 안식에 잠기고 사람은 전혀 보이지 않는다"]'::jsonb, '[[], ["god"], [], []]'::jsonb, ARRAY['god']::text[], '[{"book": "창", "from": "1:1", "to": "2:3"}]'::jsonb, -4000, -4000, 'approx', 1, '메소포타미아(추정)', 31.018, 47.423, 'published'),
    ('era_nt_consummation', '하늘 보좌: 문이 열리다', '요한은 하늘 보좌의 환상을 보고 경배의 중심을 목격한다.', '["문이 열리는 듯한", "보좌와 무지개 같은 빛, 번개와 음성이 울린다", "생물들이 거룩하다를 반복하고 요한이 숨을 삼킨다", "배경과 분위기만 보이는"]'::jsonb, '[[], [], ["john"], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "4:1", "to": "4:11"}]'::jsonb, null, null, 'approx', 1, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_exile_return', '남은 자의 선택: 두 갈래 길', '남은 자들은 두려움 속에서 떠나고, 예레미야의 경고는 외면된다.', '["백성들이 예레미야에게 와서 기도를 간구하는 장면", "하나님의 말씀이 예레미야에게 임하는 장면", "예레미야가 사람들에게 하나님의 말씀을 강하게 전하지만 사람들은 듣지 않고 가버리는 장면", "예레미야가 바로의 궁전 대문 벽돌 축대에 큰 돌 여러 개를 진흙으로 감추는 장면"]'::jsonb, '[["jeremiah"], ["jeremiah", "god"], ["jeremiah"], ["jeremiah"]]'::jsonb, ARRAY['jeremiah']::text[], '[{"book": "렘", "from": "42:1", "to": "43:7"}]'::jsonb, -585, -585, 'approx', 2, '유다 땅(미스바/애굽 길, 전승)', 31.83, 35.17, 'published'),
    ('era_nt_public_ministry', '마리아 수태고지와 찬양', '마리아는 천사의 소식을 받고 엘리사벳을 찾아가 찬양한다.', '["나사렛의 집, 가브리엘이 결연한 표정으로 선다", "마리아가 조용히 고개를 끄덕인다", "마리아가 길을 떠나 유대 산지로 달려간다", "마리아와 엘리사벳이 결연한 표정으로 선다"]'::jsonb, '[["gabriel"], ["mary"], ["mary"], ["mary", "elizabeth"]]'::jsonb, ARRAY['mary', 'gabriel', 'elizabeth']::text[], '[{"book": "눅", "from": "1:26", "to": "1:56"}]'::jsonb, 5, 5, 'approx', 2, '나사렛 → 유대 산지(전승)', 32.7, 35.303, 'published'),
    ('era_exodus', '모세의 탄생과 갈대상자', '죽음의 명령 속에서 한 아기가 갈대상자에 실려 기적처럼 보호받는다.', '["어머니가 아기를 꼭 안고 숨죽인다, 밖에서 발소리가 지나간다", "갈대상자에 역청을 바르고 조심히 물가에 띄운다", "아기의 누이가 멀리서 상자가 어떻게 되는지 지켜본다", "바로의 딸이 상자를 열고 아기를 안는다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['moses', 'miriam']::text[], '[{"book": "출", "from": "2:1", "to": "2:10"}]'::jsonb, -1446, -1446, 'approx', 2, '나일강(전승)', 29.9, 31.25, 'published'),
    ('era_nt_post_apostolic', '밧모섬의 요한: 계시의 시작', '요한은 밧모섬에서 환상 가운데 계시를 받는다.', '["바닷바람 부는 섬, 요한이 홀로 앉아 기도한다", "나팔 소리 같은 큰 음성이 들리고 요한이 뒤돌아본다", "빛나는 환상, 요한이 두려움에 엎드린다", "기록하여 보내라 명령에 요한이 두루마리를 붙잡는다"]'::jsonb, '[["john"], ["john"], ["john"], ["john"]]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "1:9", "to": "1:20"}]'::jsonb, 95, 95, 'approx', 2, '밧모섬', 37.31, 26.55, 'published'),
    ('era_nt_apostolic', '베드로 설교: 하루에 삼천', '베드로의 설교로 많은 사람이 회개하고 공동체가 태어난다.', '["군중 앞에 선 베드로, 두려움 대신 담대함이 얼굴에 있다", "이 예수를 하나님이 주와 그리스도가 되게 하셨다가 울린다", "배경과 분위기만 보이는", "물가에서 세례가 이어지고, 떡을 떼는 공동체 앞쪽에 서 있고, 으로 전환된다"]'::jsonb, '[["peter"], [], [], []]'::jsonb, ARRAY['peter']::text[], '[{"book": "행", "from": "2:14", "to": "2:47"}]'::jsonb, 33, 33, 'approx', 2, '예루살렘', 31.778, 35.222, 'published'),
    ('era_monarchy', '사울의 기름부음: 숨은 청년', '사울은 예상치 못한 자리에서 기름부음을 받고 첫 왕의 길에 들어선다.', '["젊은 청년 사울이 길에서 나귀를 찾으며 헤맨다", "젊은 사울이 사무엘을 만나 대화하며 놀라는 장면", "사무엘이 젊은 사울에게 기름을 붓는 장면", "젊은 사울이 결연한 표정으로 곧게 선다"]'::jsonb, '[["saul"], ["saul", "samuel"], ["saul", "samuel"], ["saul"]]'::jsonb, ARRAY['saul', 'samuel']::text[], '[{"book": "삼상", "from": "9:1", "to": "10:16"}]'::jsonb, -1050, -1050, 'approx', 2, '라마(전승)', 31.92, 35.21, 'published'),
    ('era_patriarch', '애굽 우회: 두려움의 선택', '기근과 두려움 속에서 아브라함은 위험한 거짓말을 선택한다.', '["메마른 땅, 기근 속 행렬이 애굽으로 향한다", "아브라함이 사라에게 속삭인다", "궁정 쪽으로 끌려가는 사라, 긴장, 아브라함은 굳은 얼굴", "재앙 후 사라가 돌아오고, 아브라함은 급히 떠난다"]'::jsonb, '[[], ["abraham", "sarah"], ["abraham", "sarah"], ["abraham", "sarah"]]'::jsonb, ARRAY['abraham', 'sarah']::text[], '[{"book": "창", "from": "12:10", "to": "12:20"}]'::jsonb, -2099, -2099, 'approx', 2, '애굽(멤피스 일대, 전승)', 29.85, 31.25, 'published'),
    ('era_nt_consummation', '어린양: 두루마리를 받다', '어린양이 두루마리를 받아 역사의 열쇠를 여는 존재로 드러난다.', '["봉인된 두루마리, 누가 열 수 있는가 질문이 울린다", "요한이 울다가 유다 지파의 사자 소리를 듣고 고개를 든다", "어린양이 보좌 앞으로 나아가 두루마리를 받는다", "하늘의 찬양이 폭발하듯 번지고 경배가 가득 찬다"]'::jsonb, '[[], ["john"], [], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "5:1", "to": "5:14"}]'::jsonb, null, null, 'approx', 2, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_primeval', '에덴: 사람의 창조와 사명', '사람은 에덴에서 돌보고 지키는 사명을 받는다.', '["옷을 입지 않은 아담이 큰 잎과 풀숲에 몸을 가린 채 흙에서 일어나 숨을 들이마시며 눈을 뜬다, 얼굴과 어깨 위주만 보인다", "옷을 입지 않은 아담이 에덴의 큰 잎과 풀숲에 몸을 가린 채 서 있고 하나님의 빛이 가까이 임한다, 얼굴과 상반신 위주만 보인다", "옷을 입지 않은 아담이 큰 잎과 풀숲에 몸을 가린 채 동물들을 바라보며 이름을 붙인다, 얼굴과 상반신 위주만 보인다", "옷을 입지 않은 아담과 하와가 큰 잎과 풀숲 뒤에 몸을 가린 채 서로를 바라본다, 얼굴과 어깨 위주만 보인다"]'::jsonb, '[["adam"], ["god", "adam"], ["adam"], ["adam", "eve"]]'::jsonb, ARRAY['god', 'adam', 'eve']::text[], '[{"book": "창", "from": "2:4", "to": "2:25"}]'::jsonb, -4000, -4000, 'approx', 2, '에덴 지역(추정)', 31.018, 47.423, 'published'),
    ('era_judges', '여리고: 침묵의 행진', '상식을 깨는 순종의 행진 끝에 성벽이 무너진다.', '["여리고 성벽 아래, 침묵 속 행렬이 한 바퀴 돈다", "나팔 소리만 울리고 사람들은 말이 없다", "일곱째 날, 일곱 바퀴, 긴장감이 최고조가 된다", "외쳐라!, 함성과 함께 성벽이 흔들리며 무너진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "6:1", "to": "6:20"}]'::jsonb, -1406, -1406, 'approx', 2, '여리고', 31.87, 35.44, 'published'),
    ('era_patriarch', '롯과 분리: 시선의 선택', '갈등을 피하려 한 분리가 훗날의 방향을 가른다.', '["목자들이 다투고, 아브라함이 손을 들어 멈추게 한다", "아브라함이 앞쪽에 서 있고, 양보를 제안한다", "롯이 푸른 요단 들을 가리키며 선택한다", "아브라함이 남은 땅에 서서 제단을 세운다"]'::jsonb, '[["abraham"], ["abraham"], ["lot"], ["abraham"]]'::jsonb, ARRAY['abraham', 'lot']::text[], '[{"book": "창", "from": "13:1", "to": "13:18"}]'::jsonb, -2098, -2098, 'approx', 3, '요단 들(전승)', 31.8, 35.6, 'published'),
    ('era_exodus', '모세의 분노와 미디안 도피', '모세는 억압을 보고 분노하지만, 결국 광야로 도망쳐 새 삶을 시작한다.', '["모세가 노역 현장을 바라보다 주먹을 꽉 쥔다", "폭력이 터지고, 모세가 숨 가쁘게 멈춰 선다, 후회", "소문이 퍼지고 바로의 분노가 번진다, 모세가 급히 떠난다", "미디안 우물가, 모세가 낯선 사람들을 돕고 물을 길어준다"]'::jsonb, '[["moses"], ["moses"], ["moses"], ["moses"]]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "2:11", "to": "2:25"}]'::jsonb, -1406, -1406, 'approx', 3, '애굽 → 미디안(전승)', 29.9, 31.25, 'published'),
    ('era_monarchy', '사울의 첫 승리: 얍베스 길르앗', '사울은 첫 위기에서 백성을 모아 구원하고 왕권을 굳힌다.', '["위협 소식이 전해진다, 사람들의 얼굴이 창백해진다", "사울이 전령을 보내 이스라엘 병력을 소집하는 장면", "전투 후, 얍베스가 구원받고 환호가 터진다", "길갈에서 사울의 왕권이 확인된다, 사무엘이 축복한다"]'::jsonb, '[[], ["saul"], [], ["saul", "samuel"]]'::jsonb, ARRAY['saul', 'samuel']::text[], '[{"book": "삼상", "from": "11:1", "to": "11:15"}]'::jsonb, -1049, -1049, 'approx', 3, '얍베스 길르앗(전승)', 32.38, 35.56, 'published'),
    ('era_nt_apostolic', '성전 미문 치유와 첫 박해', '치유로 군중이 모이고, 지도자들은 사도들을 막기 시작한다.', '["성전 문, 앉은 사람이 손을 내민다, 베드로가 멈춰 선다", "나사렛 예수 이름으로 일어나 걸어라, 사람이 벌떡 일어선다", "군중이 몰려들고 베드로가 예수를 증거한다", "관리들이 들이닥쳐 사도들을 붙잡는다, 밤이 깊어간다"]'::jsonb, '[["peter"], [], ["peter"], []]'::jsonb, ARRAY['peter', 'john']::text[], '[{"book": "행", "from": "3:1", "to": "3:26"}, {"book": "행", "from": "4:1", "to": "4:22"}]'::jsonb, 33, 33, 'approx', 3, '예루살렘 성전 미문', 31.778, 35.235, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_judges', '아간: 감춘 것이 드러나다', '숨긴 탐욕이 공동체의 패배로 드러나고, 정리가 시작된다.', '["아이 성 공격이 실패하고 군이 흩어진다, 여호수아가 찢어진 옷으로 엎드린다", "이스라엘 중에 범죄함이 있다는 선언, 진영이 술렁인다", "제비가 좁혀지며 아간이 떨며 선다", "여호수아가 뒤에 서 있고, 사람들이 아간에게 돌을 던지며 심판한다, 직접 묘사는 절제한다"]'::jsonb, '[["joshua"], [], ["achan"], ["joshua", "achan"]]'::jsonb, ARRAY['joshua', 'achan']::text[], '[{"book": "수", "from": "7:1", "to": "7:26"}]'::jsonb, -1406, -1406, 'approx', 3, '아이 성 근처(전승)', 31.93, 35.25, 'published'),
    ('era_exile_return', '에스겔의 소명: 보좌의 환상', '포로지에서 에스겔은 하나님의 영광을 보고 파수꾼의 사명을 받는다.', '["강가에 앉은 에스겔, 하늘이 갈라지는 듯한 빛", "바퀴와 생물의 환상, 에스겔이 몸을 떤다", "배경과 분위기만 보이는", "에스겔이 일어나 포로 공동체를 바라본다, 파수꾼의 눈빛"]'::jsonb, '[["ezekiel"], ["ezekiel"], [], ["ezekiel"]]'::jsonb, ARRAY['ezekiel']::text[], '[{"book": "겔", "from": "1:1", "to": "3:11"}]'::jsonb, -593, -593, 'approx', 3, '그발 강가(바벨론, 전승)', 32.55, 44.42, 'published'),
    ('era_nt_public_ministry', '예수 탄생과 목자들', '베들레헴에서 예수님이 태어나고 목자들이 기쁜 소식을 듣는다.', '["인구조사로 붐비는 베들레헴, 요셉과 마리아가 자리를 찾지 못한다", "조용한 밤, 아기가 태어나 구유에 눕혀진다", "들판의 목자들 앞에 천사가 나타나 천사가 나타나고 목자들이 놀라 눈을 들어 올린다", "목자들이 급히 달려와 아기를 보고, 돌아가며 소문을 퍼뜨린다"]'::jsonb, '[["mary", "joseph"], [], [], []]'::jsonb, ARRAY['jesus', 'mary', 'joseph']::text[], '[{"book": "눅", "from": "2:1", "to": "2:20"}]'::jsonb, 4, 4, 'approx', 3, '베들레헴', 31.705, 35.202, 'published'),
    ('era_nt_post_apostolic', '일곱 교회 편지: 촛대 사이의 말씀', '일곱 교회에 칭찬과 책망, 약속이 전달된다.', '["요한이 편지를 쓰기 시작한다, 촛불이 흔들린다", "처음 사랑을 버렸다 같은 말이 떨어지고 요한이 잠깐 멈춘다", "이기는 자에게 약속이 이어진다, 희망의 톤이 스친다", "편지가 봉해지고 사자가 길을 떠난다, 전달의"]'::jsonb, '[["john"], ["john"], [], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "2:1", "to": "3:22"}]'::jsonb, 95, 95, 'approx', 3, '소아시아(일곱 교회 중심: 에베소)', 37.95, 27.37, 'published'),
    ('era_nt_consummation', '일곱 인: 역사의 문이 열리다', '봉인이 하나씩 열리며 심판과 경고의 흐름이 전개된다.', '["첫 봉인이 열리고 전개가 시작되는 긴장감", "연속되는 봉인들로 세상이 흔들리는 이미지", "사람들의 질문과 두려움이 커지는", "보호의 표가 강조되며 끝까지 버팀의 톤으로 마무리된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "6:1", "to": "7:17"}]'::jsonb, null, null, 'approx', 3, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_primeval', '타락: 뱀의 유혹과 선택', '유혹은 의심을 만들고, 선택은 관계의 균열로 이어진다.', '["옷을 입지 않은 하와가 큰 나무 곁에서 뱀의 유혹을 듣는다, 몸은 잎과 가지에 가려지고 얼굴과 어깨 위주만 보인다", "옷을 입지 않은 하와가 열매를 바라보며 망설이다 손을 뻗는다, 몸은 큰 잎과 풀숲에 가려지고 얼굴과 상반신 위주만 보인다", "옷을 입지 않은 하와가 아담에게 열매를 건네고 아담이 받는다, 두 사람의 몸은 잎과 풀에 가려지고 얼굴과 어깨 위주만 보인다", "아담과 하와가 잎으로 몸을 가린 채 나무 사이에 숨는다, 부끄러움이 덮친다"]'::jsonb, '[["eve"], ["eve"], ["eve", "adam"], ["adam", "eve"]]'::jsonb, ARRAY['eve', 'adam']::text[], '[{"book": "창", "from": "3:1", "to": "3:13"}]'::jsonb, -3995, -3995, 'approx', 3, '에덴 지역(추정)', 31.018, 47.423, 'published'),
    ('era_judges', '기브온 조약: 속임수의 동맹', '기브온은 속임수로 조약을 맺고, 이스라엘은 그 약속을 지킨다.', '["해진 옷과 마른 떡을 든 기브온 사절단이 여호수아를 찾아온다", "여호수아가 그들의 말을 믿고 조약을 맺는다, 긴장감이 흐른다", "정체가 드러나자 진영이 분노한다", "여호수아가 그들에게 나무 패는 자와 물 긷는 자가 되라고 명령한다"]'::jsonb, '[["joshua"], ["joshua"], [], ["joshua"]]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "9:3", "to": "9:27"}]'::jsonb, -1405, -1405, 'approx', 4, '기브온(전승)', 31.85, 35.18, 'published'),
    ('era_nt_public_ministry', '동방박사와 피신', '동방박사가 경배하고, 헤롯의 위협으로 가족은 애굽으로 피신한다.', '["예루살렘 궁정, 별 이야기에 헤롯의 얼굴이 굳는다", "베들레헴의 집, 박사들이 예물을 드리며 경배한다", "꿈에서 경고를 받고 박사들이 다른 길로 돌아간다", "요셉이 급히 가족을 깨워 밤길로 애굽을 향해 떠난다"]'::jsonb, '[[], [], [], ["joseph"]]'::jsonb, ARRAY['jesus', 'mary', 'joseph', 'herod']::text[], '[{"book": "마", "from": "2:1", "to": "2:15"}]'::jsonb, 4, 4, 'approx', 4, '예루살렘 → 베들레헴 → 애굽(전승)', 31.778, 35.222, 'published'),
    ('era_exile_return', '마른 뼈: 숨이 들어오다', '절망의 뼈들에게 말씀과 숨이 임해 회복의 그림이 그려진다.', '["뼈들로 가득한 골짜기, 바람도 없는 정적", "에스겔이 대언하라는 명령", "에스겔이 서 있는 가운데 마른 뼈 위에 힘줄과 살이 덮이기 시작한다", "숨이 돌아온 사람들이 일어서고 그 한가운데 에스겔이 서 있다"]'::jsonb, '[[], ["ezekiel"], ["ezekiel"], ["ezekiel"]]'::jsonb, ARRAY['ezekiel']::text[], '[{"book": "겔", "from": "37:1", "to": "37:14"}]'::jsonb, -585, -585, 'approx', 4, '그발 강가(추정)', 32.55, 44.42, 'published'),
    ('era_exodus', '불타는 떨기나무: 모세의 소명', '광야에서 하나님은 모세를 부르시고 ‘내가 너와 함께’라는 약속을 주신다.', '["모세가 양을 몰다 불타는 떨기나무를 발견하고 멈춘다", "모세가 신을 벗고 떨며 선다", "하나님의 빛이 임한다", "모세가 망설이자 내가 너와 함께하리라가 울린다"]'::jsonb, '[["moses"], ["moses"], ["god"], ["moses"]]'::jsonb, ARRAY['moses', 'god']::text[], '[{"book": "출", "from": "3:1", "to": "3:22"}, {"book": "출", "from": "4:1", "to": "4:17"}]'::jsonb, -1446, -1446, 'approx', 4, '호렙 산(전승)', 28.54, 33.98, 'published'),
    ('era_monarchy', '사울의 불순종: 왕의 균열', '사울의 조급함과 자기합리화는 왕으로서의 길에 균열을 만든다.', '["전투 전, 사울이 조급해하며 제사를 대신 드린다", "사무엘이 상대를 바라보며 기다린다", "사무엘이 사울을 엄하게 꾸짖는다", "사무엘이 뒤돌아서 떠나자 사울이 옷자락을 붙잡고, 옷자락이 찢어진다"]'::jsonb, '[["saul"], ["samuel"], ["saul", "samuel"], ["saul", "samuel"]]'::jsonb, ARRAY['saul', 'samuel']::text[], '[{"book": "삼상", "from": "13:7", "to": "13:14"}, {"book": "삼상", "from": "15:1", "to": "15:23"}]'::jsonb, -1045, -1045, 'approx', 4, '길갈(전승)', 31.85, 35.45, 'published'),
    ('era_nt_apostolic', '아나니아와 삽비라', '거짓은 공동체를 흔들고, 사건은 거룩함의 경고가 된다.', '["아나니아가 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "베드로가 상대를 바라보며 기다린다", "충격이 퍼지고 회중이 얼어붙는다, 직접 묘사 최소", "삽비라가 들어오고 같은 질문이 반복되며 두려움이 공동체를 덮는다"]'::jsonb, '[["ananias"], ["peter"], [], []]'::jsonb, ARRAY['ananias', 'sapphira', 'peter']::text[], '[{"book": "행", "from": "5:1", "to": "5:11"}]'::jsonb, 34, 34, 'approx', 4, '예루살렘', 31.778, 35.222, 'published'),
    ('era_nt_consummation', '일곱 나팔: 경고의 울림', '나팔이 울리며 경고가 반복되고 회개의 촉구가 이어진다.', '["하늘의 잠깐 침묵 후, 첫 나팔이 울린다", "땅과 바다에 재앙 이미지가 번진다", "angels가 angels가 두 증인의 앞쪽에 서 있고, 이 스쳐 지나가며 긴장감이 높아진다", "angels가 angels가 angels가 angels가 angels가 angels가 마지막 나팔과 함께 나라가 주의 것이 되었다 선언이 울린다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "8:1", "to": "11:19"}]'::jsonb, null, null, 'approx', 4, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_patriarch', '전쟁과 멜기세덱: 축복의 만남', '아브라함은 롯을 구출하고, 멜기세덱에게 축복을 받는다.', '["전령이 사로잡힘 소식을 전하자 아브라함이 굳은 얼굴로 멈춰 선다", "아브라함이 사람들을 이끌고 야간 추격을 준비한다", "전투 후 롯을 되찾고 돌아오는 아브라함의 행렬", "멜기세덱이 떡과 포도주를 내며 아브라함을 축복한다"]'::jsonb, '[["abraham"], ["abraham"], ["abraham", "lot"], ["abraham", "melchizedek"]]'::jsonb, ARRAY['abraham', 'lot', 'melchizedek']::text[], '[{"book": "창", "from": "14:1", "to": "14:24"}]'::jsonb, -2097, -2097, 'approx', 4, '살렘(예루살렘, 전승)', 31.78, 35.22, 'published'),
    ('era_primeval', '추방: 동산 밖으로', '죄의 결과로 사람은 에덴을 떠나고, 길은 막힌다.', '["하나님의 빛 앞에서 아담과 하와가 거친 가죽옷을 입은 채 고개를 숙이고 결과를 듣는다", "하나님이 아담과 하와에게 거친 가죽옷을 입혀 준다", "아담과 하와가 거친 가죽옷을 입은 채 동산 문을 나선다, 침묵의 발걸음", "생명나무로 가는 길이 막히고 불칼이 번쩍인다"]'::jsonb, '[["god", "adam", "eve"], ["god", "adam", "eve"], ["adam", "eve"], []]'::jsonb, ARRAY['god', 'adam', 'eve']::text[], '[{"book": "창", "from": "3:14", "to": "3:24"}]'::jsonb, -3995, -3995, 'approx', 4, '에덴 동쪽(추정)', 31.09, 47.52, 'published'),
    ('era_primeval', '가인과 아벨: 들판의 비극', '분노가 다스려지지 않자 형제가 형제를 해친다.', '["두 형제가 제사를 드린다, 표정 대비", "하나님의 빛이 임하고, 가인이 이를 악문다", "들판에서 가인이 아벨을 덮친다, 직접 묘사 없이 충격", "하나님의 빛이 임하고, 가인은 책임을 피한다"]'::jsonb, '[["cain", "abel"], ["god", "cain", "abel"], ["cain", "abel"], ["god", "cain"]]'::jsonb, ARRAY['cain', 'abel', 'god']::text[], '[{"book": "창", "from": "4:1", "to": "4:16"}]'::jsonb, -3950, -3950, 'approx', 5, '에덴 밖 들판(추정)', 31.16, 47.61, 'published'),
    ('era_exile_return', '다니엘: 뜻을 정하다', '다니엘은 낯선 제국 한복판에서 믿음의 기준을 세운다.', '["궁정의 화려한 식탁, 다니엘이 멈춘다", "다니엘이 앞쪽에 서 있고, 관리가 난처해한다", "다니엘이 왕에게 단정한 제안을 하는 장면", "다니엘이 이전보다 더 건강한 모습으로 왕 앞에 서고 왕이 놀라는 장면"]'::jsonb, '[["daniel"], ["daniel"], ["daniel"], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "1:8", "to": "1:20"}]'::jsonb, -605, -605, 'approx', 5, '바벨론', 32.55, 44.42, 'published'),
    ('era_monarchy', '다윗의 기름부음: 새로운 선택', '하나님은 사람의 기준이 아닌 마음을 보시고 다윗을 택하신다.', '["사무엘이 어떤 집에 들어가는 장면", "사무엘이 여러 청년들 앞에서 고개를 젓는 모습", "젊은 다윗이 들판에서 양을 치다가 집으로 불려온다", "사무엘이 젊은 다윗에게 기름을 붓는 장면"]'::jsonb, '[["samuel"], ["samuel"], ["david"], ["david", "samuel"]]'::jsonb, ARRAY['david', 'samuel', 'jesse']::text[], '[{"book": "삼상", "from": "16:1", "to": "16:13"}]'::jsonb, -1030, -1030, 'approx', 5, '베들레헴', 31.7, 35.2, 'published'),
    ('era_exodus', '바로 앞 첫 대면: 짐이 더 무거워지다', '해방 요구와 표징 앞에서도 바로는 마음을 굳게 하고 노역을 더 무겁게 만든다.', '["모세와 아론이 바로 앞에 선다", "바로가 모세와 아론을 비웃는다", "벽돌 공장, 짚이 끊기고 사람들이 절망한다", "모세가 바로 앞에 지팡이를 던지자 뱀이 되고 궁정이 술렁인다"]'::jsonb, '[["moses", "aaron", "pharaoh"], ["moses", "aaron", "pharaoh"], [], ["moses", "aaron", "pharaoh"]]'::jsonb, ARRAY['moses', 'aaron', 'pharaoh']::text[], '[{"book": "출", "from": "5:1", "to": "7:13"}]'::jsonb, -1446, -1446, 'approx', 5, '애굽 궁정(전승)', 29.9, 31.25, 'published'),
    ('era_patriarch', '별 언약: 믿음이 의로', '하나님은 별처럼 많은 자손을 약속하시고 언약을 확증하신다.', '["밤하늘 아래 하나님의 빛이 임한다", "아브라함이 셀 수 없는 별을 바라보다가 조용히 고개를 끄덕인다", "아브라함이 암소와 암염소와 숫양의 고기를 쪼개어 언약 의식을 준비한다", "어두운 밤, 아브라함이 지켜보는 가운데 하나님의 횃불 같은 빛이 쪼갠 고기 사이를 지나간다"]'::jsonb, '[["god"], ["abraham"], ["abraham"], ["abraham", "god"]]'::jsonb, ARRAY['abraham', 'god']::text[], '[{"book": "창", "from": "15:1", "to": "15:21"}]'::jsonb, -2096, -2096, 'approx', 5, '가나안(전승)', 31.5, 35, 'published'),
    ('era_judges', '세겜 언약 갱신: 선택하라', '여호수아는 백성에게 ‘오늘 누구를 섬길지’ 선택을 요구한다.', '["세겜에 모인 백성, 여호수아가 지팡이를 짚고 선다", "여호수아가 앞쪽에 서 있다", "백성들이 여호수아에게 고개 숙여 인사하며 우리도 하나님을 따르겠다고 말한다", "여호수아가 상수리나무 아래 큰 돌을 세우고, 백성들이 지켜본다"]'::jsonb, '[["joshua"], ["joshua"], ["joshua"], ["joshua"]]'::jsonb, ARRAY['joshua']::text[], '[{"book": "수", "from": "24:1", "to": "24:28"}]'::jsonb, -1380, -1380, 'approx', 5, '세겜', 32.22, 35.28, 'published'),
    ('era_nt_public_ministry', '어린 예수의 성전 사건', '소년 예수는 성전에서 율법교사들과 대화하며 자신의 정체를 드러낸다.', '["유월절 후 귀가 행렬 속, 마리아가 예수를 찾다가 멈칫한다", "부모가 예루살렘으로 되돌아가 급히 찾아다닌다", "성전 안, 예수가 교사들과 질문·대답을 나누고 모두가 놀란다", "예수 앞쪽에 서 있고, 부모가 말없이 바라본다"]'::jsonb, '[["mary", "jesus"], [], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus', 'mary', 'joseph']::text[], '[{"book": "눅", "from": "2:41", "to": "2:52"}]'::jsonb, 8, 8, 'approx', 5, '예루살렘 성전', 31.778, 35.235, 'published'),
    ('era_nt_consummation', '용과 두 짐승: 대립의 정점', '거대한 대립이 드러나고, 믿는 자들의 인내가 강조된다.', '["하늘의 전쟁 같은 이미지, 대립이 시작된다", "땅 위에 권세가 등장하며 사람들의 시선이 흔들린다", "표와 충성의 선택이 강조되는", "배경과 분위기만 보이는"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "12:1", "to": "13:18"}]'::jsonb, null, null, 'approx', 5, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_apostolic', '일곱 집사와 스데반 순교', '섬김의 구조가 세워지고, 스데반의 죽음은 흩어짐의 불씨가 된다.', '["구제 문제로 다툼이 생기고 사도들이 일곱 사람을 세운다", "배경과 분위기만 보이는", "분노가 폭발하고 스데반이 하늘을 바라본다, 직접 묘사 최소", "사울이 그 광경을 지켜본다, 그의 눈빛이 단단해진다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "matthias"], [], [], ["saul"]]'::jsonb, ARRAY['stephen', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'matthias', 'saul']::text[], '[{"book": "행", "from": "6:1", "to": "6:7"}, {"book": "행", "from": "7:54", "to": "8:1"}]'::jsonb, 35, 35, 'approx', 5, '예루살렘', 31.778, 35.222, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_monarchy', '다윗과 골리앗: 돌 하나', '소년 다윗은 믿음으로 거인을 맞서 전세를 뒤집는다.', '["골리앗의 조롱이 울리고 이스라엘 진영이 움츠러든다", "18세쯤의 젊은 다윗이 사울 앞에 결연한 표정으로 서 있다", "18세쯤의 젊은 다윗이 시냇가에서 돌을 집어 들고 물매를 고른다", "돌이 날아가고 골리앗이 쓰러지며 진영의 공기가 바뀐다"]'::jsonb, '[[], ["david", "saul"], ["david"], []]'::jsonb, ARRAY['david', 'goliath', 'saul']::text[], '[{"book": "삼상", "from": "17:32", "to": "17:50"}]'::jsonb, -1025, -1025, 'approx', 6, '엘라 골짜기', 31.69, 34.93, 'published'),
    ('era_nt_consummation', '바벨론의 멸망: 무너지는 화려함', '교만한 체계가 무너지고, 애통과 해방의 대비가 나타난다.', '["화려한 도시 이미지가 등장하고, 사람들의 욕망이 번쩍인다", "배경과 분위기만 보이는", "배경과 분위기만 보이는", "하늘의 기쁨과 땅의 애통이 대비되며 마무리된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "계", "from": "17:1", "to": "17:18"}, {"book": "계", "from": "18:1", "to": "18:24"}]'::jsonb, null, null, 'approx', 6, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_nt_apostolic', '사마리아 복음: 빌립의 전도', '박해로 흩어진 자리에서 복음은 사마리아까지 확장된다.', '["사람들이 짐을 싸며 흩어진다, 도시마다 소문이 번진다", "빌립이 사마리아에서 복음을 전하고 사람들이 몰려든다", "기쁨이 도시를 채우고, 사도들이 내려와 기도한다", "새 공동체가 세워지고 경계가 허물어짐을 암시한다"]'::jsonb, '[[], ["philip"], [], []]'::jsonb, ARRAY['philip']::text[], '[{"book": "행", "from": "8:4", "to": "8:25"}]'::jsonb, 35, 35, 'approx', 6, '사마리아', 32.28, 35.19, 'published'),
    ('era_judges', '사사 시대의 반복: 잊고, 부르짖고, 구원받고', '이스라엘은 반복되는 타락과 회복의 사이클 속에 살아간다.', '["시간이 흐르고 세대가 바뀌며 기억이 희미해진다", "우상이 들어오고 억압이 시작된다, 어두운 톤", "배경과 분위기만 보이는", "사사가 일어나고 평안이 오지만, 다시 반복될 기미가 보인다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "삿", "from": "2:10", "to": "2:19"}]'::jsonb, -1375, -1375, 'approx', 6, '가나안(전승)', 31.8, 35.1, 'published'),
    ('era_primeval', '셋의 계보: 다시 부르다', '끊긴 듯한 역사 속에서도 하나님을 찾는 흐름이 이어진다.', '["seth가 seth가 seth가 seth가 결연한 표정으로 선다", "세대가 지나가며 이름들이 이어진다, 계보", "seth가 seth가 사람들이 여호와의 이름을 부르기 시작한다, 예배 앞쪽에 서 있다", "에녹이 하나님과 동행하는 모습으로 마무리된다"]'::jsonb, '[["seth"], [], ["seth"], []]'::jsonb, ARRAY['seth']::text[], '[{"book": "창", "from": "4:25", "to": "5:24"}]'::jsonb, -3900, -3100, 'approx', 6, '근동(상징)', 33, 44, 'published'),
    ('era_nt_public_ministry', '예수의 세례', '예수님이 세례를 받으실 때 하늘의 음성과 표징이 나타난다.', '["요단강가, 요한이 사람들을 세례 주는 가운데 예수가 앞으로 나온다", "요한이 망설이자 예수가 조용히 고개를 끄덕인다", "물에서 올라오는 순간 하늘이 열리는 듯한 빛이 비친다", "하늘에서 빛이 비치고, 사람들이 숨을 삼킨다"]'::jsonb, '[["jesus", "john_the_baptist"], ["jesus", "john_the_baptist"], [], []]'::jsonb, ARRAY['jesus', 'john_the_baptist']::text[], '[{"book": "마", "from": "3:13", "to": "3:17"}, {"book": "막", "from": "1:9", "to": "1:11"}, {"book": "눅", "from": "3:21", "to": "3:22"}, {"book": "요", "from": "1:29", "to": "1:34"}]'::jsonb, 27, 27, 'approx', 6, '요단강(여리고 근처, 전승)', 31.85, 35.55, 'published'),
    ('era_exodus', '재앙의 시작: 물이 변하다', '하나님은 열 가지 재앙으로 바로의 완강함을 흔드시지만, 바로는 끝까지 마음을 굳힌다.', '["세로 3등분 구도: 위에는 나일강 물이 피로 변해 사람들이 충격에 빠진 모습, 가운데에는 개구리가 집과 궁으로 몰려 올라오는 모습, 아래에는 이가 사람과 가축의 몸에 달라붙어 모두가 괴로워하는 모습", "세로 3등분 구도: 위에는 파리가 바로의 궁을 가득 메운 모습, 가운데에는 애굽의 가축들이 들판에서 떼죽음을 당해 사람들이 망연한 모습, 아래에는 악성 종기로 고통스러워하는 사람들이 몸을 움츠린 모습", "세로 3등분 구도: 위에는 우박이 애굽 전역에 쏟아지는 모습, 가운데에는 메뚜기가 땅을 뒤덮는 모습, 아래에는 흑암이 온 땅을 덮어 사람들이 더듬으며 서 있는 모습", "모세가 바로 앞에서 애굽의 초태생이 모두 죽게 될 것이라고 엄중히 경고한다, 궁정의 공기가 얼어붙는다"]'::jsonb, '[[], [], [], ["moses", "pharaoh"]]'::jsonb, ARRAY['moses', 'aaron', 'pharaoh']::text[], '[{"book": "출", "from": "7:14", "to": "11:10"}]'::jsonb, -1446, -1446, 'approx', 6, '나일강(전승)', 29.9, 31.25, 'published'),
    ('era_exile_return', '풀무불: 다니엘과 세 친구', '우상 숭배 강요 앞에서 믿음은 굴복 대신 신실함을 택한다.', '["다니엘과 세 친구가 거대한 금 신상 앞에서 서 있고, 다른 사람들은 모두 엎드린다", "다니엘과 세 친구가 왕 앞에서 믿음을 굽히지 않는 장면", "풀무불 속에서 다니엘과 세 친구가 함께 서 있는 장면", "왕이 다니엘과 세 친구를 칭찬하는 모습"]'::jsonb, '[["daniel"], ["daniel"], ["daniel"], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "3:1", "to": "3:30"}]'::jsonb, -585, -585, 'approx', 6, '바벨론(전승)', 32.55, 44.42, 'published'),
    ('era_patriarch', '하갈과 이스마엘: 사람의 방법', '기다림이 길어지자 가정에 갈등이 들어오고 하갈은 광야로 나간다.', '["사라가 결연한 표정으로 선다", "하갈의 시선이 바뀌고, 사라와 갈등이 폭발한다", "광야 길, 하갈이 눈물로 주저앉는다", "하나님의 위로, 하갈이 다시 일어나 길을 따른다"]'::jsonb, '[["sarah"], ["sarah", "hagar"], ["hagar"], ["hagar"]]'::jsonb, ARRAY['abraham', 'sarah', 'hagar', 'ishmael']::text[], '[{"book": "창", "from": "16:1", "to": "16:16"}]'::jsonb, -2090, -2090, 'approx', 6, '가나안(전승)', 31.5, 35, 'published'),
    ('era_nt_public_ministry', '광야 시험', '예수님은 광야에서 유혹을 말씀으로 이기며 사명의 방향을 확정하신다.', '["끝없는 광야, 예수가 지친 얼굴로 걷다가 멈춘다", "예수님이 조용히 고개를 끄덕인다", "높은 곳의 시험, 예수는 흔들리지 않는다", "유혹이 물러가고, 고요 속에 예수가 다시 길을 나선다"]'::jsonb, '[["jesus"], ["jesus"], ["jesus"], ["jesus"]]'::jsonb, ARRAY['jesus']::text[], '[{"book": "마", "from": "4:1", "to": "4:11"}, {"book": "막", "from": "1:12", "to": "1:13"}, {"book": "눅", "from": "4:1", "to": "4:13"}]'::jsonb, 27, 27, 'approx', 7, '유대 광야(전승)', 31.75, 35.3, 'published'),
    ('era_exile_return', '벨사살의 잔치: 벽에 쓴 글', '교만한 잔치에 ‘손 글씨’가 나타나고, 심판이 선포된다.', '["화려한 잔치, 웃음과 술잔 소리로 가득하다", "벽에 나타난 손 글씨, 모두가 얼어붙는다", "다니엘이 해석한다, 너는 저울에 달려 부족함이 보였다", "왕이 다니엘에게 자주색 옷을 입히게 하며 금 사슬을 그의 목에 걸어 주는 장면"]'::jsonb, '[[], [], ["daniel"], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "5:1", "to": "5:31"}]'::jsonb, -539, -539, 'approx', 7, '바벨론', 32.55, 44.42, 'published'),
    ('era_monarchy', '사울의 시기: 다윗의 도망 시작', '사울의 질투는 다윗을 적으로 만들고 도망의 길을 연다.', '["백성들이 환호하고, 사울의 표정은 굳어지고, 20대 초반의 젊은 다윗은 기쁜 얼굴로 서 있다", "사울이 창을 던지고, 20대 초반의 젊은 다윗이 몸을 피한다", "요나단이 20대 초반의 젊은 다윗과 언약을 맺고 눈물로 작별한다", "20대 초반의 젊은 다윗이 밤길로 사라지고, 뒤에서 군사들의 발소리가 따라온다"]'::jsonb, '[["david", "saul"], ["david", "saul"], ["david", "jonathan"], ["david"]]'::jsonb, ARRAY['david', 'saul', 'jonathan']::text[], '[{"book": "삼상", "from": "18:6", "to": "20:42"}]'::jsonb, -1024, -1015, 'approx', 7, '기브아(사울의 성, 전승)', 31.85, 35.25, 'published'),
    ('era_nt_apostolic', '에티오피아 내시: 길 위의 만남', '한 사람의 질문이 길 위에서 답을 만나고, 복음은 더 먼 곳으로 간다.', '["얼굴에 의문이 가득하다", "빌립이 상대를 바라보며 기다린다", "물가에서 세례, 내시가 환하게 웃는다", "내시가 기쁨으로 길을 가고, 빌립은 다른 곳으로 인도된다"]'::jsonb, '[[], ["philip"], [], ["philip"]]'::jsonb, ARRAY['philip']::text[], '[{"book": "행", "from": "8:26", "to": "8:40"}]'::jsonb, 35, 35, 'approx', 7, '예루살렘-가사 길(전승)', 31.5, 34.47, 'published'),
    ('era_judges', '에훗: 왼손의 반전', '에훗은 예상 밖의 방식으로 억압을 끊고 탈출한다.', '["이스라엘 백성이 여호와 앞에서 악을 행하며 우상을 숭배한다", "이스라엘 백성이 모압 왕 에글론을 섬기며 무거운 조공을 바친다", "에훗이 조공을 들고 모압 왕 에글론에게 들어간다", "왕은 왕좌 앞 바닥에 움직이지 않게 누워 있고, 에훗은 재빨리 도망간다"]'::jsonb, '[[], ["eglon"], ["ehud", "eglon"], ["ehud", "eglon"]]'::jsonb, ARRAY['ehud', 'eglon']::text[], '[{"book": "삿", "from": "3:12", "to": "3:30"}]'::jsonb, -1320, -1320, 'approx', 7, '여리고/모압 경계(전승)', 31.85, 35.5, 'published'),
    ('era_exodus', '유월절: 피로 표시된 문', '이스라엘은 유월절을 준비하며 ‘보호의 표’를 문에 남긴다.', '["가족들이 급히 무교병을 준비한다, 집 안은 숨죽인 긴장", "모세의 지시가 전달된다, 이 밤은 여호와의 유월절이라", "문설주에 표식을 남긴다, 손의 떨림과 결심", "밤, 바깥의 공포와 안의 침묵이 대비된다"]'::jsonb, '[[], ["moses"], [], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "12:1", "to": "12:14"}]'::jsonb, -1446, -1446, 'approx', 7, '고센(전승)', 30.8, 31.85, 'published'),
    ('era_nt_consummation', '최후 심판과 새 하늘 새 땅', '심판이 지나고 새 예루살렘과 영원한 회복이 선포된다.', '["큰 보좌 앞에 모두가 서는 앞쪽에 서 있고, 책들이 펼쳐진다", "처음 하늘과 처음 땅이 지나갔다 선언으로 화면이 전환된다", "새 예루살렘이 내려오는 이미지, 빛과 성벽", "눈물을 씻기시니라는 약속과 함께, 밝은 새 아침으로 끝난다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['john']::text[], '[{"book": "계", "from": "20:11", "to": "20:15"}, {"book": "계", "from": "21:1", "to": "22:5"}]'::jsonb, null, null, 'approx', 7, '밧모섬(추정)', 37.31, 26.55, 'published'),
    ('era_patriarch', '할례 언약: 이름이 바뀌다', '언약의 표가 주어지고 아브라함과 사라의 이름이 바뀐다.', '["하나님의 빛이 임한다", "아브람이 엎드리고, 아브라함으로 불린다", "사래가 사라로 불리며 약속이 구체화된다", "언약의 표가 선포되고 아브라함이 결단한다"]'::jsonb, '[["god"], ["abraham"], ["sarah"], ["abraham"]]'::jsonb, ARRAY['abraham', 'sarah', 'god']::text[], '[{"book": "창", "from": "17:1", "to": "17:27"}]'::jsonb, -2088, -2088, 'approx', 7, '가나안(전승)', 31.5, 35, 'published'),
    ('era_primeval', '홍수 전의 타락: 노아를 주목하다', '폭력으로 가득 찬 세상 속에서 하나님은 노아에게 길을 여신다.', '["혼란과 폭력이 번지는 앞쪽에 서 있고, 거리의 소란", "하나님의 빛이 임한다", "노아가 조용히 방주 설계 도면을 펼친다", "노아가 첫 나무를 자르며 준비를 시작한다"]'::jsonb, '[[], ["god"], ["noah"], ["noah"]]'::jsonb, ARRAY['god', 'noah']::text[], '[{"book": "창", "from": "6:1", "to": "6:22"}]'::jsonb, -2500, -2500, 'approx', 7, '근동', 33, 44, 'published'),
    ('era_judges', '기드온의 소명: 두려움 속의 표징', '기드온은 두려움 속에서 부르심을 받고, 표징으로 확신을 얻는다.', '["기드온이 포도주 틀에서 몰래 타작한다, 눈치 보는 표정", "큰 용사여라는 부름에 기드온이 어이없어한다", "기드온이 제물을 놓고 기다린다, 순간 불빛이 일어난다", "기드온이 숨을 몰아쉬며 무릎 꿇는다"]'::jsonb, '[["gideon"], ["gideon"], ["gideon"], ["gideon"]]'::jsonb, ARRAY['gideon']::text[], '[{"book": "삿", "from": "6:11", "to": "6:24"}]'::jsonb, -1160, -1160, 'approx', 8, '오브라(전승)', 32.5, 35.3, 'published'),
    ('era_monarchy', '다윗이 사울을 살려주다: 동굴의 순간', '다윗은 복수의 기회를 놓아주며 ‘손대지 않음’으로 자신의 길을 지킨다.', '["다윗 일행이 동굴 안에 몸을 숨기고 긴장한 채 웅크리고 있다", "사울이 다윗 일행이 숨어 있는 동굴 안으로 무심코 들어오는 모습", "다윗이 동굴 안에서 사울의 옷자락만 조용히 자른다", "동굴 안에서 사울이 울며 고개를 숙이고, 다윗은 괜찮다고 손짓하는 장면"]'::jsonb, '[["david"], ["saul"], ["david", "saul"], ["david", "saul"]]'::jsonb, ARRAY['david', 'saul']::text[], '[{"book": "삼상", "from": "24:1", "to": "24:22"}]'::jsonb, -1012, -1012, 'approx', 8, '엔게디(전승)', 31.46, 35.39, 'published'),
    ('era_primeval', '방주와 홍수: 문이 닫히다', '구원의 문이 닫히고 물이 땅을 덮는다.', '["노아 가족이 방주로 들어가고 짐승들이 따라 들어온다", "문이 닫히는 둔탁한 소리, 바깥 소리가 끊긴다", "폭우와 물기둥, 방주가 크게 흔들리며 떠오른다", "물이 잦아들고 방주 문이 열리며 새 땅이 보인다"]'::jsonb, '[["noah"], [], [], []]'::jsonb, ARRAY['noah']::text[], '[{"book": "창", "from": "7:1", "to": "8:19"}]'::jsonb, -2500, -2499, 'approx', 8, '방주(근동)', 33, 44, 'published'),
    ('era_nt_apostolic', '사울 회심: 다메섹의 빛', '박해자 사울은 부르심을 만나고 방향이 완전히 바뀐다.', '["사울이 공문을 들고 다메섹으로 달린다, 눈빛이 날카롭다", "강한 빛이 비치고 사울이 쓰러진다, 사울아, 네가 어찌하여", "눈먼 사울이 손에 이끌려 들어간다, 도시가 낯설어진다", "아나니아가 안수하자 사울이 다시 보고, 조용히 일어난다"]'::jsonb, '[["saul"], ["saul"], ["saul"], ["saul", "ananias"]]'::jsonb, ARRAY['saul', 'ananias']::text[], '[{"book": "행", "from": "9:1", "to": "9:19"}]'::jsonb, 35, 35, 'approx', 8, '다메섹', 33.51, 36.29, 'published'),
    ('era_exile_return', '사자굴: 멈추지 않는 기도', '금지령 속에서도 다니엘은 기도를 멈추지 않고, 구원은 새벽에 드러난다.', '["관원들이 계략을 꾸민다, 그의 하나님을 걸어야 한다", "다니엘이 창을 열고 기도한다, 소문이 퍼진다", "신하들이 왕에게 말하고, 왕이 괴로워하는 장면", "새벽, 다니엘의 목소리가 들린다, 하나님이 사자들의 입을 막으셨습니다"]'::jsonb, '[[], ["daniel"], [], ["daniel"]]'::jsonb, ARRAY['daniel']::text[], '[{"book": "단", "from": "6:1", "to": "6:28"}]'::jsonb, -537, -537, 'approx', 8, '바벨론/메대-바사(전승)', 32.55, 44.42, 'published'),
    ('era_patriarch', '세 손님: 웃음과 약속', '손님을 맞이한 아브라함의 집에 불가능해 보이던 약속이 다시 선포된다.', '["더운 낮, 아브라함이 세 손님을 보고 장막 밖으로 뛰어나가 맞이한다", "사라가 장막 안에서 급히 음식을 준비하며 긴장한 표정을 짓는다", "사라가 장막 뒤에서 숨은 채 웃음을 참지 못한다", "하나님의 빛이 아브라함 앞에서 머물고, 장막 뒤에서 그 말을 듣던 사라의 얼굴이 굳는다"]'::jsonb, '[["abraham"], ["sarah"], ["sarah"], ["abraham", "god", "sarah"]]'::jsonb, ARRAY['abraham', 'sarah', 'god']::text[], '[{"book": "창", "from": "18:1", "to": "18:15"}]'::jsonb, -2087, -2087, 'approx', 8, '마므레(헤브론, 전승)', 31.53, 35.1, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_nt_public_ministry', '제자 부르심: 그물을 버리다', '예수님은 어부들을 부르시고 그들은 삶의 방향을 바꾼다.', '["호숫가, 그물을 손질하는 어부들, 예수가 다가온다", "베드로가 멈칫한다", "배가 뒤로 밀리며 그물이 가득하다", "그들이 그물을 내려놓고 예수를 따라 길을 걷는다"]'::jsonb, '[["jesus"], ["peter"], [], ["jesus"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james', 'john']::text[], '[{"book": "막", "from": "1:16", "to": "1:20"}, {"book": "마", "from": "4:18", "to": "4:22"}, {"book": "눅", "from": "5:1", "to": "5:11"}, {"book": "요", "from": "1:35", "to": "1:51"}]'::jsonb, 27, 27, 'approx', 8, '갈릴리 호수(가버나움 근처)', 32.88, 35.57, 'published'),
    ('era_exodus', '출애굽의 밤: 떠나라는 명령', '마침내 바로가 떠나라 말하고, 이스라엘은 급히 길을 나선다.', '["밤의 애굽, 집집마다 초태생의 죽음으로 사람들이 침상 곁에서 오열한다, 시신은 직접적으로 보이지 않고 슬픔과 충격만 절제되게 표현", "밤에 바로가 모세에게 당장 나가라고 말한다, 궁정은 무겁고 다급하다", "모세와 백성들이 반죽과 짐을 들고 애굽을 떠나 광야로 나아간다", "불기둥/구름기둥, 이스라엘이 전진한다"]'::jsonb, '[[], ["moses", "pharaoh"], ["moses"], []]'::jsonb, ARRAY['moses', 'pharaoh']::text[], '[{"book": "출", "from": "12:29", "to": "13:22"}]'::jsonb, -1446, -1446, 'approx', 8, '애굽 → 광야(전승)', 30.8, 31.85, 'published'),
    ('era_nt_apostolic', '고넬료: 이방인에게도', '베드로는 편견을 넘어 이방인에게도 성령이 임함을 목격한다.', '["고넬료가 기도하다 환상을 보고 사람을 보낸다", "베드로가 환상 속 천을 보고 멈칫한다", "베드로가 결연한 표정으로 선다", "성령의 표징에 모두가 놀란다, 베드로가 고개를 끄덕인다"]'::jsonb, '[[], ["peter"], ["peter"], ["peter"]]'::jsonb, ARRAY['peter', 'cornelius']::text[], '[{"book": "행", "from": "10:1", "to": "10:48"}, {"book": "행", "from": "11:1", "to": "11:18"}]'::jsonb, 38, 38, 'approx', 9, '가이사랴', 32.5, 34.89, 'published'),
    ('era_exile_return', '고레스 칙령: 돌아가라', '고레스의 칙령으로 귀환의 문이 열리고 성전 재건이 시작된다.', '["칙령이 낭독된다, 사람들이 서로를 바라본다", "누군가 울음을 터뜨린다, 돌아갈 수 있다", "짐을 싸고 긴 행렬이 길을 나선다", "멀리 예루살렘 방향으로 해가 뜬다, 희망의 톤"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['cyrus']::text[], '[{"book": "스", "from": "1:1", "to": "1:4"}]'::jsonb, -538, -538, 'approx', 9, '바벨론 → 예루살렘(전승)', 32.55, 44.42, 'published'),
    ('era_judges', '기드온 300: 횃불과 나팔', '적은 수의 300명이 공포를 뒤집는 소리로 승리를 만든다.', '["병력이 줄어드는 앞쪽에 서 있고, 기드온이 놀라지만 고개를 끄덕인다", "밤, 300명이 항아리·횃불·나팔을 든다", "여호와와 기드온의 칼!, 항아리를 깨뜨리고 빛이 터진다", "이스라엘이 추격한다"]'::jsonb, '[["gideon"], [], ["gideon"], []]'::jsonb, ARRAY['gideon']::text[], '[{"book": "삿", "from": "7:1", "to": "7:22"}]'::jsonb, -1160, -1160, 'approx', 9, '미디안 진(전승)', 32.35, 35.55, 'published'),
    ('era_primeval', '무지개 언약: 다시는', '하나님은 무지개로 언약을 표징하시며 새 출발을 약속하신다.', '["노아가 제단을 쌓고 고개 숙인다, 연기가 위로 오른다", "하나님의 빛이 임한다", "비구름이 걷히고 햇빛만 비치며 사람은 보이지 않는다", "무지개가 선명하게 걸리고 노아가 올려다본다"]'::jsonb, '[["noah"], ["god"], [], ["noah"]]'::jsonb, ARRAY['god', 'noah']::text[], '[{"book": "창", "from": "8:20", "to": "9:17"}]'::jsonb, -2499, -2499, 'approx', 9, '아라랏 산지(전승)', 39.7, 44.3, 'published'),
    ('era_monarchy', '사울의 최후: 엔돌과 길보아', '사울의 두려움은 어두운 선택으로 이어지고 결국 전장에서 끝난다.', '["블레셋 군대를 보고 사울이 떤다, 하늘은 침묵처럼 보인다", "밤, 사울이 엔돌로 향한다, 불안한 발걸음", "예언이 사울을 무너뜨린다, 사울이 바닥에 주저앉는다", "길보아 전투, 사울이 쓰러지고 왕정의 첫 장이 닫힌다"]'::jsonb, '[["saul"], ["saul"], ["saul"], ["saul"]]'::jsonb, ARRAY['saul']::text[], '[{"book": "삼상", "from": "28:5", "to": "28:20"}, {"book": "삼상", "from": "31:1", "to": "31:6"}]'::jsonb, -1010, -1010, 'approx', 9, '길보아 산(전승)', 32.49, 35.38, 'published'),
    ('era_nt_public_ministry', '산상수훈: 복 있는 사람', '예수님은 하나님 나라의 새로운 가치와 삶의 기준을 선포하신다.', '["산비탈에 사람들이 모여 앉고, 예수가 자리에 앉는다", "복이 있나니, 선포가 이어지고 사람들의 표정이 바뀐다", "너희는 빛이라 말하며 예수가 손으로 도시를 가리킨다", "반석 위에 집을 짓는 자 비유로 마무리되고 군중이 놀란다"]'::jsonb, '[["jesus"], [], ["jesus"], []]'::jsonb, ARRAY['jesus']::text[], '[{"book": "마", "from": "5:1", "to": "7:29"}]'::jsonb, 28, 28, 'approx', 9, '갈릴리 산지(전승)', 32.85, 35.55, 'published'),
    ('era_patriarch', '소돔을 위한 중보: 숫자가 줄어들다', '아브라함은 의인을 위해 담대하게 간구하며 하나님의 공의를 붙든다.', '["멀리 소돔 방향을 바라보는 아브라함의 실루엣", "아브라함이 하나님의 빛 앞에서 간절히 중보를 시작한다", "아브라함이 땅에 엎드려 하나님께 간절히 기도한다", "기도를 마친 아브라함이 무거운 발걸음으로 자기 장막 쪽으로 돌아간다"]'::jsonb, '[["abraham"], ["abraham", "god"], ["abraham", "god"], ["abraham"]]'::jsonb, ARRAY['abraham', 'god']::text[], '[{"book": "창", "from": "18:16", "to": "18:33"}]'::jsonb, -2087, -2087, 'approx', 9, '마므레(전승)', 31.53, 35.1, 'published'),
    ('era_exodus', '홍해: 길이 열리다', '막다른 길에서 하나님이 길을 여시고 백성은 두려움에서 믿음으로 옮겨간다.', '["뒤엔 군대, 앞엔 바다, 백성이 원망하며 멈춰 선다", "모세가 두 손을 들어 다급하게 몸짓한다", "갈라진 물 벽 사이로 모세가 앞서고 백성들이 아이들과 짐을 이끌며 건너간다", "모두가 건넌 뒤, 물이 합쳐지고 백성은 숨을 몰아쉬며 찬양한다"]'::jsonb, '[[], ["moses"], ["moses"], []]'::jsonb, ARRAY['moses', 'pharaoh']::text[], '[{"book": "출", "from": "14:10", "to": "14:31"}]'::jsonb, -1446, -1446, 'approx', 9, '홍해/갈대바다(전승)', 29.5, 34.9, 'published'),
    ('era_monarchy', '다윗 즉위: 한 왕국으로', '다윗은 점진적으로 왕이 되어 마침내 온 이스라엘을 다스린다.', '["사무엘이 다윗에게 기름을 붓는 장면, 사람들의 시선이 모인다", "긴 갈등의 시간, 짧은, 서로 다른 진영이 흔들린다", "장로들이 다윗 앞에 선다", "예루살렘에 들어서는 다윗, 도시의 문이 열리고 새 시작이 열린다"]'::jsonb, '[["david", "samuel"], [], ["david"], ["david"]]'::jsonb, ARRAY['david', 'samuel']::text[], '[{"book": "삼하", "from": "2:1", "to": "2:7"}, {"book": "삼하", "from": "5:1", "to": "5:10"}]'::jsonb, -1005, -1000, 'approx', 10, '헤브론 → 예루살렘(전승)', 31.53, 35.1, 'published'),
    ('era_exodus', '마라: 쓴 물이 달아지다', '광야의 첫 위기에서 하나님은 쓴 물을 바꾸며 백성을 가르치신다.', '["사람들이 물을 마시고 뱉는다, 써서 못 마신다!", "원망이 커지고 모세가 한쪽으로 물러나 기도한다", "모세가 지시받은 나무를 물에 던진다", "사람들이 다시 물을 마신다, 표정이 풀리며 행렬이 움직인다"]'::jsonb, '[[], ["moses"], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "15:22", "to": "15:27"}]'::jsonb, -1446, -1446, 'approx', 10, '마라(전승)', 28.7, 33.4, 'published'),
    ('era_primeval', '바벨탑: 언어가 갈라지다', '자기 이름을 세우려던 계획은 언어의 혼잡으로 멈춘다.', '["배경과 분위기만 보이는", "탑이 올라가며 사람들의 얼굴이 도취된다", "갑자기 말이 안 통한다, 손짓만 커지고 싸움이 난다", "공사가 멈추고 사람들이 각기 다른 방향으로 흩어진다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY['god']::text[], '[{"book": "창", "from": "11:1", "to": "11:9"}]'::jsonb, -2200, -2200, 'approx', 10, '시날 평지(바벨론, 전승)', 32.54, 44.42, 'published'),
    ('era_patriarch', '소돔 멸망과 롯 구출', '도시는 심판을 받고 롯의 가족은 급히 나오지만 뒤돌아봄이 비극을 만든다.', '["밤의 소돔에서 롯이 두 천사를 자기 집 안으로 급히 들여 숨겨 준다", "아직 불타지 않은 도시를 뒤로 두고 롯이 아내와 두 딸을 재촉하며 허둥지둥 달린다", "롯과 아내와 두 딸이 도망가고 뒤편 도시에는 불길과 연기가 치솟기 시작한다", "롯의 아내는 소금기둥이 되고, 롯과 두 딸은 불타는 성을 뒤로한 채 달아난다"]'::jsonb, '[["lot"], ["lot"], ["lot"], ["lot"]]'::jsonb, ARRAY['lot']::text[], '[{"book": "창", "from": "19:1", "to": "19:29"}]'::jsonb, -2086, -2086, 'approx', 10, '소돔 일대(사해 남부, 전승)', 31.2, 35.5, 'published'),
    ('era_judges', '아비멜렉: 왕 노릇의 비극', '권력을 움켜쥔 아비멜렉의 길은 폭력과 파멸로 끝난다.', '["욕심 가득한 얼굴의 아비멜렉이 형제들을 죽인 뒤 차갑게 서 있고, 뒤에는 형제들이 쓰러져 있다", "한 아이가 사람들에게 나무들이 서로 대화하는 비유를 들려준다", "욕심 가득한 아비멜렉이 여러 전쟁을 일으켜 많은 사람이 쓰러지고 성읍이 불타는 모습", "한 여인이 성 위에서 맷돌을 떨어뜨리고, 아래의 아비멜렉은 치명상을 입고 무너진다"]'::jsonb, '[["abimelech"], [], ["abimelech"], ["abimelech"]]'::jsonb, ARRAY['abimelech']::text[], '[{"book": "삿", "from": "9:1", "to": "9:57"}]'::jsonb, -1135, -1135, 'approx', 10, '세겜(전승)', 32.22, 35.28, 'published'),
    ('era_nt_apostolic', '안디옥 교회: 선교의 출발', '안디옥 교회는 금식과 기도 가운데 바울과 바나바를 파송한다.', '["금식과 기도 중 공동체가 조용히 고개를 든다", "따로 세우라는 인도에 모두가 숨을 삼킨다", "안수 앞쪽에 서 있고, 바울과 바나바가 서로를 바라본다", "배가 있는 항구를 향해 걸어 나간다"]'::jsonb, '[[], [], ["barnabas", "paul"], []]'::jsonb, ARRAY['barnabas', 'paul']::text[], '[{"book": "행", "from": "13:1", "to": "13:3"}]'::jsonb, 46, 46, 'approx', 10, '안디옥(시리아)', 36.202, 36.16, 'published'),
    ('era_exile_return', '제단과 예배 회복', '폐허 위에서 먼저 예배가 회복되고 제단이 다시 세워진다.', '["returnees가 returnees가 returnees가 손에 돌을 들고 있다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 제단을 쌓고 불을 밝힌다, 모두가 숨을 죽인다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 제사가 드려지고, 오래 잊었던 노래가 다시 울린다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 어떤 이는 울고 어떤 이는 기뻐한다, 처음이 다시 시작된다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "스", "from": "3:1", "to": "3:6"}]'::jsonb, -537, -537, 'approx', 10, '예루살렘(성전 터)', 31.78, 35.23, 'published'),
    ('era_nt_public_ministry', '폭풍을 잠잠케 하심', '두려움 속 제자들 앞에서 예수님은 바람과 물결을 잠잠케 하신다.', '["배 위, 폭풍이 몰아치고 제자들이 물을 퍼낸다", "제자들이 두 손을 들어 다급하게 몸짓한다", "예수님이 앞쪽에 서서 표정과 몸짓이 또렷하게 보인다", "제자들이 서로를 바라본다, 두려움과 놀람이 엇갈린다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "4:35", "to": "4:41"}, {"book": "마", "from": "8:23", "to": "8:27"}, {"book": "눅", "from": "8:22", "to": "8:25"}]'::jsonb, 28, 28, 'approx', 10, '갈릴리 호수', 32.83, 35.59, 'published'),
    ('era_nt_apostolic', '1차 선교(1): 구브로 살라미–바보', '바울과 바나바는 구브로에서 복음을 전하며 첫 여정을 시작한다.', '["배가 항구에 닿고, 회당으로 향하는 발걸음이 빠르다", "반대와 긴장이 오가지만, 복음이 선포된다", "분위기가 뒤집히는 순간, 총독의 표정이 달라진다", "바울이 지도를 펼치며 다음 목적지를 가리킨다"]'::jsonb, '[[], [], [], ["paul"]]'::jsonb, ARRAY['paul', 'barnabas', 'john_mark']::text[], '[{"book": "행", "from": "13:4", "to": "13:12"}]'::jsonb, 46, 46, 'approx', 11, '구브로(살라미 → 바보)', 34.775, 32.424, 'published'),
    ('era_exodus', '만나와 메추라기: 하늘의 양식', '먹을 것이 없던 광야에서 하나님은 매일의 양식을 주시며 ‘신뢰’를 훈련하신다.', '["백성이 불평한다, 애굽의 냄비가 그립다", "아침, 땅 위에 하얀 것들이 덮인다, 이것이 무엇이냐?", "모세가 결연한 표정으로 선다", "집 안에 쌓아 둔 만나가 벌레가 생기고 냄새가 나며 썩어 간다, 사람들이 놀라 뒤로 물러선다"]'::jsonb, '[[], [], ["moses"], []]'::jsonb, ARRAY['moses']::text[], '[{"book": "출", "from": "16:1", "to": "16:36"}]'::jsonb, -1446, -1446, 'approx', 11, '신 광야(전승)', 28.9, 33.3, 'published'),
    ('era_exile_return', '성전 재건: 방해와 완공', '방해가 이어지지만 성전은 결국 다시 세워진다.', '["주변 사람들이 접근한다, 긴장이 감돈다", "거절 후 방해와 협박이 시작된다, 작업이 멈춘다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 다시 망치 소리, 돌이 쌓이고 골조가 올라간다", "returnees가 returnees가 returnees가 returnees가 returnees가 returnees가 완공 예배, 사람들의 얼굴에 눈물과 웃음이 함께 있다"]'::jsonb, '[[], [], [], []]'::jsonb, ARRAY[]::text[], '[{"book": "스", "from": "4:1", "to": "4:6"}, {"book": "스", "from": "6:13", "to": "6:22"}]'::jsonb, -536, -516, 'approx', 11, '예루살렘', 31.78, 35.23, 'published'),
    ('era_patriarch', '아브라함과 아비멜렉: 오해와 보호', '아브라함의 두려움이 다시 거짓을 낳지만 하나님이 사라를 지키신다.', '["그랄 입성, 아브라함과 사라가 결연한 표정으로 선다", "아비멜렉의 궁정, 사라가 끌려가는 긴장", "밤의 꿈, 경고를 받은 아비멜렉이 놀라 깬다", "사라가 돌아오고, 아브라함은 변명 대신 침묵한다"]'::jsonb, '[["abraham", "sarah"], ["sarah", "abimelech"], ["abimelech"], ["abraham", "sarah"]]'::jsonb, ARRAY['abraham', 'sarah', 'abimelech']::text[], '[{"book": "창", "from": "20:1", "to": "20:18"}]'::jsonb, -2085, -2085, 'approx', 11, '그랄(전승)', 31.37, 34.45, 'published'),
    ('era_nt_public_ministry', '야이로의 딸과 혈루증 여인', '절박한 믿음이 이어지는 길 위에서 예수님은 치유와 생명의 능력을 보이신다.', '["야이로가 무릎 꿇고 간청한다", "군중 속 여인이 예수의 옷자락을 만지고 멈춘다", "예수 앞쪽에 서 있고, 여인이 울며 고개 숙인다", "집에 도착해 달리다굼이 울리고, 아이가 일어나는 순간 모두가 숨을 삼킨다"]'::jsonb, '[[], ["jesus"], ["jesus"], []]'::jsonb, ARRAY['jesus', 'jairus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "5:21", "to": "5:43"}, {"book": "마", "from": "9:18", "to": "9:26"}, {"book": "눅", "from": "8:40", "to": "8:56"}]'::jsonb, 28, 28, 'approx', 11, '가버나움(전승)', 32.88, 35.57, 'published'),
    ('era_monarchy', '언약궤 입성: 춤과 기쁨', '다윗은 언약궤가 들어올 때 온 마음으로 기뻐하며 예배한다.', '["나팔 소리와 함께 행렬이 예루살렘으로 들어온다", "다윗이 체면보다 기쁨을 택해 춤춘다", "언약궤 앞에서 다윗이 멈추어 고개 숙인다", "다윗이 백성에게 음식을 나누며 축복하고, 도시는 환호로 찬다"]'::jsonb, '[[], ["david"], ["david"], ["david"]]'::jsonb, ARRAY['david']::text[], '[{"book": "삼하", "from": "6:12", "to": "6:19"}]'::jsonb, -1000, -1000, 'approx', 11, '예루살렘', 31.78, 35.22, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;

with seed_events (era_code, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status) as (
  values
    ('era_judges', '입다: 서원과 상처', '입다는 승리를 원하며 서원을 하지만, 그 말은 깊은 상처를 남긴다.', '["전쟁 전, 입다가 혼자 서원하며 중얼거린다", "전투의 승전 소식, 사람들이 환호한다", "집 문이 열리고 가장 먼저 달려나온 딸을 보고 입다의 얼굴이 굳는다", "입다와 딸이 침묵 속에 마주 서 있고, 서원의 무게가 장면을 누른다"]'::jsonb, '[["jephthah"], [], ["jephthah"], ["jephthah"]]'::jsonb, ARRAY['jephthah']::text[], '[{"book": "삿", "from": "11:29", "to": "11:40"}]'::jsonb, -1100, -1100, 'approx', 11, '길르앗(전승)', 32, 35.7, 'published'),
    ('era_nt_apostolic', '1차 선교(2): 비시디아 안디옥', '바울은 회당에서 설교하고, 복음은 이방인에게 크게 확장된다.', '["회당, 사람들이 바울의 말을 기다리며 숨죽인다", "설교 후 이방인들이 기뻐하며 몰려든다", "반대가 커지고 도시의 공기가 갈라진다", "두 사람은 먼지를 털고 다음 도시로 떠난다"]'::jsonb, '[["paul"], [], [], []]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "13:13", "to": "13:52"}]'::jsonb, 46, 46, 'approx', 12, '비시디아 안디옥(소아시아)', 38.35, 31.18, 'published'),
    ('era_monarchy', '다윗 언약: 집을 세우리라', '하나님은 다윗에게 ‘네 집과 왕위를 견고케 하겠다’는 약속을 주신다.', '["다윗이 결연한 표정으로 선다, 나는 백향목에 거하나, 나단이 듣는다", "밤, 나단이 말씀을 듣고 얼굴이 굳는다, 경외", "다윗과 나단이 엄숙한 표정으로 손짓한다", "다윗이 무릎 꿇고 기도한다, 약속의 무게가 방에 남는다"]'::jsonb, '[["david", "nathan"], ["nathan"], ["david", "nathan"], ["david"]]'::jsonb, ARRAY['david', 'nathan']::text[], '[{"book": "삼하", "from": "7:1", "to": "7:17"}]'::jsonb, -995, -995, 'approx', 12, '예루살렘', 31.78, 35.22, 'published'),
    ('era_judges', '삼손: 힘의 비밀과 마지막 기도', '삼손은 은사를 남용하다 무너지고, 마지막에 하나님께 부르짖는다.', '["배경과 분위기만 보이는 앞쪽에 서 있고, 삼손은 웃으며 넘기다 점점 지친다", "비밀을 말하는 순간, 공기가 싸늘해진다, 삼손의 눈빛이 흔들린다", "붙잡힌 삼손이 어둠 속에서 고개를 숙인다, 침묵", "삼손이 마지막으로 기도한다, 나를 기억하소서"]'::jsonb, '[["samson", "delilah"], ["samson", "delilah"], ["samson"], ["samson"]]'::jsonb, ARRAY['samson', 'delilah']::text[], '[{"book": "삿", "from": "16:4", "to": "16:31"}]'::jsonb, -1080, -1080, 'approx', 12, '블레셋 지역(가사/소렉, 전승)', 31.5, 34.45, 'published'),
    ('era_exodus', '아말렉 전투: 팔이 내려갈 때', '전투의 승패는 숫자가 아니라 ‘붙드는 손’에서 드러난다.', '["여호수아가 병력을 정리하고 달려나간다", "언덕 위 모세가 손을 들자 이스라엘이 밀어붙인다", "아론과 훌이 양쪽에서 받친다", "해 질 무렵 승리, 모세가 결연한 표정으로 선다"]'::jsonb, '[["joshua"], ["moses"], ["moses", "aaron"], ["moses"]]'::jsonb, ARRAY['moses', 'joshua', 'aaron']::text[], '[{"book": "출", "from": "17:8", "to": "17:16"}]'::jsonb, -1446, -1446, 'approx', 12, '르비딤(전승)', 28.75, 33.35, 'published'),
    ('era_exile_return', '에스더: 왕후가 되다', '에스더는 예상치 못한 자리에서 왕후가 되어 때를 기다린다.', '["에스더가 왕후가 되기 전, 다른 후보들과 함께 궁정에 모인 모습", "왕관이 없는 후보의 모습인 에스더가 왕 앞에 선다, 방 안이 숨을 죽인다", "왕이 왕관을 씌운다, 에스더의 얼굴이 굳어지며 책임을 느낀다", "모르드개가 멀리서 지켜본다, 때가 올 것 같은 눈빛"]'::jsonb, '[["esther"], ["esther"], ["esther"], ["mordecai"]]'::jsonb, ARRAY['esther', 'mordecai']::text[], '[{"book": "에", "from": "2:5", "to": "2:18"}]'::jsonb, -480, -480, 'approx', 12, '수산 궁(페르시아)', 32.19, 48.26, 'published'),
    ('era_nt_public_ministry', '오병이어', '작은 나눔이 시작점이 되어 많은 사람이 먹고 남는다.', '["제자들이 결연한 표정으로 선다", "제자들이 당황한다", "떡과 물고기가 들려오고, 예수가 축사하며 떼어 준다", "사람들이 배부르고 바구니가 쌓인다, 제자들이 말없이 서로를 본다"]'::jsonb, '[["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"], ["jesus"], ["peter", "andrew", "james_zebedee", "john", "philip", "bartholomew", "matthew", "thomas", "james_alphaeus", "thaddaeus", "simon_zealot", "judas"]]'::jsonb, ARRAY['jesus', 'peter', 'andrew', 'james_zebedee', 'john', 'philip', 'bartholomew', 'matthew', 'thomas', 'james_alphaeus', 'thaddaeus', 'simon_zealot', 'judas']::text[], '[{"book": "막", "from": "6:34", "to": "6:44"}, {"book": "마", "from": "14:13", "to": "14:21"}, {"book": "눅", "from": "9:10", "to": "9:17"}, {"book": "요", "from": "6:1", "to": "6:13"}]'::jsonb, 29, 29, 'approx', 12, '갈릴리 호숫가 들판(전승)', 32.84, 35.54, 'published'),
    ('era_patriarch', '이삭 탄생과 하갈 추방', '약속의 아들이 태어나지만 가정의 갈등은 하갈을 광야로 내몬다.', '["사라가 아기 이삭을 안고 환하게 웃는다", "사라의 차가운 눈빛이 앞쪽에 크게 보이고, 뒤편에서는 열 살쯤 된 이스마엘이 어린 이삭을 놀린다", "하갈이 물가죽을 들고 열 살쯤 된 이스마엘과 함께 집을 떠난다", "하갈이 우물 앞에서 열 살쯤 된 이스마엘을 안아 일으켜 세운다"]'::jsonb, '[["sarah", "isaac"], ["sarah", "isaac", "ishmael"], ["hagar", "ishmael"], ["hagar", "ishmael"]]'::jsonb, ARRAY['abraham', 'sarah', 'isaac', 'hagar', 'ishmael']::text[], '[{"book": "창", "from": "21:1", "to": "21:21"}]'::jsonb, -2066, -2066, 'approx', 12, '브엘세바 주변(전승)', 31.25, 34.8, 'published'),
    ('era_nt_apostolic', '1차 선교(3): 이고니온', '표적과 논쟁이 함께 일어나고, 박해의 조짐이 짙어진다.', '["많은 사람이 믿지만, 반대가 조직적으로 커진다", "두 사람이 서로 눈빛을 맞추고 도시를 떠날 결심을 한다"]'::jsonb, '[[], []]'::jsonb, ARRAY['paul', 'barnabas']::text[], '[{"book": "행", "from": "14:1", "to": "14:7"}]'::jsonb, 47, 47, 'approx', 13, '이고니온(코니아)', 37.874, 32.493, 'published')
)
insert into events (era_id, title, summary, story_scenes, scene_characters, character_codes, bible_refs, start_year, end_year, time_precision, story_index, place_name, lat, lng, status)
select
  e.id,
  s.title,
  s.summary,
  s.story_scenes,
  s.scene_characters,
  s.character_codes,
  s.bible_refs,
  s.start_year,
  s.end_year,
  s.time_precision,
  s.story_index,
  s.place_name,
  s.lat,
  s.lng,
  s.status
from seed_events s
join eras e on e.code = s.era_code
on conflict (era_id, story_index) do update set
  title = excluded.title,
  summary = excluded.summary,
  story_scenes = excluded.story_scenes,
  scene_characters = excluded.scene_characters,
  character_codes = excluded.character_codes,
  bible_refs = excluded.bible_refs,
  start_year = excluded.start_year,
  end_year = excluded.end_year,
  time_precision = excluded.time_precision,
  place_name = excluded.place_name,
  lat = excluded.lat,
  lng = excluded.lng,
  status = excluded.status
;


alter table events enable trigger trg_notify_on_new_event;
commit;
