-- Generated by tools/seed/build_landmarks_seed_sql.py
-- Target table: landmarks (시대별 랜드마크 정적 카탈로그)
begin;

-- Drop landmarks rows not present in current assets/landmarks/landmarks.json
delete from landmarks where code not in ('ai', 'antioch_pisidia', 'antioch_syria', 'assos', 'athens', 'babylon', 'beersheba', 'berea', 'bethany', 'bethel', 'bethlehem', 'bethsaida', 'brook_cherith', 'burning_bush', 'caesarea_maritima', 'caesarea_palace', 'caesarea_philippi', 'cana', 'capernaum', 'chorazin', 'city_of_david', 'corinth', 'damascus', 'dead_sea', 'decapolis', 'dothan', 'elah_valley', 'endor', 'ephesus', 'garden_of_eden', 'gehenna', 'gethsemane', 'gilgal', 'golgotha', 'goshen', 'haran', 'hazor', 'hebron', 'heshbon', 'jericho', 'jerusalem_damascus_gate', 'jerusalem_temple', 'joppa', 'jordan_river', 'judean_wilderness', 'kadesh_barnea', 'kebar_river', 'kishon_river', 'laodicea', 'lystra', 'machpelah', 'malta', 'megiddo', 'miletus', 'mizpah', 'mount_ararat', 'mount_carmel', 'mount_gilboa', 'mount_hermon', 'mount_moriah', 'mount_nebo', 'mount_sinai', 'mount_tabor', 'nazareth', 'nineveh', 'patmos', 'peniel', 'pergamon', 'philadelphia', 'philippi', 'rachel_tomb', 'rameses', 'red_sea', 'rephidim', 'rome', 'salamis_cyprus', 'samaria', 'sardis', 'sea_of_galilee', 'shechem', 'shiloh', 'smyrna', 'sodom', 'susa', 'sychar_well', 'tarsus', 'thessalonica', 'thyatira', 'tower_of_babel', 'troas', 'tyre', 'ur', 'wilderness_of_paran', 'wilderness_of_zin', 'zarephath');

with seed_landmarks (code, name, description, emoji, category, lat, lng, display_priority, era_codes, related_event_codes, is_active) as (
  values
    ('ai', '아이성', '여리고 다음 정복 시도에서 아간의 죄로 패배했다가 재공격으로 함락된 성 (수 7-8장).', '⚔️', 'battle', 31.917, 35.27, 2, ARRAY['era_judges']::text[], ARRAY['joshua', 'achan']::text[], true),
    ('antioch_pisidia', '비시디아 안디옥', '바울이 1차 선교 여행에서 회당에서 메시아를 선포한 곳. 박해 후 쫓겨남 (행 13:13-52).', '📜', 'city', 38.31, 31.19, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'barnabas']::text[], true),
    ('antioch_syria', '안디옥 (수리아)', '초대 교회의 선교 출발지. "그리스도인"이라는 이름이 처음 불린 곳. 바울의 1·2·3차 선교 여행 출발지 (행 11장, 13장).', '⛪', 'city', 36.2055, 36.1611, 0, ARRAY['era_nt_apostolic', 'era_nt_post_apostolic']::text[], ARRAY['paul', 'barnabas', 'peter']::text[], true),
    ('assos', '앗소', '바울이 3차 선교 여행 끝에 도보로 이동해 일행과 만난 항구. 거기서 배를 타고 미틸레네로 향함 (행 20:13-14).', '🚶', 'city', 39.49, 26.34, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('athens', '아덴 (아테네)', '바울이 아레오바고에서 "알지 못하는 신에게"라는 단을 보고 참 하나님을 선포한 곳 (행 17:16-34).', '🏛️', 'city', 37.975, 23.735, 1, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('babylon', '바벨론', '유다 백성이 포로로 끌려간 제국의 수도. 다니엘과 에스겔의 무대 (왕하 25장, 단 1장).', '🗼', 'city', 32.5421, 44.4209, 0, ARRAY['era_exile_return']::text[], ARRAY['daniel', 'ezekiel', 'jeremiah']::text[], true),
    ('beersheba', '브엘세바', '아브라함과 이삭이 우물을 파고 언약을 맺은 곳. 약속의 땅 남쪽 끝 (창 21:31, 26:33).', '💧', 'city', 31.252, 34.792, 1, ARRAY['era_patriarch', 'era_judges', 'era_monarchy']::text[], ARRAY['abraham', 'isaac', 'samuel']::text[], true),
    ('berea', '베뢰아', '"신사적이라"는 칭송을 받은 사람들이 매일 성경을 상고하던 곳 (행 17:11).', '📖', 'city', 40.525, 22.201, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'silas']::text[], true),
    ('bethany', '베다니', '마리아·마르다·나사로의 마을. 예수께서 나사로를 살리시고 마지막 한 주를 보내신 곳 (요 11장).', '🌿', 'city', 31.771, 35.257, 1, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'lazarus', 'martha', 'mary']::text[], true),
    ('bethel', '벧엘', '야곱이 사다리 꿈을 꾸고 "하나님의 집"이라 부른 곳. 사무엘이 순회 재판한 곳, 후대에는 우상 숭배 자리도 됨 (창 28장, 삼상 7:16, 왕상 12장).', '🪜', 'holy_site', 31.9269, 35.2192, 1, ARRAY['era_patriarch', 'era_judges', 'era_monarchy']::text[], ARRAY['jacob', 'samuel']::text[], true),
    ('bethlehem', '베들레헴', '다윗의 고향이자 예수께서 태어나신 곳. 룻과 보아스의 무대. "떡집"이라는 뜻 (삼상 16장, 룻기, 마 2장).', '⭐', 'city', 31.7054, 35.2024, 0, ARRAY['era_judges', 'era_monarchy', 'era_nt_public_ministry']::text[], ARRAY['david', 'jesus', 'ruth', 'boaz']::text[], true),
    ('bethsaida', '벳새다', '베드로·안드레·빌립의 고향. 예수께서 오병이어 기적을 행하시고 맹인을 고치신 곳 (요 1:44, 막 8:22, 눅 9:10).', '🍞', 'city', 32.91, 35.63, 1, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'peter', 'andrew', 'philip']::text[], true),
    ('brook_cherith', '그릿 시내', '엘리야가 가뭄 중 까마귀가 떡과 고기를 가져다주던 시내. 요단 동편 (왕상 17:2-7).', '🐦', 'water', 32.13, 35.62, 2, ARRAY['era_monarchy']::text[], ARRAY['elijah']::text[], true),
    ('burning_bush', '떨기나무', '하나님이 모세를 불꽃 가운데서 부르신 자리. 시내산 기슭 (출 3장).', '🔥', 'holy_site', 28.5556, 33.9764, 1, ARRAY['era_exodus']::text[], ARRAY['moses']::text[], true),
    ('caesarea_maritima', '가이사랴 (마리티마)', '헤롯이 세운 항구 도시. 베드로가 고넬료에게 복음을 전한 곳, 바울이 2년간 옥에 갇힌 곳 (행 10장, 24-26장).', '⛓️', 'prison', 32.498, 34.893, 1, ARRAY['era_nt_apostolic']::text[], ARRAY['peter', 'paul']::text[], true),
    ('caesarea_palace', '가이사랴 헤롯 궁전', '헤롯이 세운 해변 궁전. 베드로가 고넬료에게 복음을 전했고, 후일 바울이 벨릭스·베스도·아그립바 앞에서 변증한 재판정 (행 10장, 23-26장).', '🏛️', 'prison', 32.504, 34.892, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'peter']::text[], true),
    ('caesarea_philippi', '가이사랴 빌립보', '베드로가 "주는 그리스도시오 살아 계신 하나님의 아들"이라 고백한 곳 (마 16:13-20).', '🗝️', 'city', 33.248, 35.695, 1, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'peter']::text[], true),
    ('cana', '가나', '예수께서 물로 포도주를 만드신 첫 표적의 무대. 갈릴리 지방의 마을 (요 2장).', '🍷', 'city', 32.7464, 35.3399, 1, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'mary']::text[], true),
    ('capernaum', '가버나움', '예수의 갈릴리 사역 본거지. 베드로의 집이 있던 어촌. 백부장의 종을 고치심 (마 4장, 8장).', '🏘️', 'city', 32.881, 35.575, 0, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'peter']::text[], true),
    ('chorazin', '고라신', '예수께서 많은 능력을 행하셨으나 회개하지 않아 화가 선포된 갈릴리 호수 북쪽 마을 (마 11:21).', '🚫', 'city', 32.91, 35.56, 2, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus']::text[], true),
    ('city_of_david', '다윗의 성 / 다윗 무덤', '다윗이 여부스 사람들에게서 빼앗아 수도로 삼은 시온의 옛 성채. 후일 다윗이 묻히고 "다윗의 성에 장사되었다"는 표현이 왕들에게 반복 등장 (삼하 5장, 왕상 2:10).', '🏰', 'tomb', 31.772, 35.236, 1, ARRAY['era_monarchy']::text[], ARRAY['david', 'solomon']::text[], true),
    ('corinth', '고린도', '바울이 1년 6개월 머물며 교회를 세운 무역 도시. 고린도전·후서의 무대 (행 18장).', '📨', 'city', 37.939, 22.918, 0, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'aquila', 'priscilla']::text[], true),
    ('damascus', '다메섹', '사울(바울)이 예수를 만나 회심한 도시. 그리스도인 박해를 위해 향하던 길에서 빛을 보았다 (행 9장).', '💡', 'city', 33.5138, 36.2765, 0, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('dead_sea', '사해 (염해)', '지구상 가장 낮은 호수. 소돔·고모라가 잠겼다는 추정지. 다윗이 사울을 피한 엔게디가 서편에 있음 (창 14장, 삼상 24장).', '🧂', 'water', 31.5, 35.5, 1, ARRAY['era_patriarch', 'era_judges', 'era_monarchy']::text[], ARRAY['abraham', 'lot', 'david']::text[], true),
    ('decapolis', '데가볼리 (열 도시)', '갈릴리 동쪽의 그리스 도시 연합. 예수께서 군대 귀신 들린 자를 고치고 데가볼리 사람들이 그 소문을 듣게 됨 (막 5장).', '🏛️', 'region', 32.5, 35.85, 2, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus']::text[], true),
    ('dothan', '도단', '요셉이 형들에게 팔린 곳. 후일 엘리사가 불 말과 불 병거의 환상을 본 곳 (창 37:17, 왕하 6장).', '🛒', 'city', 32.41, 35.24, 2, ARRAY['era_patriarch', 'era_monarchy']::text[], ARRAY['joseph', 'elisha']::text[], true),
    ('elah_valley', '엘라 골짜기', '다윗이 물매와 돌 다섯 개로 골리앗을 무찌른 전투지 (삼상 17장).', '⚔️', 'battle', 31.69, 34.97, 0, ARRAY['era_monarchy']::text[], ARRAY['david', 'saul']::text[], true),
    ('endor', '엔돌', '사울이 여인 무당을 찾아가 사무엘의 영을 불러낸 곳 (삼상 28장).', '👻', 'monument', 32.62, 35.36, 2, ARRAY['era_monarchy']::text[], ARRAY['saul', 'samuel']::text[], true),
    ('ephesus', '에베소', '바울이 3년간 머물며 사역한 아시아의 중심 도시. 아데미 신전이 있던 곳. 요한계시록 7교회 중 첫째 (행 19장, 계 2장).', '⛪', 'city', 37.949, 27.366, 0, ARRAY['era_nt_apostolic', 'era_nt_consummation']::text[], ARRAY['paul', 'john', 'timothy']::text[], true),
    ('garden_of_eden', '에덴 동산 (전통적 위치)', '아담과 하와가 처음 살던 동산. 티그리스·유프라테스 강 사이로 추정된다 (창 2:8-14).', '🌳', 'holy_site', 33.0, 44.5, 0, ARRAY['era_primeval']::text[], ARRAY['adam', 'eve']::text[], true),
    ('gehenna', '게헨나 (한놈의 골짜기)', '예루살렘 남쪽의 쓰레기 소각 골짜기. 어린이를 우상에게 불사르던 곳. 예수께서 "지옥"의 상징으로 사용하심 (왕하 23:10, 막 9:43).', '🔥', 'holy_site', 31.766, 35.227, 2, ARRAY['era_monarchy', 'era_nt_public_ministry']::text[], ARRAY['jesus']::text[], true),
    ('gethsemane', '겟세마네 / 감람산', '예수께서 잡히시기 전 "이 잔을 옮겨 주옵소서"라 기도한 동산. 또 승천하신 곳 (마 26장, 행 1장).', '🫒', 'holy_site', 31.779, 35.243, 0, ARRAY['era_nt_public_ministry', 'era_nt_apostolic']::text[], ARRAY['jesus', 'peter']::text[], true),
    ('gilgal', '길갈', '요단을 건넌 후 12 돌을 세워 기념한 곳. 사울이 왕으로 세워진 곳이기도 함 (수 4장, 삼상 11:15).', '🪨', 'monument', 31.85, 35.5, 1, ARRAY['era_judges', 'era_monarchy']::text[], ARRAY['joshua', 'samuel', 'saul']::text[], true),
    ('golgotha', '골고다 (해골 언덕)', '예수께서 십자가에 못 박히신 곳. 예루살렘 성벽 바깥 언덕 (마 27장).', '✝️', 'holy_site', 31.7783, 35.2298, 0, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus']::text[], true),
    ('goshen', '고센 땅', '요셉의 가족 70명이 이주해 정착한 이집트 동부의 비옥한 땅. 출애굽 직전 거주지 (창 47장).', '🌾', 'region', 30.78, 31.36, 1, ARRAY['era_patriarch', 'era_exodus']::text[], ARRAY['joseph', 'moses']::text[], true),
    ('haran', '하란', '아브라함이 우르를 떠나 잠시 머문 곳. 야곱이 라반의 집에서 일한 곳이기도 함 (창 11:31, 28:10).', '🏕️', 'city', 36.8589, 39.0314, 1, ARRAY['era_patriarch']::text[], ARRAY['abraham', 'jacob']::text[], true),
    ('hazor', '하솔', '여호수아가 정복한 가나안 북부 최강 도시. 후에 사사 시대에 야빈 왕이 다시 일어나 압제. 솔로몬이 재건축 (수 11장, 삿 4장, 왕상 9장).', '⚔️', 'battle', 33.0177, 35.5685, 2, ARRAY['era_judges', 'era_monarchy']::text[], ARRAY['joshua', 'deborah', 'barak', 'solomon']::text[], true),
    ('hebron', '헤브론 (마므레)', '아브라함이 마므레 상수리 나무 아래 거하던 곳. 다윗이 처음 왕으로 즉위한 도시 (창 13:18, 삼하 2:1-4).', '🌲', 'city', 31.5326, 35.0998, 1, ARRAY['era_patriarch', 'era_monarchy']::text[], ARRAY['abraham', 'david']::text[], true),
    ('heshbon', '헤스본', '아모리 왕 시혼의 수도. 이스라엘이 요단 동편에서 정복한 첫 큰 도시. 후일 르우벤·갓 지파의 영토 (민 21장, 수 13장).', '⚔️', 'battle', 31.8, 35.81, 2, ARRAY['era_exodus', 'era_judges']::text[], ARRAY['moses', 'joshua']::text[], true),
    ('jericho', '여리고', '여호수아의 외침과 함께 성벽이 무너진 도시. 가나안 정복의 첫 관문. 예수께서 삭개오를 만난 곳 (수 6장, 눅 19장).', '🏰', 'battle', 31.8744, 35.4441, 0, ARRAY['era_exodus', 'era_judges', 'era_nt_public_ministry']::text[], ARRAY['joshua', 'rahab', 'jesus']::text[], true),
    ('jerusalem_damascus_gate', '예루살렘 다메섹 문', '예루살렘 북쪽 성문. 사도 바울이 회심 전 다메섹으로 향하던 길과 연결되는 상징적 위치.', '🚪', 'city_gate', 31.7821, 35.2305, 1, ARRAY['era_monarchy', 'era_nt_public_ministry', 'era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('jerusalem_temple', '예루살렘 성전', '솔로몬이 모리아산에 세운 성전. 바벨론에 의해 파괴된 후 스룹바벨이 재건. 헤롯이 확장한 두 번째 성전을 예수께서 거니심 (왕상 6장, 스 6장, 마 24장).', '🏛️', 'temple', 31.778, 35.2354, 0, ARRAY['era_monarchy', 'era_exile_return', 'era_nt_public_ministry']::text[], ARRAY['solomon', 'david', 'jesus']::text[], true),
    ('joppa', '욥바', '요나가 다시스로 도망치려 배를 탄 항구. 베드로가 환상을 보고 이방인 고넬료에게로 부름받은 곳 (욘 1장, 행 10장).', '⛵', 'city', 32.054, 34.753, 1, ARRAY['era_monarchy', 'era_exile_return', 'era_nt_apostolic']::text[], ARRAY['jonah', 'peter']::text[], true),
    ('jordan_river', '요단강', '이스라엘이 가나안 입성 직전 건넌 강. 엘리야가 승천하기 전 갈라놓은 곳, 예수께서 세례 요한에게 세례받으신 곳 (수 3장, 왕하 2장, 마 3장).', '💦', 'water', 32.311, 35.5688, 0, ARRAY['era_exodus', 'era_judges', 'era_monarchy', 'era_nt_public_ministry']::text[], ARRAY['joshua', 'jesus', 'john_baptist', 'elijah', 'elisha']::text[], true),
    ('judean_wilderness', '유다 광야', '예루살렘 동쪽의 거친 광야. 다윗이 사울을 피해 숨던 곳, 세례 요한의 활동 무대, 예수께서 40일 시험을 받으신 곳 (삼상 23장, 마 3-4장).', '🏜️', 'wilderness', 31.6, 35.4, 2, ARRAY['era_monarchy', 'era_nt_public_ministry']::text[], ARRAY['david', 'jesus', 'john_baptist']::text[], true),
    ('kadesh_barnea', '가데스 바네아', '12 정탐꾼이 가나안을 정탐한 후 돌아온 곳. 광야 38년의 거점 (민 13장).', '👀', 'wilderness', 30.66, 34.42, 1, ARRAY['era_exodus']::text[], ARRAY['moses', 'joshua', 'caleb']::text[], true),
    ('kebar_river', '그발 강', '에스겔이 포로 중 하나님의 영광 환상을 본 강 (겔 1장).', '👁️', 'water', 32.65, 44.6, 2, ARRAY['era_exile_return']::text[], ARRAY['ezekiel']::text[], true),
    ('kishon_river', '기손 강', '드보라와 바락이 시스라의 군대를 휩쓴 강. 후일 엘리야가 갈멜산에서 바알 선지자들을 처단해 시체가 던져진 강 (삿 5:21, 왕상 18:40).', '🌊', 'water', 32.55, 35.1, 2, ARRAY['era_judges', 'era_monarchy']::text[], ARRAY['deborah', 'barak', 'elijah']::text[], true),
    ('laodicea', '라오디게아', '요한계시록 7교회 중 일곱째. "차지도 덥지도 않은" 미지근함을 책망받은 교회 (계 3:14-22).', '🌡️', 'city', 37.839, 29.108, 1, ARRAY['era_nt_apostolic', 'era_nt_consummation']::text[], ARRAY['paul', 'john']::text[], true),
    ('lystra', '루스드라', '바울이 앉은뱅이를 일으키자 사람들이 그를 헤르메스로 오인해 신으로 모시려 한 곳. 후일 디모데의 고향 (행 14장, 16장).', '🦮', 'city', 37.578, 32.448, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'barnabas', 'timothy']::text[], true),
    ('machpelah', '막벨라 굴', '아브라함, 사라, 이삭, 리브가, 야곱, 레아가 묻힌 가족 무덤 (창 23장, 50:13).', '⚰️', 'tomb', 31.5246, 35.111, 1, ARRAY['era_patriarch']::text[], ARRAY['abraham', 'sarah', 'isaac', 'rebekah', 'jacob', 'leah']::text[], true),
    ('malta', '멜리데 (몰타)', '바울이 로마로 압송 중 풍랑을 만나 난파해 표류한 섬. 추장 보블리오의 부친을 고침 (행 28장).', '🏝️', 'island', 35.937, 14.375, 1, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('megiddo', '므깃도 (아마겟돈)', '이스라엘 평원의 전략 요새. 수많은 전투가 벌어진 곳. 요시야 왕이 전사한 곳, 요한계시록의 "아마겟돈" 어원 (왕하 23:29, 계 16:16).', '⚔️', 'battle', 32.584, 35.183, 0, ARRAY['era_judges', 'era_monarchy', 'era_nt_consummation']::text[], ARRAY['josiah']::text[], true),
    ('miletus', '밀레도', '바울이 에베소 장로들과 마지막 작별 인사를 나눈 항구 (행 20:17-38).', '🚢', 'city', 37.53, 27.278, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('mizpah', '미스바', '사무엘이 백성을 모아 회개와 기도의 집회를 연 곳. 사울이 왕으로 뽑힌 곳 (삼상 7장, 10장).', '🙏', 'holy_site', 31.831, 35.18, 1, ARRAY['era_judges', 'era_monarchy']::text[], ARRAY['samuel', 'saul']::text[], true),
    ('mount_ararat', '아라랏산', '노아의 방주가 홍수 후 머물렀다고 전해지는 산 (창 8:4).', '🚢', 'mountain', 39.7019, 44.2986, 0, ARRAY['era_primeval']::text[], ARRAY['noah']::text[], true),
    ('mount_carmel', '갈멜산', '엘리야가 바알 선지자 450명과 대결한 산. 하늘에서 불이 내려와 응답하신 사건의 무대 (왕상 18장).', '🔥', 'mountain', 32.7333, 35.05, 0, ARRAY['era_monarchy']::text[], ARRAY['elijah']::text[], true),
    ('mount_gilboa', '길보아산', '사울과 그의 아들 요나단이 블레셋과 싸우다 전사한 산. 다윗의 애가 (삼상 31장, 삼하 1장).', '🪦', 'battle', 32.543, 35.406, 1, ARRAY['era_monarchy']::text[], ARRAY['saul', 'david']::text[], true),
    ('mount_hermon', '헤르몬산 (변화산)', '예수께서 베드로·야고보·요한과 함께 올라 영광스러운 모습으로 변화하신 산. 모세와 엘리야가 함께 나타남 (마 17장).', '✨', 'mountain', 33.416, 35.857, 1, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'peter', 'james_zebedee', 'john', 'moses', 'elijah']::text[], true),
    ('mount_moriah', '모리아산', '아브라함이 이삭을 번제로 드리려 한 산. 후일 솔로몬 성전이 세워진 자리 (창 22장, 대하 3:1).', '🔥', 'holy_site', 31.778, 35.2354, 0, ARRAY['era_patriarch', 'era_monarchy']::text[], ARRAY['abraham', 'isaac', 'solomon']::text[], true)
)
insert into landmarks (code, name, description, emoji, category, lat, lng, display_priority, era_codes, related_event_codes, is_active)
select code, name, description, emoji, category, lat, lng, display_priority, era_codes, related_event_codes, is_active from seed_landmarks
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  emoji = excluded.emoji,
  category = excluded.category,
  lat = excluded.lat,
  lng = excluded.lng,
  display_priority = excluded.display_priority,
  era_codes = excluded.era_codes,
  related_event_codes = excluded.related_event_codes,
  is_active = excluded.is_active
;

with seed_landmarks (code, name, description, emoji, category, lat, lng, display_priority, era_codes, related_event_codes, is_active) as (
  values
    ('mount_nebo', '느보산', '모세가 약속의 땅을 바라보며 죽은 산. 그의 무덤은 알려지지 않았다 (신 34장).', '🪦', 'tomb', 31.7683, 35.725, 1, ARRAY['era_exodus']::text[], ARRAY['moses']::text[], true),
    ('mount_sinai', '시내산 (호렙산)', '모세가 십계명을 받은 산. 엘리야가 도망쳐 "세미한 음성"을 들은 곳이기도 함 (출 19-20장, 왕상 19장).', '⛰️', 'mountain', 28.5392, 33.9756, 0, ARRAY['era_exodus', 'era_monarchy']::text[], ARRAY['moses', 'elijah']::text[], true),
    ('mount_tabor', '다볼산', '사사 드보라와 바락이 시스라의 군대를 격파한 산 (삿 4장). 변화산은 별도 헤르몬산이 정설이라 era 는 사사 시대로만.', '⛰️', 'battle', 32.687, 35.39, 1, ARRAY['era_judges']::text[], ARRAY['deborah', 'barak']::text[], true),
    ('nazareth', '나사렛', '예수께서 자라신 마을. 마리아가 천사 가브리엘에게 수태 고지를 받은 곳 (눅 1장).', '🏘️', 'city', 32.6996, 35.3035, 0, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'mary']::text[], true),
    ('nineveh', '니느웨', '앗수르 제국의 수도. 요나가 회개를 외쳐 도시 전체가 돌이킨 곳. 후일 나훔 선지자가 멸망을 예언 (욘 3장, 나 1장).', '🐋', 'city', 36.3589, 43.1525, 0, ARRAY['era_monarchy', 'era_exile_return']::text[], ARRAY['jonah']::text[], true),
    ('patmos', '밧모섬', '사도 요한이 박해로 유배되어 요한계시록의 환상을 본 작은 섬 (계 1:9).', '👁️', 'island', 37.32, 26.55, 0, ARRAY['era_nt_consummation']::text[], ARRAY['john']::text[], true),
    ('peniel', '브니엘', '야곱이 하나님의 사자와 씨름하고 "이스라엘"이라는 이름을 받은 곳 (창 32:22-32).', '🤼', 'monument', 32.18, 35.71, 1, ARRAY['era_patriarch']::text[], ARRAY['jacob']::text[], true),
    ('pergamon', '버가모', '요한계시록 7교code. 사탄의 보좌가 있는 곳. 안디바가 순교한 곳 (계 2:12-17).', '⚔️', 'city', 39.131, 27.184, 1, ARRAY['era_nt_consummation']::text[], ARRAY['john']::text[], true),
    ('philadelphia', '빌라델비아', '요한계시록 7교회 중 여섯째. "열린 문"의 약속을 받은 신실한 교회 (계 3:7-13).', '🚪', 'city', 38.355, 28.519, 2, ARRAY['era_nt_consummation']::text[], ARRAY['john']::text[], true),
    ('philippi', '빌립보', '바울의 유럽 첫 선교지. 자색 옷감 장수 루디아의 회심, 옥에서 찬송하다 옥문이 열린 사건 (행 16장).', '⛓️', 'prison', 41.014, 24.286, 1, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'silas']::text[], true),
    ('rachel_tomb', '라헬 무덤', '야곱의 사랑하는 아내 라헬이 베냐민을 낳다 죽어 묻힌 곳. 베들레헴 길 위의 기둥 (창 35:19-20). 마 2:18 의 ''라헬이 자식 위해 우는'' 은 인용일 뿐이라 era 는 족장 시대로만.', '⚰️', 'tomb', 31.72, 35.202, 2, ARRAY['era_patriarch']::text[], ARRAY['jacob', 'rachel', 'benjamin']::text[], true),
    ('rameses', '라암셋', '이스라엘이 노예 노동으로 짓던 국고성. 출애굽 출발지 (출 1:11, 12:37).', '🧱', 'city', 30.63, 31.85, 2, ARRAY['era_exodus']::text[], ARRAY['moses', 'pharaoh']::text[], true),
    ('red_sea', '홍해', '출애굽 때 모세가 지팡이를 들자 갈라진 바다. 이스라엘이 마른 땅을 밟고 건넘 (출 14장).', '🌊', 'water', 28.0, 33.5, 0, ARRAY['era_exodus']::text[], ARRAY['moses']::text[], true),
    ('rephidim', '르비딤', '모세가 반석을 쳐 물을 낸 곳. 아말렉과 첫 전투를 벌인 곳 (출 17장).', '⚔️', 'battle', 28.7, 33.6, 2, ARRAY['era_exodus']::text[], ARRAY['moses', 'aaron', 'joshua']::text[], true),
    ('rome', '로마', '사도 바울이 마지막에 도착하여 셋방에 거하며 복음을 전한 제국의 수도. 후일 베드로와 함께 순교 (행 28장, 롬 1장).', '🦅', 'city', 41.8967, 12.4823, 0, ARRAY['era_nt_apostolic', 'era_nt_post_apostolic']::text[], ARRAY['paul', 'peter']::text[], true),
    ('salamis_cyprus', '살라미 (구브로)', '바나바와 바울의 1차 선교 여행 첫 기항지. 구브로(키프로스) 동쪽 항구 (행 13:5).', '🚢', 'city', 35.181, 33.904, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'barnabas']::text[], true),
    ('samaria', '사마리아', '오므리가 세운 북왕국 이스라엘의 수도. 아합과 이세벨의 우상 숭배 중심지 (왕상 16장).', '👑', 'city', 32.279, 35.19, 1, ARRAY['era_monarchy']::text[], ARRAY['ahab', 'elijah', 'elisha']::text[], true),
    ('sardis', '사데', '요한계시록 7교회 중 다섯째. "살았다 하는 이름은 가졌으나 죽은 자"라 책망받은 교회 (계 3:1-6).', '💤', 'city', 38.488, 28.04, 2, ARRAY['era_nt_consummation']::text[], ARRAY['john']::text[], true),
    ('sea_of_galilee', '갈릴리 호수', '예수의 제자 다수가 어부였던 호수. 풍랑을 잠재우신 사건과 오병이어의 무대 (마 8장, 14장).', '🌊', 'water', 32.8333, 35.5833, 0, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus', 'peter', 'andrew', 'john', 'james_zebedee']::text[], true),
    ('shechem', '세겜', '아브라함이 가나안 입성 후 처음 제단을 쌓은 곳. 야곱이 우물을 파고 요셉이 묻힌 곳, 여호수아가 언약을 갱신한 곳 (창 12:6, 33:18, 수 24장).', '⛺', 'city', 32.2137, 35.281, 1, ARRAY['era_patriarch', 'era_judges', 'era_monarchy']::text[], ARRAY['abraham', 'jacob', 'joseph', 'joshua']::text[], true),
    ('shiloh', '실로', '여호수아 시대부터 약 300년 동안 회막(성막)이 머문 곳. 한나가 사무엘을 위해 기도한 곳 (수 18장, 삼상 1장).', '⛪', 'temple', 32.056, 35.29, 1, ARRAY['era_judges']::text[], ARRAY['joshua', 'samuel', 'hannah', 'eli']::text[], true),
    ('smyrna', '서머나', '요한계시록 7교회 중 둘째. 환난 받는 교회에 "죽도록 충성하라"고 말씀하신 곳 (계 2:8-11).', '👑', 'city', 38.419, 27.129, 1, ARRAY['era_nt_consummation']::text[], ARRAY['john']::text[], true),
    ('sodom', '소돔 (추정 위치)', '롯이 살던 도시. 죄악으로 인해 하나님의 심판을 받음 (창 19장).', '💥', 'city', 31.0667, 35.45, 1, ARRAY['era_patriarch']::text[], ARRAY['abraham', 'lot']::text[], true),
    ('susa', '수사', '페르시아 제국의 수도 중 하나. 에스더가 왕후가 되어 민족을 구한 무대. 느헤미야가 왕의 술 맡은 자였던 곳 (에 1장, 느 1장).', '👑', 'city', 32.1881, 48.2581, 0, ARRAY['era_exile_return']::text[], ARRAY['esther', 'mordecai', 'nehemiah', 'daniel']::text[], true),
    ('sychar_well', '수가 (야곱의 우물)', '예수께서 사마리아 여인을 만나 "내가 주는 물을 마시는 자는 영원히 목마르지 않으리라" 말씀하신 곳 (요 4장).', '🪣', 'holy_site', 32.21, 35.28, 1, ARRAY['era_nt_public_ministry']::text[], ARRAY['jesus']::text[], true),
    ('tarsus', '다소', '사도 바울의 출생지. 길리기아 지방의 학문 도시 (행 9:11, 22:3).', '📜', 'city', 36.918, 34.896, 1, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('thessalonica', '데살로니가', '바울이 회당에서 3주간 변론한 곳. 후에 데살로니가전·후서를 보낸 교회 (행 17장).', '📨', 'city', 40.64, 22.944, 1, ARRAY['era_nt_apostolic']::text[], ARRAY['paul', 'silas']::text[], true),
    ('thyatira', '두아디라', '요한계시록 7교회 중 넷째. 자칭 선지자 "이세벨"이 가르침을 변질시킨 교회 (계 2:18-29).', '🎨', 'city', 38.92, 27.84, 2, ARRAY['era_nt_consummation']::text[], ARRAY['john']::text[], true),
    ('tower_of_babel', '바벨탑 (시날 평원)', '사람들이 하늘에 닿으려 쌓다가 언어가 흩어진 곳. 시날 평원, 후일 바벨론 자리 (창 11:1-9).', '🏗️', 'monument', 32.54, 44.45, 0, ARRAY['era_primeval']::text[], ARRAY['noah']::text[], true),
    ('troas', '드로아', '바울이 "마게도냐 사람이 건너와 우리를 도우라" 환상을 본 항구. 유럽 선교의 출발점. 후일 유두고가 창에서 떨어진 곳 (행 16:8-10, 20:6-12).', '🚢', 'city', 39.76, 26.16, 2, ARRAY['era_nt_apostolic']::text[], ARRAY['paul']::text[], true),
    ('tyre', '두로', '예수께서 수로보니게 여인의 딸을 고치신 곳. 사도 바울이 7일간 머문 항구 (마 15장, 행 21장).', '🏺', 'city', 33.27, 35.2, 2, ARRAY['era_nt_public_ministry', 'era_nt_apostolic']::text[], ARRAY['jesus', 'paul']::text[], true),
    ('ur', '우르', '아브라함이 하나님의 부르심을 따라 떠난 고향. 메소포타미아 남부 (창 11:31, 15:7).', '🏺', 'city', 30.9624, 46.1031, 0, ARRAY['era_patriarch']::text[], ARRAY['abraham']::text[], true),
    ('wilderness_of_paran', '바란 광야', '이스마엘이 거주한 광야. 출애굽 후 12 정탐꾼이 가데스에서 출발해 가나안을 정탐한 거점 (창 21장, 민 13장).', '🏜️', 'wilderness', 29.5, 34.5, 2, ARRAY['era_patriarch', 'era_exodus']::text[], ARRAY['ishmael', 'moses']::text[], true),
    ('wilderness_of_zin', '신 광야', '이스라엘이 광야 38년을 보낸 핵심 무대. 가데스 바네아가 이 광야에 속함. 모세가 반석을 두 번 친 므리바도 이 지역 (민 20장).', '🏜️', 'wilderness', 30.5, 34.7, 2, ARRAY['era_exodus']::text[], ARRAY['moses', 'aaron']::text[], true),
    ('zarephath', '사르밧', '엘리야가 가뭄 중 머물며 과부의 마지막 가루로 음식을 받고 그녀의 아들을 살린 곳 (왕상 17장).', '🥖', 'city', 33.27, 35.2, 2, ARRAY['era_monarchy']::text[], ARRAY['elijah']::text[], true)
)
insert into landmarks (code, name, description, emoji, category, lat, lng, display_priority, era_codes, related_event_codes, is_active)
select code, name, description, emoji, category, lat, lng, display_priority, era_codes, related_event_codes, is_active from seed_landmarks
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  emoji = excluded.emoji,
  category = excluded.category,
  lat = excluded.lat,
  lng = excluded.lng,
  display_priority = excluded.display_priority,
  era_codes = excluded.era_codes,
  related_event_codes = excluded.related_event_codes,
  is_active = excluded.is_active
;

commit;
