#!/usr/bin/env python3
"""Build SQL seed for the era_boundaries table.

era_boundaries 는 시대(era) 별 거친 지리 영역 폴리곤을 담는 카탈로그. 사용자가
시대를 선택했을 때 지도 위에 반투명 영역으로 그려진다. 한 시대가 분리된 지역
(예: 메소포타미아 + 가나안)을 포함하면 polygons 배열에 여러 폴리곤을 둔다.

JSON 스키마 (한 항목):
    {
      "era_code": "era_patriarch",     # eras.code 와 매칭
      "color": "#F4A261",              # 외곽선 + 채움 색 (#RRGGBB 또는 #AARRGGBB)
      "fill_opacity": 0.18,            # 채움 알파 (0.0 ~ 1.0)
      "display_order": 2,
      "polygons": [
        [[lat, lng], [lat, lng], ...], # 폴리곤 1
        [[lat, lng], ...]              # 폴리곤 2 (선택)
      ]
    }

DB 행은 (era_id, polygon_index) UNIQUE — JSON 의 polygons 배열 인덱스가
polygon_index 가 된다. era_code 는 INSERT 시점에 SELECT id FROM eras WHERE
code = ... 로 era_id 로 변환된다.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build SQL seed for the era_boundaries table."
    )
    parser.add_argument(
        "--input",
        default="assets/landmarks/era_boundaries.json",
        help="Input JSON path.",
    )
    parser.add_argument(
        "--output",
        default="supabase/200_stories/era_boundaries_seed.sql",
        help="Output SQL path.",
    )
    return parser.parse_args()


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_value(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    return sql_literal(str(value))


def load_rows(input_path: Path) -> list[dict[str, Any]]:
    if not input_path.exists():
        raise FileNotFoundError(f"Input JSON not found: {input_path}")
    raw = json.loads(input_path.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError(f"JSON root must be list: {input_path}")
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, int]] = set()
    for item in raw:
        if not isinstance(item, dict):
            raise ValueError(f"Row must be object: {item!r}")
        era_code = str(item.get("era_code", "")).strip()
        if not era_code:
            raise ValueError(f"Missing era_code: {item!r}")
        polygons = item.get("polygons")
        if not isinstance(polygons, list) or not polygons:
            raise ValueError(f"era_code={era_code} must have non-empty polygons")
        color = str(item.get("color") or "#FF8800").strip()
        fill_opacity = float(item.get("fill_opacity") or 0.18)
        display_order = int(item.get("display_order") or 0)
        for polygon_index, polygon in enumerate(polygons):
            if not isinstance(polygon, list) or len(polygon) < 3:
                raise ValueError(
                    f"era_code={era_code} polygon #{polygon_index} must have >= 3 points"
                )
            cleaned: list[list[float]] = []
            for point in polygon:
                if not isinstance(point, list) or len(point) < 2:
                    raise ValueError(
                        f"era_code={era_code} polygon #{polygon_index}: invalid point {point!r}"
                    )
                lat = float(point[0])
                lng = float(point[1])
                cleaned.append([lat, lng])
            key = (era_code, polygon_index)
            if key in seen:
                raise ValueError(f"Duplicate (era_code, polygon_index)={key!r}")
            seen.add(key)
            rows.append(
                {
                    "era_code": era_code,
                    "polygon_index": polygon_index,
                    "polygon": cleaned,
                    "color": color,
                    "fill_opacity": fill_opacity,
                    "display_order": display_order,
                }
            )
    rows.sort(key=lambda r: (r["display_order"], r["era_code"], r["polygon_index"]))
    return rows


def build_sql(rows: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("-- Generated by tools/seed/build_era_boundaries_seed_sql.py")
    lines.append("-- Target table: era_boundaries")
    lines.append("begin;")
    lines.append("")

    if rows:
        keep_keys = sorted({(r["era_code"], r["polygon_index"]) for r in rows})
        in_pairs = ", ".join(f"({sql_literal(code)}, {idx})" for code, idx in keep_keys)
        lines.append("-- Drop boundaries not present in current JSON")
        lines.append(
            "delete from era_boundaries\n"
            "  where (\n"
            "    (select code from eras where id = era_boundaries.era_id),\n"
            "    polygon_index\n"
            f"  ) not in ({in_pairs});"
        )
        lines.append("")

    for row in rows:
        polygon_json = json.dumps(row["polygon"], ensure_ascii=False)
        lines.append("insert into era_boundaries")
        lines.append(
            "  (era_id, polygon_index, polygon, color, fill_opacity, display_order)"
        )
        lines.append(
            "select e.id, "
            f"{row['polygon_index']}, "
            f"{sql_literal(polygon_json)}::jsonb, "
            f"{sql_literal(row['color'])}, "
            f"{row['fill_opacity']}, "
            f"{row['display_order']}"
        )
        lines.append("  from eras e " f"where e.code = {sql_literal(row['era_code'])}")
        lines.append("on conflict (era_id, polygon_index) do update set")
        lines.append("  polygon = excluded.polygon,")
        lines.append("  color = excluded.color,")
        lines.append("  fill_opacity = excluded.fill_opacity,")
        lines.append("  display_order = excluded.display_order")
        lines.append(";")
        lines.append("")

    lines.append("commit;")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    rows = load_rows(input_path)
    sql_text = build_sql(rows)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sql_text, encoding="utf-8")

    eras = sorted({r["era_code"] for r in rows})
    print(f"input              : {input_path}")
    print(f"era count          : {len(eras)}  ({', '.join(eras)})")
    print(f"polygon row count  : {len(rows)}")
    print(f"output             : {output_path}")
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
