#!/usr/bin/env python3
"""landmarks.json → supabase/200_stories/landmarks_seed.sql.

성경 전체 시대 region/landmark 카탈로그를 landmarks 테이블에 UPSERT 한다.

Output schema 가정:
  landmarks (
    id, code, name, description, emoji, category,
    lat, lng,                       -- non-region 의 정확한 점, region 의 라벨 위치
    polygon jsonb,                  -- kind='region' 만 채움
    kind text,                       -- 'region' | 'mountain' | 'city' | ...
    parent_landmark_id uuid,         -- non-region → 그 region. region 은 NULL.
    alias_group_id uuid,             -- (deprecated, 항상 NULL — 호환만 유지)
    display_priority int,
    era_codes text[],
    related_event_codes text[],
    is_active bool,
    ...
  )

규칙:
  - region: era_codes 다중 가능
  - landmark (non-region): era_codes 단일, 코드 prefix 'lm_<era_short>_<name>'
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "assets" / "landmarks" / "landmarks.json"
OUT_PATH = ROOT / "supabase" / "200_stories" / "landmarks_seed.sql"


def sql_str(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value).replace("'", "''")
    return f"'{s}'"


def sql_text_array(values) -> str:
    if not values:
        return "'{}'::text[]"
    parts = ",".join(f'"{v}"' for v in values)
    return f"'{{{parts}}}'::text[]"


def sql_polygon(polygon) -> str:
    # polygon=None → null (non-region), polygon=[] → '[]'::jsonb (비지리적 region),
    # polygon=[[lat,lng], ...] → 정상 jsonb. region 의 빈 배열도 NOT NULL 제약 통과.
    if polygon is None:
        return "null"
    return f"'{json.dumps(polygon)}'::jsonb"


def emit_row(row, kind, parent_code):
    code = row["code"]
    name = row["name"]
    description = row.get("description")
    emoji = row.get("emoji", "📍")
    category = row.get("category")
    lat = row.get("lat") or row.get("anchor_lat")
    lng = row.get("lng") or row.get("anchor_lng")
    polygon = row.get("polygon") if kind == "region" else None
    display_priority = row.get("display_priority", 0)
    era_codes = row.get("era_codes", [])
    related = row.get("related_event_codes", [])

    parent_clause = (
        f"(select id from landmarks where code = {sql_str(parent_code)})"
        if parent_code
        else "null"
    )
    # alias_group 기능 제거. 컬럼은 호환 위해 유지하되 항상 null.
    alias_clause = "null"

    return (
        f"  ({sql_str(code)}, {sql_str(name)}, {sql_str(description)}, "
        f"{sql_str(emoji)}, {sql_str(category)}, "
        f"{sql_str(lat)}, {sql_str(lng)}, "
        f"{sql_polygon(polygon)}, {sql_str(kind)}, "
        f"{parent_clause}, {alias_clause}, "
        f"{display_priority}, {sql_text_array(era_codes)}, {sql_text_array(related)})"
    )


UPSERT_COLUMNS = (
    "code, name, description, emoji, category, "
    "lat, lng, polygon, kind, parent_landmark_id, alias_group_id, "
    "display_priority, era_codes, related_event_codes"
)

UPSERT_UPDATE = """\
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  emoji = excluded.emoji,
  category = excluded.category,
  lat = excluded.lat,
  lng = excluded.lng,
  polygon = excluded.polygon,
  kind = excluded.kind,
  parent_landmark_id = excluded.parent_landmark_id,
  alias_group_id = excluded.alias_group_id,
  display_priority = excluded.display_priority,
  era_codes = excluded.era_codes,
  related_event_codes = excluded.related_event_codes;"""


def main() -> None:
    with CATALOG_PATH.open() as fp:
        catalog = json.load(fp)

    lines: list[str] = []
    lines.append("-- AUTO-GENERATED by tools/seed/build_landmarks_seed_sql.py")
    lines.append("-- Source: assets/landmarks/landmarks.json")
    lines.append("")
    lines.append("set search_path = public;")
    lines.append("")

    # 1. Regions (parent_landmark_id 없음)
    lines.append("-- ----- regions (큰 영역, polygon 으로 표시) -----")
    if catalog.get("regions"):
        lines.append(f"insert into landmarks ({UPSERT_COLUMNS}) values")
        region_rows = [emit_row(r, "region", None) for r in catalog["regions"]]
        lines.append(",\n".join(region_rows))
        lines.append(UPSERT_UPDATE)
        lines.append("")

    # 2. Landmarks (non-region 마커, parent_landmark_id = region code)
    # JSON 호환: 'anchors' 또는 'landmarks' 키 모두 허용. v3 부터는 'landmarks' 권장.
    point_rows = []
    for key in ("landmarks", "anchors", "minors"):
        for r in catalog.get(key, []) or []:
            kind = r.get("kind") or (
                "anchor"
                if key == "anchors"
                else "minor" if key == "minors" else "point"
            )
            point_rows.append(emit_row(r, kind, r["parent_region_code"]))

    if point_rows:
        lines.append("-- ----- landmarks (non-region 마커, region 에 속함) -----")
        lines.append(f"insert into landmarks ({UPSERT_COLUMNS}) values")
        lines.append(",\n".join(point_rows))
        lines.append(UPSERT_UPDATE)
        lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    region_count = len(catalog.get("regions") or [])
    landmark_count = len(point_rows)
    print(f"Wrote {OUT_PATH}")
    print(f"  {region_count} regions, {landmark_count} landmarks")


if __name__ == "__main__":
    main()
